#!/bin/bash

arr=( ./clusters/local/apps/* )

kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v3.6/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml

for item in "${arr[@]}"; do
    if [ -d "$item" ]; then
        kubectl apply -f $item
    fi
done