apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jwt-forward-auth
  namespace: traefik
spec:
  forwardAuth:
    address: http://identity-service.identity.svc.cluster.local:50051/internal/identity/validate

    authResponseHeaders:
      - user-uuid
      - user-role

    authRequestHeaders:
      - Authorization
