apiVersion: v1
kind: ServiceAccount
metadata:
  name: alloy
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: alloy
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - nodes/proxy
      - pods/log
      - services
      - endpoints
      - events
    verbs: [get, list, watch]
  - nonResourceURLs: [/metrics]
    verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: alloy
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: alloy
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: alloy
  apiGroup: rbac.authorization.k8s.io
