apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./alloy-rbac.yaml
  - ./loki-config.yaml
  - ./loki-statefulset.yaml
  - ./alloy-config.yaml
  - ./alloy-daemon.yaml
  - ./grafana-config.yaml
  - ./grafana-deployment.yaml
  - ./grafana-ingress.yaml
  - ./prometheus-config.yaml
  - ./prometheus-rbac.yaml
  - ./prometheus-statefulset.yaml
