// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: news.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateUploadURLSsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Images        []*ImageMeta           `protobuf:"bytes,2,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadURLSsRequest) Reset() {
	*x = GenerateUploadURLSsRequest{}
	mi := &file_news_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadURLSsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadURLSsRequest) ProtoMessage() {}

func (x *GenerateUploadURLSsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadURLSsRequest.ProtoReflect.Descriptor instead.
func (*GenerateUploadURLSsRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUploadURLSsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateUploadURLSsRequest) GetImages() []*ImageMeta {
	if x != nil {
		return x.Images
	}
	return nil
}

type ImageMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileName      string                 `protobuf:"bytes,1,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Mime          string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageMeta) Reset() {
	*x = ImageMeta{}
	mi := &file_news_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMeta) ProtoMessage() {}

func (x *ImageMeta) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMeta.ProtoReflect.Descriptor instead.
func (*ImageMeta) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{1}
}

func (x *ImageMeta) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ImageMeta) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type UploadTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadUrl     string                 `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	FileKey       string                 `protobuf:"bytes,2,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTarget) Reset() {
	*x = UploadTarget{}
	mi := &file_news_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTarget) ProtoMessage() {}

func (x *UploadTarget) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTarget.ProtoReflect.Descriptor instead.
func (*UploadTarget) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{2}
}

func (x *UploadTarget) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadTarget) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

type GenerateNewUploadURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*UploadTarget        `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNewUploadURLsResponse) Reset() {
	*x = GenerateNewUploadURLsResponse{}
	mi := &file_news_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNewUploadURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNewUploadURLsResponse) ProtoMessage() {}

func (x *GenerateNewUploadURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNewUploadURLsResponse.ProtoReflect.Descriptor instead.
func (*GenerateNewUploadURLsResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateNewUploadURLsResponse) GetTargets() []*UploadTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

type CreateNewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption       string                 `protobuf:"bytes,2,opt,name=caption,proto3" json:"caption,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	FileKeys      []string               `protobuf:"bytes,4,rep,name=file_keys,json=fileKeys,proto3" json:"file_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewRequest) Reset() {
	*x = CreateNewRequest{}
	mi := &file_news_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewRequest) ProtoMessage() {}

func (x *CreateNewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewRequest.ProtoReflect.Descriptor instead.
func (*CreateNewRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{4}
}

func (x *CreateNewRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateNewRequest) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *CreateNewRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateNewRequest) GetFileKeys() []string {
	if x != nil {
		return x.FileKeys
	}
	return nil
}

type New struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewId         string                 `protobuf:"bytes,1,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Caption       string                 `protobuf:"bytes,3,opt,name=caption,proto3" json:"caption,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ImageUrls     []string               `protobuf:"bytes,5,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *New) Reset() {
	*x = New{}
	mi := &file_news_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *New) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*New) ProtoMessage() {}

func (x *New) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use New.ProtoReflect.Descriptor instead.
func (*New) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{5}
}

func (x *New) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

func (x *New) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *New) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *New) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *New) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *New) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateNewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	New           *New                   `protobuf:"bytes,1,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewResponse) Reset() {
	*x = CreateNewResponse{}
	mi := &file_news_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewResponse) ProtoMessage() {}

func (x *CreateNewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewResponse.ProtoReflect.Descriptor instead.
func (*CreateNewResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{6}
}

func (x *CreateNewResponse) GetNew() *New {
	if x != nil {
		return x.New
	}
	return nil
}

type GetNewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewId         string                 `protobuf:"bytes,1,opt,name=new_id,json=newId,proto3" json:"new_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewRequest) Reset() {
	*x = GetNewRequest{}
	mi := &file_news_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewRequest) ProtoMessage() {}

func (x *GetNewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewRequest.ProtoReflect.Descriptor instead.
func (*GetNewRequest) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{7}
}

func (x *GetNewRequest) GetNewId() string {
	if x != nil {
		return x.NewId
	}
	return ""
}

type GetNewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	New           *New                   `protobuf:"bytes,1,opt,name=new,proto3" json:"new,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNewResponse) Reset() {
	*x = GetNewResponse{}
	mi := &file_news_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNewResponse) ProtoMessage() {}

func (x *GetNewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_news_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNewResponse.ProtoReflect.Descriptor instead.
func (*GetNewResponse) Descriptor() ([]byte, []int) {
	return file_news_proto_rawDescGZIP(), []int{8}
}

func (x *GetNewResponse) GetNew() *New {
	if x != nil {
		return x.New
	}
	return nil
}

var File_news_proto protoreflect.FileDescriptor

const file_news_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"news.proto\x12\x04news\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x1aGenerateUploadURLSsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x06images\x18\x02 \x03(\v2\x0f.news.ImageMetaR\x06images\"<\n" +
	"\tImageMeta\x12\x1b\n" +
	"\tfile_name\x18\x01 \x01(\tR\bfileName\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\"H\n" +
	"\fUploadTarget\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\tR\tuploadUrl\x12\x19\n" +
	"\bfile_key\x18\x02 \x01(\tR\afileKey\"M\n" +
	"\x1dGenerateNewUploadURLsResponse\x12,\n" +
	"\atargets\x18\x01 \x03(\v2\x12.news.UploadTargetR\atargets\"v\n" +
	"\x10CreateNewRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acaption\x18\x02 \x01(\tR\acaption\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1b\n" +
	"\tfile_keys\x18\x04 \x03(\tR\bfileKeys\"\xbd\x01\n" +
	"\x03New\x12\x15\n" +
	"\x06new_id\x18\x01 \x01(\tR\x05newId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\acaption\x18\x03 \x01(\tR\acaption\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x05 \x03(\tR\timageUrls\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"0\n" +
	"\x11CreateNewResponse\x12\x1b\n" +
	"\x03new\x18\x01 \x01(\v2\t.news.NewR\x03new\"&\n" +
	"\rGetNewRequest\x12\x15\n" +
	"\x06new_id\x18\x01 \x01(\tR\x05newId\"-\n" +
	"\x0eGetNewResponse\x12\x1b\n" +
	"\x03new\x18\x01 \x01(\v2\t.news.NewR\x03new2\xdf\x01\n" +
	"\vNewsService\x12]\n" +
	"\x14GenerateNewUploadURL\x12 .news.GenerateUploadURLSsRequest\x1a#.news.GenerateNewUploadURLsResponse\x12<\n" +
	"\tCreateNew\x12\x16.news.CreateNewRequest\x1a\x17.news.CreateNewResponse\x123\n" +
	"\x06GetNew\x12\x13.news.GetNewRequest\x1a\x14.news.GetNewResponseB\x04Z\x02./b\x06proto3"

var (
	file_news_proto_rawDescOnce sync.Once
	file_news_proto_rawDescData []byte
)

func file_news_proto_rawDescGZIP() []byte {
	file_news_proto_rawDescOnce.Do(func() {
		file_news_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_news_proto_rawDesc), len(file_news_proto_rawDesc)))
	})
	return file_news_proto_rawDescData
}

var file_news_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_news_proto_goTypes = []any{
	(*GenerateUploadURLSsRequest)(nil),    // 0: news.GenerateUploadURLSsRequest
	(*ImageMeta)(nil),                     // 1: news.ImageMeta
	(*UploadTarget)(nil),                  // 2: news.UploadTarget
	(*GenerateNewUploadURLsResponse)(nil), // 3: news.GenerateNewUploadURLsResponse
	(*CreateNewRequest)(nil),              // 4: news.CreateNewRequest
	(*New)(nil),                           // 5: news.New
	(*CreateNewResponse)(nil),             // 6: news.CreateNewResponse
	(*GetNewRequest)(nil),                 // 7: news.GetNewRequest
	(*GetNewResponse)(nil),                // 8: news.GetNewResponse
	(*timestamppb.Timestamp)(nil),         // 9: google.protobuf.Timestamp
}
var file_news_proto_depIdxs = []int32{
	1, // 0: news.GenerateUploadURLSsRequest.images:type_name -> news.ImageMeta
	2, // 1: news.GenerateNewUploadURLsResponse.targets:type_name -> news.UploadTarget
	9, // 2: news.New.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: news.CreateNewResponse.new:type_name -> news.New
	5, // 4: news.GetNewResponse.new:type_name -> news.New
	0, // 5: news.NewsService.GenerateNewUploadURL:input_type -> news.GenerateUploadURLSsRequest
	4, // 6: news.NewsService.CreateNew:input_type -> news.CreateNewRequest
	7, // 7: news.NewsService.GetNew:input_type -> news.GetNewRequest
	3, // 8: news.NewsService.GenerateNewUploadURL:output_type -> news.GenerateNewUploadURLsResponse
	6, // 9: news.NewsService.CreateNew:output_type -> news.CreateNewResponse
	8, // 10: news.NewsService.GetNew:output_type -> news.GetNewResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_news_proto_init() }
func file_news_proto_init() {
	if File_news_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_news_proto_rawDesc), len(file_news_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_news_proto_goTypes,
		DependencyIndexes: file_news_proto_depIdxs,
		MessageInfos:      file_news_proto_msgTypes,
	}.Build()
	File_news_proto = out.File
	file_news_proto_goTypes = nil
	file_news_proto_depIdxs = nil
}
