// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/news.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsService_GenerateBodyUploadURL_FullMethodName = "/news.NewsService/GenerateBodyUploadURL"
	NewsService_GenerateNewUploadURLs_FullMethodName = "/news.NewsService/GenerateNewUploadURLs"
	NewsService_CreateNew_FullMethodName             = "/news.NewsService/CreateNew"
	NewsService_GetNew_FullMethodName                = "/news.NewsService/GetNew"
	NewsService_ListNews_FullMethodName              = "/news.NewsService/ListNews"
	NewsService_DeleteNew_FullMethodName             = "/news.NewsService/DeleteNew"
	NewsService_ListNewsByUser_FullMethodName        = "/news.NewsService/ListNewsByUser"
)

// NewsServiceClient is the client API for NewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsServiceClient interface {
	GenerateBodyUploadURL(ctx context.Context, in *GenerateBodyUploadURLRequest, opts ...grpc.CallOption) (*GenerateBodyUploadURLResponse, error)
	GenerateNewUploadURLs(ctx context.Context, in *GenerateUploadURLSsRequest, opts ...grpc.CallOption) (*GenerateNewUploadURLsResponse, error)
	CreateNew(ctx context.Context, in *CreateNewRequest, opts ...grpc.CallOption) (*CreateNewResponse, error)
	GetNew(ctx context.Context, in *GetNewRequest, opts ...grpc.CallOption) (*GetNewResponse, error)
	ListNews(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error)
	DeleteNew(ctx context.Context, in *DeleteNewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListNewsByUser(ctx context.Context, in *ListNewsByUserRequest, opts ...grpc.CallOption) (*ListNewsResponse, error)
}

type newsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsServiceClient(cc grpc.ClientConnInterface) NewsServiceClient {
	return &newsServiceClient{cc}
}

func (c *newsServiceClient) GenerateBodyUploadURL(ctx context.Context, in *GenerateBodyUploadURLRequest, opts ...grpc.CallOption) (*GenerateBodyUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateBodyUploadURLResponse)
	err := c.cc.Invoke(ctx, NewsService_GenerateBodyUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GenerateNewUploadURLs(ctx context.Context, in *GenerateUploadURLSsRequest, opts ...grpc.CallOption) (*GenerateNewUploadURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateNewUploadURLsResponse)
	err := c.cc.Invoke(ctx, NewsService_GenerateNewUploadURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) CreateNew(ctx context.Context, in *CreateNewRequest, opts ...grpc.CallOption) (*CreateNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewResponse)
	err := c.cc.Invoke(ctx, NewsService_CreateNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GetNew(ctx context.Context, in *GetNewRequest, opts ...grpc.CallOption) (*GetNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewResponse)
	err := c.cc.Invoke(ctx, NewsService_GetNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) ListNews(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNewsResponse)
	err := c.cc.Invoke(ctx, NewsService_ListNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) DeleteNew(ctx context.Context, in *DeleteNewRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NewsService_DeleteNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) ListNewsByUser(ctx context.Context, in *ListNewsByUserRequest, opts ...grpc.CallOption) (*ListNewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNewsResponse)
	err := c.cc.Invoke(ctx, NewsService_ListNewsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsServiceServer is the server API for NewsService service.
// All implementations must embed UnimplementedNewsServiceServer
// for forward compatibility.
type NewsServiceServer interface {
	GenerateBodyUploadURL(context.Context, *GenerateBodyUploadURLRequest) (*GenerateBodyUploadURLResponse, error)
	GenerateNewUploadURLs(context.Context, *GenerateUploadURLSsRequest) (*GenerateNewUploadURLsResponse, error)
	CreateNew(context.Context, *CreateNewRequest) (*CreateNewResponse, error)
	GetNew(context.Context, *GetNewRequest) (*GetNewResponse, error)
	ListNews(context.Context, *ListNewsRequest) (*ListNewsResponse, error)
	DeleteNew(context.Context, *DeleteNewRequest) (*emptypb.Empty, error)
	ListNewsByUser(context.Context, *ListNewsByUserRequest) (*ListNewsResponse, error)
	mustEmbedUnimplementedNewsServiceServer()
}

// UnimplementedNewsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsServiceServer struct{}

func (UnimplementedNewsServiceServer) GenerateBodyUploadURL(context.Context, *GenerateBodyUploadURLRequest) (*GenerateBodyUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateBodyUploadURL not implemented")
}
func (UnimplementedNewsServiceServer) GenerateNewUploadURLs(context.Context, *GenerateUploadURLSsRequest) (*GenerateNewUploadURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateNewUploadURLs not implemented")
}
func (UnimplementedNewsServiceServer) CreateNew(context.Context, *CreateNewRequest) (*CreateNewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNew not implemented")
}
func (UnimplementedNewsServiceServer) GetNew(context.Context, *GetNewRequest) (*GetNewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNew not implemented")
}
func (UnimplementedNewsServiceServer) ListNews(context.Context, *ListNewsRequest) (*ListNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNews not implemented")
}
func (UnimplementedNewsServiceServer) DeleteNew(context.Context, *DeleteNewRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNew not implemented")
}
func (UnimplementedNewsServiceServer) ListNewsByUser(context.Context, *ListNewsByUserRequest) (*ListNewsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNewsByUser not implemented")
}
func (UnimplementedNewsServiceServer) mustEmbedUnimplementedNewsServiceServer() {}
func (UnimplementedNewsServiceServer) testEmbeddedByValue()                     {}

// UnsafeNewsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsServiceServer will
// result in compilation errors.
type UnsafeNewsServiceServer interface {
	mustEmbedUnimplementedNewsServiceServer()
}

func RegisterNewsServiceServer(s grpc.ServiceRegistrar, srv NewsServiceServer) {
	// If the following call panics, it indicates UnimplementedNewsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsService_ServiceDesc, srv)
}

func _NewsService_GenerateBodyUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateBodyUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GenerateBodyUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GenerateBodyUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GenerateBodyUploadURL(ctx, req.(*GenerateBodyUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GenerateNewUploadURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUploadURLSsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GenerateNewUploadURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GenerateNewUploadURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GenerateNewUploadURLs(ctx, req.(*GenerateUploadURLSsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_CreateNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).CreateNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_CreateNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).CreateNew(ctx, req.(*CreateNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GetNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GetNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GetNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GetNew(ctx, req.(*GetNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_ListNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).ListNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_ListNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).ListNews(ctx, req.(*ListNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_DeleteNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).DeleteNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_DeleteNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).DeleteNew(ctx, req.(*DeleteNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_ListNewsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNewsByUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).ListNewsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_ListNewsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).ListNewsByUser(ctx, req.(*ListNewsByUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsService_ServiceDesc is the grpc.ServiceDesc for NewsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news.NewsService",
	HandlerType: (*NewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateBodyUploadURL",
			Handler:    _NewsService_GenerateBodyUploadURL_Handler,
		},
		{
			MethodName: "GenerateNewUploadURLs",
			Handler:    _NewsService_GenerateNewUploadURLs_Handler,
		},
		{
			MethodName: "CreateNew",
			Handler:    _NewsService_CreateNew_Handler,
		},
		{
			MethodName: "GetNew",
			Handler:    _NewsService_GetNew_Handler,
		},
		{
			MethodName: "ListNews",
			Handler:    _NewsService_ListNews_Handler,
		},
		{
			MethodName: "DeleteNew",
			Handler:    _NewsService_DeleteNew_Handler,
		},
		{
			MethodName: "ListNewsByUser",
			Handler:    _NewsService_ListNewsByUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/news.proto",
}
