// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: news.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NewsService_GenerateNewUploadURL_FullMethodName = "/news.NewsService/GenerateNewUploadURL"
	NewsService_CreateNew_FullMethodName            = "/news.NewsService/CreateNew"
	NewsService_GetNew_FullMethodName               = "/news.NewsService/GetNew"
)

// NewsServiceClient is the client API for NewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NewsServiceClient interface {
	GenerateNewUploadURL(ctx context.Context, in *GenerateUploadURLSsRequest, opts ...grpc.CallOption) (*GenerateNewUploadURLsResponse, error)
	CreateNew(ctx context.Context, in *CreateNewRequest, opts ...grpc.CallOption) (*CreateNewResponse, error)
	GetNew(ctx context.Context, in *GetNewRequest, opts ...grpc.CallOption) (*GetNewResponse, error)
}

type newsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNewsServiceClient(cc grpc.ClientConnInterface) NewsServiceClient {
	return &newsServiceClient{cc}
}

func (c *newsServiceClient) GenerateNewUploadURL(ctx context.Context, in *GenerateUploadURLSsRequest, opts ...grpc.CallOption) (*GenerateNewUploadURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateNewUploadURLsResponse)
	err := c.cc.Invoke(ctx, NewsService_GenerateNewUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) CreateNew(ctx context.Context, in *CreateNewRequest, opts ...grpc.CallOption) (*CreateNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNewResponse)
	err := c.cc.Invoke(ctx, NewsService_CreateNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) GetNew(ctx context.Context, in *GetNewRequest, opts ...grpc.CallOption) (*GetNewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNewResponse)
	err := c.cc.Invoke(ctx, NewsService_GetNew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsServiceServer is the server API for NewsService service.
// All implementations must embed UnimplementedNewsServiceServer
// for forward compatibility.
type NewsServiceServer interface {
	GenerateNewUploadURL(context.Context, *GenerateUploadURLSsRequest) (*GenerateNewUploadURLsResponse, error)
	CreateNew(context.Context, *CreateNewRequest) (*CreateNewResponse, error)
	GetNew(context.Context, *GetNewRequest) (*GetNewResponse, error)
	mustEmbedUnimplementedNewsServiceServer()
}

// UnimplementedNewsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNewsServiceServer struct{}

func (UnimplementedNewsServiceServer) GenerateNewUploadURL(context.Context, *GenerateUploadURLSsRequest) (*GenerateNewUploadURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateNewUploadURL not implemented")
}
func (UnimplementedNewsServiceServer) CreateNew(context.Context, *CreateNewRequest) (*CreateNewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNew not implemented")
}
func (UnimplementedNewsServiceServer) GetNew(context.Context, *GetNewRequest) (*GetNewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNew not implemented")
}
func (UnimplementedNewsServiceServer) mustEmbedUnimplementedNewsServiceServer() {}
func (UnimplementedNewsServiceServer) testEmbeddedByValue()                     {}

// UnsafeNewsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NewsServiceServer will
// result in compilation errors.
type UnsafeNewsServiceServer interface {
	mustEmbedUnimplementedNewsServiceServer()
}

func RegisterNewsServiceServer(s grpc.ServiceRegistrar, srv NewsServiceServer) {
	// If the following call panics, it indicates UnimplementedNewsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NewsService_ServiceDesc, srv)
}

func _NewsService_GenerateNewUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateUploadURLSsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GenerateNewUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GenerateNewUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GenerateNewUploadURL(ctx, req.(*GenerateUploadURLSsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_CreateNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).CreateNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_CreateNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).CreateNew(ctx, req.(*CreateNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_GetNew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).GetNew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NewsService_GetNew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).GetNew(ctx, req.(*GetNewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NewsService_ServiceDesc is the grpc.ServiceDesc for NewsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NewsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "news.NewsService",
	HandlerType: (*NewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateNewUploadURL",
			Handler:    _NewsService_GenerateNewUploadURL_Handler,
		},
		{
			MethodName: "CreateNew",
			Handler:    _NewsService_CreateNew_Handler,
		},
		{
			MethodName: "GetNew",
			Handler:    _NewsService_GetNew_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "news.proto",
}
