// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/group.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupService_AssignCuratorToSenior_FullMethodName   = "/group.GroupService/AssignCuratorToSenior"
	GroupService_AssignCuratorToGroup_FullMethodName    = "/group.GroupService/AssignCuratorToGroup"
	GroupService_RevokeCuratorFromSenior_FullMethodName = "/group.GroupService/RevokeCuratorFromSenior"
	GroupService_RevokeCuratorFromGroup_FullMethodName  = "/group.GroupService/RevokeCuratorFromGroup"
	GroupService_AddCurator_FullMethodName              = "/group.GroupService/AddCurator"
	GroupService_RevokeCurator_FullMethodName           = "/group.GroupService/RevokeCurator"
	GroupService_GroupsCurators_FullMethodName          = "/group.GroupService/GroupsCurators"
	GroupService_AddMember_FullMethodName               = "/group.GroupService/AddMember"
	GroupService_RemoveMember_FullMethodName            = "/group.GroupService/RemoveMember"
	GroupService_MembersGroups_FullMethodName           = "/group.GroupService/MembersGroups"
	GroupService_ListMembers_FullMethodName             = "/group.GroupService/ListMembers"
	GroupService_Group_FullMethodName                   = "/group.GroupService/Group"
	GroupService_CreateGroup_FullMethodName             = "/group.GroupService/CreateGroup"
	GroupService_SearchGroup_FullMethodName             = "/group.GroupService/SearchGroup"
	GroupService_DeleteGroup_FullMethodName             = "/group.GroupService/DeleteGroup"
	GroupService_ListGroups_FullMethodName              = "/group.GroupService/ListGroups"
	GroupService_CuratorsGroups_FullMethodName          = "/group.GroupService/CuratorsGroups"
)

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupServiceClient interface {
	AssignCuratorToSenior(ctx context.Context, in *AssignCuratorToSeniorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AssignCuratorToGroup(ctx context.Context, in *AssignCuratorToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeCuratorFromSenior(ctx context.Context, in *RevokeCuratorFromSeniorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeCuratorFromGroup(ctx context.Context, in *RevokeCuratorFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddCurator(ctx context.Context, in *AddCuratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RevokeCurator(ctx context.Context, in *RevokeCuratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GroupsCurators(ctx context.Context, in *GroupsCuratorsRequest, opts ...grpc.CallOption) (*GroupsCuratorsResponse, error)
	AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MembersGroups(ctx context.Context, in *MembersGroupsRequest, opts ...grpc.CallOption) (*MembersGroupsResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error)
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SearchGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*SearchGroupResponse, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	CuratorsGroups(ctx context.Context, in *CuratorsGroupsRequest, opts ...grpc.CallOption) (*CuratorsGroupsResponse, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) AssignCuratorToSenior(ctx context.Context, in *AssignCuratorToSeniorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_AssignCuratorToSenior_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AssignCuratorToGroup(ctx context.Context, in *AssignCuratorToGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_AssignCuratorToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RevokeCuratorFromSenior(ctx context.Context, in *RevokeCuratorFromSeniorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_RevokeCuratorFromSenior_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RevokeCuratorFromGroup(ctx context.Context, in *RevokeCuratorFromGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_RevokeCuratorFromGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddCurator(ctx context.Context, in *AddCuratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_AddCurator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RevokeCurator(ctx context.Context, in *RevokeCuratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_RevokeCurator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GroupsCurators(ctx context.Context, in *GroupsCuratorsRequest, opts ...grpc.CallOption) (*GroupsCuratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupsCuratorsResponse)
	err := c.cc.Invoke(ctx, GroupService_GroupsCurators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) AddMember(ctx context.Context, in *AddMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RemoveMember(ctx context.Context, in *RemoveMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) MembersGroups(ctx context.Context, in *MembersGroupsRequest, opts ...grpc.CallOption) (*MembersGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MembersGroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_MembersGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, GroupService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) Group(ctx context.Context, in *GroupRequest, opts ...grpc.CallOption) (*GroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupResponse)
	err := c.cc.Invoke(ctx, GroupService_Group_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) SearchGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*SearchGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_SearchGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GroupService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListGroups(ctx context.Context, in *ListGroupsRequest, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CuratorsGroups(ctx context.Context, in *CuratorsGroupsRequest, opts ...grpc.CallOption) (*CuratorsGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CuratorsGroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_CuratorsGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
// All implementations must embed UnimplementedGroupServiceServer
// for forward compatibility.
type GroupServiceServer interface {
	AssignCuratorToSenior(context.Context, *AssignCuratorToSeniorRequest) (*emptypb.Empty, error)
	AssignCuratorToGroup(context.Context, *AssignCuratorToGroupRequest) (*emptypb.Empty, error)
	RevokeCuratorFromSenior(context.Context, *RevokeCuratorFromSeniorRequest) (*emptypb.Empty, error)
	RevokeCuratorFromGroup(context.Context, *RevokeCuratorFromGroupRequest) (*emptypb.Empty, error)
	AddCurator(context.Context, *AddCuratorRequest) (*emptypb.Empty, error)
	RevokeCurator(context.Context, *RevokeCuratorRequest) (*emptypb.Empty, error)
	GroupsCurators(context.Context, *GroupsCuratorsRequest) (*GroupsCuratorsResponse, error)
	AddMember(context.Context, *AddMemberRequest) (*emptypb.Empty, error)
	RemoveMember(context.Context, *RemoveMemberRequest) (*emptypb.Empty, error)
	MembersGroups(context.Context, *MembersGroupsRequest) (*MembersGroupsResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	Group(context.Context, *GroupRequest) (*GroupResponse, error)
	CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error)
	SearchGroup(context.Context, *CreateGroupRequest) (*SearchGroupResponse, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*emptypb.Empty, error)
	ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error)
	CuratorsGroups(context.Context, *CuratorsGroupsRequest) (*CuratorsGroupsResponse, error)
	mustEmbedUnimplementedGroupServiceServer()
}

// UnimplementedGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServiceServer struct{}

func (UnimplementedGroupServiceServer) AssignCuratorToSenior(context.Context, *AssignCuratorToSeniorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCuratorToSenior not implemented")
}
func (UnimplementedGroupServiceServer) AssignCuratorToGroup(context.Context, *AssignCuratorToGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignCuratorToGroup not implemented")
}
func (UnimplementedGroupServiceServer) RevokeCuratorFromSenior(context.Context, *RevokeCuratorFromSeniorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCuratorFromSenior not implemented")
}
func (UnimplementedGroupServiceServer) RevokeCuratorFromGroup(context.Context, *RevokeCuratorFromGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCuratorFromGroup not implemented")
}
func (UnimplementedGroupServiceServer) AddCurator(context.Context, *AddCuratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCurator not implemented")
}
func (UnimplementedGroupServiceServer) RevokeCurator(context.Context, *RevokeCuratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCurator not implemented")
}
func (UnimplementedGroupServiceServer) GroupsCurators(context.Context, *GroupsCuratorsRequest) (*GroupsCuratorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupsCurators not implemented")
}
func (UnimplementedGroupServiceServer) AddMember(context.Context, *AddMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedGroupServiceServer) RemoveMember(context.Context, *RemoveMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedGroupServiceServer) MembersGroups(context.Context, *MembersGroupsRequest) (*MembersGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MembersGroups not implemented")
}
func (UnimplementedGroupServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGroupServiceServer) Group(context.Context, *GroupRequest) (*GroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Group not implemented")
}
func (UnimplementedGroupServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupServiceServer) SearchGroup(context.Context, *CreateGroupRequest) (*SearchGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGroup not implemented")
}
func (UnimplementedGroupServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedGroupServiceServer) ListGroups(context.Context, *ListGroupsRequest) (*ListGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedGroupServiceServer) CuratorsGroups(context.Context, *CuratorsGroupsRequest) (*CuratorsGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CuratorsGroups not implemented")
}
func (UnimplementedGroupServiceServer) mustEmbedUnimplementedGroupServiceServer() {}
func (UnimplementedGroupServiceServer) testEmbeddedByValue()                      {}

// UnsafeGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServiceServer will
// result in compilation errors.
type UnsafeGroupServiceServer interface {
	mustEmbedUnimplementedGroupServiceServer()
}

func RegisterGroupServiceServer(s grpc.ServiceRegistrar, srv GroupServiceServer) {
	// If the following call panics, it indicates UnimplementedGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupService_ServiceDesc, srv)
}

func _GroupService_AssignCuratorToSenior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCuratorToSeniorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AssignCuratorToSenior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AssignCuratorToSenior_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AssignCuratorToSenior(ctx, req.(*AssignCuratorToSeniorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AssignCuratorToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignCuratorToGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AssignCuratorToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AssignCuratorToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AssignCuratorToGroup(ctx, req.(*AssignCuratorToGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RevokeCuratorFromSenior_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCuratorFromSeniorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RevokeCuratorFromSenior(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RevokeCuratorFromSenior_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RevokeCuratorFromSenior(ctx, req.(*RevokeCuratorFromSeniorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RevokeCuratorFromGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCuratorFromGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RevokeCuratorFromGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RevokeCuratorFromGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RevokeCuratorFromGroup(ctx, req.(*RevokeCuratorFromGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddCurator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCuratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddCurator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AddCurator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddCurator(ctx, req.(*AddCuratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RevokeCurator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCuratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RevokeCurator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RevokeCurator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RevokeCurator(ctx, req.(*RevokeCuratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GroupsCurators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupsCuratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GroupsCurators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GroupsCurators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GroupsCurators(ctx, req.(*GroupsCuratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).AddMember(ctx, req.(*AddMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RemoveMember(ctx, req.(*RemoveMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_MembersGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembersGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).MembersGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_MembersGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).MembersGroups(ctx, req.(*MembersGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_Group_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).Group(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_Group_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).Group(ctx, req.(*GroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_SearchGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).SearchGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_SearchGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).SearchGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListGroups(ctx, req.(*ListGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CuratorsGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CuratorsGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CuratorsGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CuratorsGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CuratorsGroups(ctx, req.(*CuratorsGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupService_ServiceDesc is the grpc.ServiceDesc for GroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignCuratorToSenior",
			Handler:    _GroupService_AssignCuratorToSenior_Handler,
		},
		{
			MethodName: "AssignCuratorToGroup",
			Handler:    _GroupService_AssignCuratorToGroup_Handler,
		},
		{
			MethodName: "RevokeCuratorFromSenior",
			Handler:    _GroupService_RevokeCuratorFromSenior_Handler,
		},
		{
			MethodName: "RevokeCuratorFromGroup",
			Handler:    _GroupService_RevokeCuratorFromGroup_Handler,
		},
		{
			MethodName: "AddCurator",
			Handler:    _GroupService_AddCurator_Handler,
		},
		{
			MethodName: "RevokeCurator",
			Handler:    _GroupService_RevokeCurator_Handler,
		},
		{
			MethodName: "GroupsCurators",
			Handler:    _GroupService_GroupsCurators_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _GroupService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _GroupService_RemoveMember_Handler,
		},
		{
			MethodName: "MembersGroups",
			Handler:    _GroupService_MembersGroups_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GroupService_ListMembers_Handler,
		},
		{
			MethodName: "Group",
			Handler:    _GroupService_Group_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _GroupService_CreateGroup_Handler,
		},
		{
			MethodName: "SearchGroup",
			Handler:    _GroupService_SearchGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _GroupService_DeleteGroup_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _GroupService_ListGroups_Handler,
		},
		{
			MethodName: "CuratorsGroups",
			Handler:    _GroupService_CuratorsGroups_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/group.proto",
}
