FROM golang:1.26.1-alpine AS builder
RUN apk add --no-cache git
WORKDIR /news
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -o /app .

FROM scratch
COPY --from=builder /app /app
ENTRYPOINT ["/app"]