// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/RBAC.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Verb int32

const (
	Verb_UNDEFINED Verb = 0
	Verb_GET       Verb = 1
	Verb_POST      Verb = 2
	Verb_PUT       Verb = 3
	Verb_PATCH     Verb = 4
	Verb_DELETE    Verb = 5
)

// Enum value maps for Verb.
var (
	Verb_name = map[int32]string{
		0: "UNDEFINED",
		1: "GET",
		2: "POST",
		3: "PUT",
		4: "PATCH",
		5: "DELETE",
	}
	Verb_value = map[string]int32{
		"UNDEFINED": 0,
		"GET":       1,
		"POST":      2,
		"PUT":       3,
		"PATCH":     4,
		"DELETE":    5,
	}
)

func (x Verb) Enum() *Verb {
	p := new(Verb)
	*p = x
	return p
}

func (x Verb) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verb) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_RBAC_proto_enumTypes[0].Descriptor()
}

func (Verb) Type() protoreflect.EnumType {
	return &file_proto_RBAC_proto_enumTypes[0]
}

func (x Verb) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verb.Descriptor instead.
func (Verb) EnumDescriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{0}
}

type HasPermissionQuestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User_UUID     string                 `protobuf:"bytes,1,opt,name=user_UUID,json=userUUID,proto3" json:"user_UUID,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	SubScope      *string                `protobuf:"bytes,3,opt,name=subScope,proto3,oneof" json:"subScope,omitempty"`
	Verb          Verb                   `protobuf:"varint,4,opt,name=verb,proto3,enum=RBAC.Verb" json:"verb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionQuestion) Reset() {
	*x = HasPermissionQuestion{}
	mi := &file_proto_RBAC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionQuestion) ProtoMessage() {}

func (x *HasPermissionQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionQuestion.ProtoReflect.Descriptor instead.
func (*HasPermissionQuestion) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{0}
}

func (x *HasPermissionQuestion) GetUser_UUID() string {
	if x != nil {
		return x.User_UUID
	}
	return ""
}

func (x *HasPermissionQuestion) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *HasPermissionQuestion) GetSubScope() string {
	if x != nil && x.SubScope != nil {
		return *x.SubScope
	}
	return ""
}

func (x *HasPermissionQuestion) GetVerb() Verb {
	if x != nil {
		return x.Verb
	}
	return Verb_UNDEFINED
}

type HasPermissionAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Has           bool                   `protobuf:"varint,1,opt,name=has,proto3" json:"has,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HasPermissionAnswer) Reset() {
	*x = HasPermissionAnswer{}
	mi := &file_proto_RBAC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HasPermissionAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasPermissionAnswer) ProtoMessage() {}

func (x *HasPermissionAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasPermissionAnswer.ProtoReflect.Descriptor instead.
func (*HasPermissionAnswer) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{1}
}

func (x *HasPermissionAnswer) GetHas() bool {
	if x != nil {
		return x.Has
	}
	return false
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRoleRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type Action struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	SubScope      *string                `protobuf:"bytes,2,opt,name=sub_scope,json=subScope,proto3,oneof" json:"sub_scope,omitempty"`
	Verb          Verb                   `protobuf:"varint,3,opt,name=verb,proto3,enum=RBAC.Verb" json:"verb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Action) Reset() {
	*x = Action{}
	mi := &file_proto_RBAC_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Action) ProtoMessage() {}

func (x *Action) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Action.ProtoReflect.Descriptor instead.
func (*Action) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{3}
}

func (x *Action) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Action) GetSubScope() string {
	if x != nil && x.SubScope != nil {
		return *x.SubScope
	}
	return ""
}

func (x *Action) GetVerb() Verb {
	if x != nil {
		return x.Verb
	}
	return Verb_UNDEFINED
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Extended_UUID *string                `protobuf:"bytes,3,opt,name=extended_UUID,json=extendedUUID,proto3,oneof" json:"extended_UUID,omitempty"`
	Priority      int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	Actions       []*Action              `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateRoleRequest) GetExtended_UUID() string {
	if x != nil && x.Extended_UUID != nil {
		return *x.Extended_UUID
	}
	return ""
}

func (x *CreateRoleRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateRoleRequest) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type AssignorsAssigneesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignor_UUID string                 `protobuf:"bytes,1,opt,name=assignor_UUID,json=assignorUUID,proto3" json:"assignor_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignorsAssigneesRequest) Reset() {
	*x = AssignorsAssigneesRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignorsAssigneesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignorsAssigneesRequest) ProtoMessage() {}

func (x *AssignorsAssigneesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignorsAssigneesRequest.ProtoReflect.Descriptor instead.
func (*AssignorsAssigneesRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{5}
}

func (x *AssignorsAssigneesRequest) GetAssignor_UUID() string {
	if x != nil {
		return x.Assignor_UUID
	}
	return ""
}

type AssignorsAssigneesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Assignee_UUIDs []string               `protobuf:"bytes,1,rep,name=assignee_UUIDs,json=assigneeUUIDs,proto3" json:"assignee_UUIDs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssignorsAssigneesResponse) Reset() {
	*x = AssignorsAssigneesResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignorsAssigneesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignorsAssigneesResponse) ProtoMessage() {}

func (x *AssignorsAssigneesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignorsAssigneesResponse.ProtoReflect.Descriptor instead.
func (*AssignorsAssigneesResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{6}
}

func (x *AssignorsAssigneesResponse) GetAssignee_UUIDs() []string {
	if x != nil {
		return x.Assignee_UUIDs
	}
	return nil
}

type RoleAssignorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignee_UUID string                 `protobuf:"bytes,1,opt,name=assignee_UUID,json=assigneeUUID,proto3" json:"assignee_UUID,omitempty"`
	Role_UUID     string                 `protobuf:"bytes,2,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignorRequest) Reset() {
	*x = RoleAssignorRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignorRequest) ProtoMessage() {}

func (x *RoleAssignorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignorRequest.ProtoReflect.Descriptor instead.
func (*RoleAssignorRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{7}
}

func (x *RoleAssignorRequest) GetAssignee_UUID() string {
	if x != nil {
		return x.Assignee_UUID
	}
	return ""
}

func (x *RoleAssignorRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type RoleAssignorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignor_UUID string                 `protobuf:"bytes,1,opt,name=assignor_UUID,json=assignorUUID,proto3" json:"assignor_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssignorResponse) Reset() {
	*x = RoleAssignorResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssignorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssignorResponse) ProtoMessage() {}

func (x *RoleAssignorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssignorResponse.ProtoReflect.Descriptor instead.
func (*RoleAssignorResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{8}
}

func (x *RoleAssignorResponse) GetAssignor_UUID() string {
	if x != nil {
		return x.Assignor_UUID
	}
	return ""
}

type RoleAssigneesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssigneesRequest) Reset() {
	*x = RoleAssigneesRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssigneesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssigneesRequest) ProtoMessage() {}

func (x *RoleAssigneesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssigneesRequest.ProtoReflect.Descriptor instead.
func (*RoleAssigneesRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{9}
}

func (x *RoleAssigneesRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type RoleAssigneesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User_UUIDs    []string               `protobuf:"bytes,1,rep,name=user_UUIDs,json=userUUIDs,proto3" json:"user_UUIDs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleAssigneesResponse) Reset() {
	*x = RoleAssigneesResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleAssigneesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleAssigneesResponse) ProtoMessage() {}

func (x *RoleAssigneesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleAssigneesResponse.ProtoReflect.Descriptor instead.
func (*RoleAssigneesResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{10}
}

func (x *RoleAssigneesResponse) GetUser_UUIDs() []string {
	if x != nil {
		return x.User_UUIDs
	}
	return nil
}

type AssignRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignee_UUID string                 `protobuf:"bytes,1,opt,name=assignee_UUID,json=assigneeUUID,proto3" json:"assignee_UUID,omitempty"`
	Role_UUID     string                 `protobuf:"bytes,2,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{11}
}

func (x *AssignRoleRequest) GetAssignee_UUID() string {
	if x != nil {
		return x.Assignee_UUID
	}
	return ""
}

func (x *AssignRoleRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

func (x *AssignRoleRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type PatchRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Extended_UUID *string                `protobuf:"bytes,4,opt,name=extended_UUID,json=extendedUUID,proto3,oneof" json:"extended_UUID,omitempty"`
	Priority      *int32                 `protobuf:"varint,5,opt,name=priority,proto3,oneof" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRoleRequest) Reset() {
	*x = PatchRoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRoleRequest) ProtoMessage() {}

func (x *PatchRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRoleRequest.ProtoReflect.Descriptor instead.
func (*PatchRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{12}
}

func (x *PatchRoleRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

func (x *PatchRoleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PatchRoleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *PatchRoleRequest) GetExtended_UUID() string {
	if x != nil && x.Extended_UUID != nil {
		return *x.Extended_UUID
	}
	return ""
}

func (x *PatchRoleRequest) GetPriority() int32 {
	if x != nil && x.Priority != nil {
		return *x.Priority
	}
	return 0
}

type RoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleRequest) Reset() {
	*x = RoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRequest) ProtoMessage() {}

func (x *RoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRequest.ProtoReflect.Descriptor instead.
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{13}
}

func (x *RoleRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type RoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Extended_UUID *string                `protobuf:"bytes,4,opt,name=extended_UUID,json=extendedUUID,proto3,oneof" json:"extended_UUID,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleResponse) Reset() {
	*x = RoleResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleResponse) ProtoMessage() {}

func (x *RoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleResponse.ProtoReflect.Descriptor instead.
func (*RoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{14}
}

func (x *RoleResponse) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

func (x *RoleResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleResponse) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RoleResponse) GetExtended_UUID() string {
	if x != nil && x.Extended_UUID != nil {
		return *x.Extended_UUID
	}
	return ""
}

func (x *RoleResponse) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *RoleResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RoleResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *RoleResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{15}
}

func (x *ListRolesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListRolesResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Roles         []*ListRolesResponse_Role `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	Page          int32                     `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                     `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{16}
}

func (x *ListRolesResponse) GetRoles() []*ListRolesResponse_Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ListRolesResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRolesResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListRolesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AddActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action_UUIDs  []string               `protobuf:"bytes,1,rep,name=action_UUIDs,json=actionUUIDs,proto3" json:"action_UUIDs,omitempty"`
	Role_UUID     string                 `protobuf:"bytes,2,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddActionsRequest) Reset() {
	*x = AddActionsRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddActionsRequest) ProtoMessage() {}

func (x *AddActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddActionsRequest.ProtoReflect.Descriptor instead.
func (*AddActionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{17}
}

func (x *AddActionsRequest) GetAction_UUIDs() []string {
	if x != nil {
		return x.Action_UUIDs
	}
	return nil
}

func (x *AddActionsRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type RevokeActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action_UUIDs  []string               `protobuf:"bytes,1,rep,name=action_UUIDs,json=actionUUIDs,proto3" json:"action_UUIDs,omitempty"`
	Role_UUID     string                 `protobuf:"bytes,2,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeActionsRequest) Reset() {
	*x = RevokeActionsRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeActionsRequest) ProtoMessage() {}

func (x *RevokeActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeActionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeActionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeActionsRequest) GetAction_UUIDs() []string {
	if x != nil {
		return x.Action_UUIDs
	}
	return nil
}

func (x *RevokeActionsRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type ListActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{19}
}

func (x *ListActionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        []*Action              `protobuf:"bytes,1,rep,name=action,proto3" json:"action,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{20}
}

func (x *ListActionsResponse) GetAction() []*Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ListActionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListActionsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListActionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ActionsByRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsByRoleRequest) Reset() {
	*x = ActionsByRoleRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsByRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsByRoleRequest) ProtoMessage() {}

func (x *ActionsByRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsByRoleRequest.ProtoReflect.Descriptor instead.
func (*ActionsByRoleRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{21}
}

func (x *ActionsByRoleRequest) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

type ActionsByRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*Action              `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionsByRoleResponse) Reset() {
	*x = ActionsByRoleResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionsByRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionsByRoleResponse) ProtoMessage() {}

func (x *ActionsByRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionsByRoleResponse.ProtoReflect.Descriptor instead.
func (*ActionsByRoleResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{22}
}

func (x *ActionsByRoleResponse) GetActions() []*Action {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action_UUID   string                 `protobuf:"bytes,1,opt,name=action_UUID,json=actionUUID,proto3" json:"action_UUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_proto_RBAC_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{23}
}

func (x *ActionRequest) GetAction_UUID() string {
	if x != nil {
		return x.Action_UUID
	}
	return ""
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        *Action                `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_proto_RBAC_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{24}
}

func (x *ActionResponse) GetAction() *Action {
	if x != nil {
		return x.Action
	}
	return nil
}

type ListRolesResponse_Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role_UUID     string                 `protobuf:"bytes,1,opt,name=role_UUID,json=roleUUID,proto3" json:"role_UUID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Extended_UUID *string                `protobuf:"bytes,4,opt,name=extended_UUID,json=extendedUUID,proto3,oneof" json:"extended_UUID,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse_Role) Reset() {
	*x = ListRolesResponse_Role{}
	mi := &file_proto_RBAC_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse_Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse_Role) ProtoMessage() {}

func (x *ListRolesResponse_Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_RBAC_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse_Role.ProtoReflect.Descriptor instead.
func (*ListRolesResponse_Role) Descriptor() ([]byte, []int) {
	return file_proto_RBAC_proto_rawDescGZIP(), []int{16, 0}
}

func (x *ListRolesResponse_Role) GetRole_UUID() string {
	if x != nil {
		return x.Role_UUID
	}
	return ""
}

func (x *ListRolesResponse_Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListRolesResponse_Role) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ListRolesResponse_Role) GetExtended_UUID() string {
	if x != nil && x.Extended_UUID != nil {
		return *x.Extended_UUID
	}
	return ""
}

func (x *ListRolesResponse_Role) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ListRolesResponse_Role) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ListRolesResponse_Role) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *ListRolesResponse_Role) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_proto_RBAC_proto protoreflect.FileDescriptor

const file_proto_RBAC_proto_rawDesc = "" +
	"\n" +
	"\x10proto/RBAC.proto\x12\x04RBAC\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x98\x01\n" +
	"\x15HasPermissionQuestion\x12\x1b\n" +
	"\tuser_UUID\x18\x01 \x01(\tR\buserUUID\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x1f\n" +
	"\bsubScope\x18\x03 \x01(\tH\x00R\bsubScope\x88\x01\x01\x12\x1e\n" +
	"\x04verb\x18\x04 \x01(\x0e2\n" +
	".RBAC.VerbR\x04verbB\v\n" +
	"\t_subScope\"'\n" +
	"\x13HasPermissionAnswer\x12\x10\n" +
	"\x03has\x18\x01 \x01(\bR\x03has\"0\n" +
	"\x11DeleteRoleRequest\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\"n\n" +
	"\x06Action\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12 \n" +
	"\tsub_scope\x18\x02 \x01(\tH\x00R\bsubScope\x88\x01\x01\x12\x1e\n" +
	"\x04verb\x18\x03 \x01(\x0e2\n" +
	".RBAC.VerbR\x04verbB\f\n" +
	"\n" +
	"_sub_scope\"\xde\x01\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12(\n" +
	"\rextended_UUID\x18\x03 \x01(\tH\x01R\fextendedUUID\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x12&\n" +
	"\aactions\x18\x05 \x03(\v2\f.RBAC.ActionR\aactionsB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_extended_UUID\"@\n" +
	"\x19AssignorsAssigneesRequest\x12#\n" +
	"\rassignor_UUID\x18\x01 \x01(\tR\fassignorUUID\"C\n" +
	"\x1aAssignorsAssigneesResponse\x12%\n" +
	"\x0eassignee_UUIDs\x18\x01 \x03(\tR\rassigneeUUIDs\"W\n" +
	"\x13RoleAssignorRequest\x12#\n" +
	"\rassignee_UUID\x18\x01 \x01(\tR\fassigneeUUID\x12\x1b\n" +
	"\trole_UUID\x18\x02 \x01(\tR\broleUUID\";\n" +
	"\x14RoleAssignorResponse\x12#\n" +
	"\rassignor_UUID\x18\x01 \x01(\tR\fassignorUUID\"3\n" +
	"\x14RoleAssigneesRequest\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\"6\n" +
	"\x15RoleAssigneesResponse\x12\x1d\n" +
	"\n" +
	"user_UUIDs\x18\x01 \x03(\tR\tuserUUIDs\"\xa4\x01\n" +
	"\x11AssignRoleRequest\x12#\n" +
	"\rassignee_UUID\x18\x01 \x01(\tR\fassigneeUUID\x12\x1b\n" +
	"\trole_UUID\x18\x02 \x01(\tR\broleUUID\x12>\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\texpiresAt\x88\x01\x01B\r\n" +
	"\v_expires_at\"\xf2\x01\n" +
	"\x10PatchRoleRequest\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12(\n" +
	"\rextended_UUID\x18\x04 \x01(\tH\x02R\fextendedUUID\x88\x01\x01\x12\x1f\n" +
	"\bpriority\x18\x05 \x01(\x05H\x03R\bpriority\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_extended_UUIDB\v\n" +
	"\t_priority\"*\n" +
	"\vRoleRequest\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\"\x93\x03\n" +
	"\fRoleResponse\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12(\n" +
	"\rextended_UUID\x18\x04 \x01(\tH\x01R\fextendedUUID\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tdeletedAt\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_extended_UUIDB\r\n" +
	"\v_deleted_at\":\n" +
	"\x10ListRolesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x93\x04\n" +
	"\x11ListRolesResponse\x122\n" +
	"\x05roles\x18\x01 \x03(\v2\x1c.RBAC.ListRolesResponse.RoleR\x05roles\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\x1a\x8b\x03\n" +
	"\x04Role\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12(\n" +
	"\rextended_UUID\x18\x04 \x01(\tH\x01R\fextendedUUID\x88\x01\x01\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\n" +
	"deleted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x02R\tdeletedAt\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_descriptionB\x10\n" +
	"\x0e_extended_UUIDB\r\n" +
	"\v_deleted_at\"S\n" +
	"\x11AddActionsRequest\x12!\n" +
	"\faction_UUIDs\x18\x01 \x03(\tR\vactionUUIDs\x12\x1b\n" +
	"\trole_UUID\x18\x02 \x01(\tR\broleUUID\"V\n" +
	"\x14RevokeActionsRequest\x12!\n" +
	"\faction_UUIDs\x18\x01 \x03(\tR\vactionUUIDs\x12\x1b\n" +
	"\trole_UUID\x18\x02 \x01(\tR\broleUUID\"<\n" +
	"\x12ListActionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"y\n" +
	"\x13ListActionsResponse\x12$\n" +
	"\x06action\x18\x01 \x03(\v2\f.RBAC.ActionR\x06action\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"3\n" +
	"\x14ActionsByRoleRequest\x12\x1b\n" +
	"\trole_UUID\x18\x01 \x01(\tR\broleUUID\"?\n" +
	"\x15ActionsByRoleResponse\x12&\n" +
	"\aactions\x18\x01 \x03(\v2\f.RBAC.ActionR\aactions\"0\n" +
	"\rActionRequest\x12\x1f\n" +
	"\vaction_UUID\x18\x01 \x01(\tR\n" +
	"actionUUID\"6\n" +
	"\x0eActionResponse\x12$\n" +
	"\x06action\x18\x01 \x01(\v2\f.RBAC.ActionR\x06action*H\n" +
	"\x04Verb\x12\r\n" +
	"\tUNDEFINED\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\b\n" +
	"\x04POST\x10\x02\x12\a\n" +
	"\x03PUT\x10\x03\x12\t\n" +
	"\x05PATCH\x10\x04\x12\n" +
	"\n" +
	"\x06DELETE\x10\x052\xaa\f\n" +
	"\vRBACService\x12G\n" +
	"\rHasPermission\x12\x1b.RBAC.HasPermissionQuestion\x1a\x19.RBAC.HasPermissionAnswer\x12a\n" +
	"\n" +
	"DeleteRole\x12\x17.RBAC.DeleteRoleRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c*\x1a/v1/RBAC/roles/{role_UUID}\x12Q\n" +
	"\x04Role\x12\x11.RBAC.RoleRequest\x1a\x12.RBAC.RoleResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/RBAC/roles/{role_UUID}\x12b\n" +
	"\tPatchRole\x12\x16.RBAC.PatchRoleRequest\x1a\x16.google.protobuf.Empty\"%\x82\xd3\xe4\x93\x02\x1f:\x01*2\x1a/v1/RBAC/roles/{role_UUID}\x12X\n" +
	"\n" +
	"CreateRole\x12\x17.RBAC.CreateRoleRequest\x1a\x16.google.protobuf.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/RBAC/roles\x12T\n" +
	"\tListRoles\x12\x16.RBAC.ListRolesRequest\x1a\x17.RBAC.ListRolesResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/RBAC/roles\x12\x83\x01\n" +
	"\x12AssignorsAssignees\x12\x1f.RBAC.AssignorsAssigneesRequest\x1a .RBAC.AssignorsAssigneesResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/RBAC/assignors/{assignor_UUID}\x12}\n" +
	"\fRoleAssignor\x12\x19.RBAC.RoleAssignorRequest\x1a\x1a.RBAC.RoleAssignorResponse\"6\x82\xd3\xe4\x93\x020\x12./v1/RBAC/assignees/{assignee_UUID}/{role_UUID}\x12v\n" +
	"\rRoleAssignees\x12\x1a.RBAC.RoleAssigneesRequest\x1a\x1b.RBAC.RoleAssigneesResponse\",\x82\xd3\xe4\x93\x02&\x12$/v1/RBAC/roles/{role_UUID}/assignees\x12{\n" +
	"\n" +
	"AssignRole\x12\x17.RBAC.AssignRoleRequest\x1a\x16.google.protobuf.Empty\"<\x82\xd3\xe4\x93\x026\"4/v1/RBAC/roles/{role_UUID}/assignees/{assignee_UUID}\x12l\n" +
	"\n" +
	"AddActions\x12\x17.RBAC.AddActionsRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/RBAC/roles/{role_UUID}/actions\x12o\n" +
	"\rRevokeActions\x12\x1a.RBAC.RevokeActionsRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$*\"/v1/RBAC/roles/{role_UUID}/actions\x12\\\n" +
	"\vListActions\x12\x18.RBAC.ListActionsRequest\x1a\x19.RBAC.ListActionsResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/RBAC/actions\x12t\n" +
	"\rActionsByRole\x12\x1a.RBAC.ActionsByRoleRequest\x1a\x1b.RBAC.ActionsByRoleResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/RBAC/roles/{role_UUID}/actions\x12[\n" +
	"\x06Action\x12\x13.RBAC.ActionRequest\x1a\x14.RBAC.ActionResponse\"&\x82\xd3\xe4\x93\x02 \x12\x1e/v1/RBAC/actions/{action_UUID}B\x04Z\x02./b\x06proto3"

var (
	file_proto_RBAC_proto_rawDescOnce sync.Once
	file_proto_RBAC_proto_rawDescData []byte
)

func file_proto_RBAC_proto_rawDescGZIP() []byte {
	file_proto_RBAC_proto_rawDescOnce.Do(func() {
		file_proto_RBAC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_RBAC_proto_rawDesc), len(file_proto_RBAC_proto_rawDesc)))
	})
	return file_proto_RBAC_proto_rawDescData
}

var file_proto_RBAC_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_RBAC_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_RBAC_proto_goTypes = []any{
	(Verb)(0),                          // 0: RBAC.Verb
	(*HasPermissionQuestion)(nil),      // 1: RBAC.HasPermissionQuestion
	(*HasPermissionAnswer)(nil),        // 2: RBAC.HasPermissionAnswer
	(*DeleteRoleRequest)(nil),          // 3: RBAC.DeleteRoleRequest
	(*Action)(nil),                     // 4: RBAC.Action
	(*CreateRoleRequest)(nil),          // 5: RBAC.CreateRoleRequest
	(*AssignorsAssigneesRequest)(nil),  // 6: RBAC.AssignorsAssigneesRequest
	(*AssignorsAssigneesResponse)(nil), // 7: RBAC.AssignorsAssigneesResponse
	(*RoleAssignorRequest)(nil),        // 8: RBAC.RoleAssignorRequest
	(*RoleAssignorResponse)(nil),       // 9: RBAC.RoleAssignorResponse
	(*RoleAssigneesRequest)(nil),       // 10: RBAC.RoleAssigneesRequest
	(*RoleAssigneesResponse)(nil),      // 11: RBAC.RoleAssigneesResponse
	(*AssignRoleRequest)(nil),          // 12: RBAC.AssignRoleRequest
	(*PatchRoleRequest)(nil),           // 13: RBAC.PatchRoleRequest
	(*RoleRequest)(nil),                // 14: RBAC.RoleRequest
	(*RoleResponse)(nil),               // 15: RBAC.RoleResponse
	(*ListRolesRequest)(nil),           // 16: RBAC.ListRolesRequest
	(*ListRolesResponse)(nil),          // 17: RBAC.ListRolesResponse
	(*AddActionsRequest)(nil),          // 18: RBAC.AddActionsRequest
	(*RevokeActionsRequest)(nil),       // 19: RBAC.RevokeActionsRequest
	(*ListActionsRequest)(nil),         // 20: RBAC.ListActionsRequest
	(*ListActionsResponse)(nil),        // 21: RBAC.ListActionsResponse
	(*ActionsByRoleRequest)(nil),       // 22: RBAC.ActionsByRoleRequest
	(*ActionsByRoleResponse)(nil),      // 23: RBAC.ActionsByRoleResponse
	(*ActionRequest)(nil),              // 24: RBAC.ActionRequest
	(*ActionResponse)(nil),             // 25: RBAC.ActionResponse
	(*ListRolesResponse_Role)(nil),     // 26: RBAC.ListRolesResponse.Role
	(*timestamppb.Timestamp)(nil),      // 27: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),              // 28: google.protobuf.Empty
}
var file_proto_RBAC_proto_depIdxs = []int32{
	0,  // 0: RBAC.HasPermissionQuestion.verb:type_name -> RBAC.Verb
	0,  // 1: RBAC.Action.verb:type_name -> RBAC.Verb
	4,  // 2: RBAC.CreateRoleRequest.actions:type_name -> RBAC.Action
	27, // 3: RBAC.AssignRoleRequest.expires_at:type_name -> google.protobuf.Timestamp
	27, // 4: RBAC.RoleResponse.created_at:type_name -> google.protobuf.Timestamp
	27, // 5: RBAC.RoleResponse.deleted_at:type_name -> google.protobuf.Timestamp
	27, // 6: RBAC.RoleResponse.updated_at:type_name -> google.protobuf.Timestamp
	26, // 7: RBAC.ListRolesResponse.roles:type_name -> RBAC.ListRolesResponse.Role
	4,  // 8: RBAC.ListActionsResponse.action:type_name -> RBAC.Action
	4,  // 9: RBAC.ActionsByRoleResponse.actions:type_name -> RBAC.Action
	4,  // 10: RBAC.ActionResponse.action:type_name -> RBAC.Action
	27, // 11: RBAC.ListRolesResponse.Role.created_at:type_name -> google.protobuf.Timestamp
	27, // 12: RBAC.ListRolesResponse.Role.deleted_at:type_name -> google.protobuf.Timestamp
	27, // 13: RBAC.ListRolesResponse.Role.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 14: RBAC.RBACService.HasPermission:input_type -> RBAC.HasPermissionQuestion
	3,  // 15: RBAC.RBACService.DeleteRole:input_type -> RBAC.DeleteRoleRequest
	14, // 16: RBAC.RBACService.Role:input_type -> RBAC.RoleRequest
	13, // 17: RBAC.RBACService.PatchRole:input_type -> RBAC.PatchRoleRequest
	5,  // 18: RBAC.RBACService.CreateRole:input_type -> RBAC.CreateRoleRequest
	16, // 19: RBAC.RBACService.ListRoles:input_type -> RBAC.ListRolesRequest
	6,  // 20: RBAC.RBACService.AssignorsAssignees:input_type -> RBAC.AssignorsAssigneesRequest
	8,  // 21: RBAC.RBACService.RoleAssignor:input_type -> RBAC.RoleAssignorRequest
	10, // 22: RBAC.RBACService.RoleAssignees:input_type -> RBAC.RoleAssigneesRequest
	12, // 23: RBAC.RBACService.AssignRole:input_type -> RBAC.AssignRoleRequest
	18, // 24: RBAC.RBACService.AddActions:input_type -> RBAC.AddActionsRequest
	19, // 25: RBAC.RBACService.RevokeActions:input_type -> RBAC.RevokeActionsRequest
	20, // 26: RBAC.RBACService.ListActions:input_type -> RBAC.ListActionsRequest
	22, // 27: RBAC.RBACService.ActionsByRole:input_type -> RBAC.ActionsByRoleRequest
	24, // 28: RBAC.RBACService.Action:input_type -> RBAC.ActionRequest
	2,  // 29: RBAC.RBACService.HasPermission:output_type -> RBAC.HasPermissionAnswer
	28, // 30: RBAC.RBACService.DeleteRole:output_type -> google.protobuf.Empty
	15, // 31: RBAC.RBACService.Role:output_type -> RBAC.RoleResponse
	28, // 32: RBAC.RBACService.PatchRole:output_type -> google.protobuf.Empty
	28, // 33: RBAC.RBACService.CreateRole:output_type -> google.protobuf.Empty
	17, // 34: RBAC.RBACService.ListRoles:output_type -> RBAC.ListRolesResponse
	7,  // 35: RBAC.RBACService.AssignorsAssignees:output_type -> RBAC.AssignorsAssigneesResponse
	9,  // 36: RBAC.RBACService.RoleAssignor:output_type -> RBAC.RoleAssignorResponse
	11, // 37: RBAC.RBACService.RoleAssignees:output_type -> RBAC.RoleAssigneesResponse
	28, // 38: RBAC.RBACService.AssignRole:output_type -> google.protobuf.Empty
	28, // 39: RBAC.RBACService.AddActions:output_type -> google.protobuf.Empty
	28, // 40: RBAC.RBACService.RevokeActions:output_type -> google.protobuf.Empty
	21, // 41: RBAC.RBACService.ListActions:output_type -> RBAC.ListActionsResponse
	23, // 42: RBAC.RBACService.ActionsByRole:output_type -> RBAC.ActionsByRoleResponse
	25, // 43: RBAC.RBACService.Action:output_type -> RBAC.ActionResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_RBAC_proto_init() }
func file_proto_RBAC_proto_init() {
	if File_proto_RBAC_proto != nil {
		return
	}
	file_proto_RBAC_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[14].OneofWrappers = []any{}
	file_proto_RBAC_proto_msgTypes[25].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_RBAC_proto_rawDesc), len(file_proto_RBAC_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_RBAC_proto_goTypes,
		DependencyIndexes: file_proto_RBAC_proto_depIdxs,
		EnumInfos:         file_proto_RBAC_proto_enumTypes,
		MessageInfos:      file_proto_RBAC_proto_msgTypes,
	}.Build()
	File_proto_RBAC_proto = out.File
	file_proto_RBAC_proto_goTypes = nil
	file_proto_RBAC_proto_depIdxs = nil
}
