apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./2-deployment.yaml
  - ./baryte-deployment.yaml
  - ./cashew-deployment.yaml
  - ./cora-deployment.yaml
  - ./revelation-deployment.yaml
  - ./group-deployment.yaml
  - ./rbac-deployment.yaml
  - ./timetable-deployment.yaml
