apiVersion: v1
kind: Secret
metadata:
  name: group-db-secret
  namespace: group-domain
type: Opaque
stringData:
  JWT_SECRET: a-string-secret-at-least-256-bits-long
  DB_USER: ets
  POSTGRES_PASSWORD: super_SECURE-pAsSwOrD2805!!!
  DB_HOST: group-db-0.group-db
  DB_PORT: "5432"
  DB_IDENTITY_NAME: group_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: group-db-init
  namespace: group-domain
data:
  init.sql: |
    CREATE ROLE ets WITH LOGIN SUPERUSER PASSWORD 'super_SECURE-pAsSwOrD2805!!!';

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: group-db
  namespace: group-domain
spec:
  serviceName: group-db
  replicas: 1
  selector:
    matchLabels:
      app: group-db
  template:
    metadata:
      labels:
        app: group-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: group-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: group-db-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts-volume
          configMap:
            name: group-db-init
  volumeClaimTemplates:
    - metadata:
        name: group-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: group-db
  namespace: group-domain
spec:
  clusterIP: None
  selector:
    app: group-db
  ports:
    - port: 5432
