apiVersion: v1
kind: Secret
metadata:
  name: rbac-db-secret
  namespace: rbac-domain
type: Opaque
stringData:
  JWT_SECRET: a-string-secret-at-least-256-bits-long
  DB_USER: ets
  POSTGRES_PASSWORD: super_SECURE-pAsSwOrD2805!!!
  DB_HOST: rbac-db-0.rbac-db
  DB_PORT: "5432"
  DB_IDENTITY_NAME: rbac_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rbac-db-init
  namespace: rbac-domain
data:
  init.sql: |
    CREATE ROLE ets WITH LOGIN SUPERUSER PASSWORD 'super_SECURE-pAsSwOrD2805!!!';

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rbac-db
  namespace: rbac-domain
spec:
  serviceName: rbac-db
  replicas: 1
  selector:
    matchLabels:
      app: rbac-db
  template:
    metadata:
      labels:
        app: rbac-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: rbac-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: rbac-db-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts-volume
          configMap:
            name: rbac-db-init
  volumeClaimTemplates:
    - metadata:
        name: rbac-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: rbac-db
  namespace: rbac-domain
spec:
  clusterIP: None
  selector:
    app: rbac-db
  ports:
    - port: 5432
