apiVersion: v1
kind: Secret
metadata:
  name: timetable-db-secret
  namespace: timetable-domain
type: Opaque
stringData:
  DB_USER: ets
  POSTGRES_PASSWORD: super_SECURE-pAsSwOrD2805!!!
  DB_HOST: timetable-db-0.timetable-db
  DB_PORT: "5432"
  DB_IDENTITY_NAME: timetable_db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timetable-db-init
  namespace: timetable-domain
data:
  init.sql: |
    CREATE ROLE ets WITH LOGIN SUPERUSER PASSWORD 'super_SECURE-pAsSwOrD2805!!!';

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timetable-db
  namespace: timetable-domain
spec:
  serviceName: timetable-db
  replicas: 1
  selector:
    matchLabels:
      app: timetable-db
  template:
    metadata:
      labels:
        app: timetable-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          envFrom:
            - secretRef:
                name: timetable-db-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: timetable-db-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-scripts-volume
          configMap:
            name: timetable-db-init
  volumeClaimTemplates:
    - metadata:
        name: timetable-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: timetable-db
  namespace: timetable-domain
spec:
  clusterIP: None
  selector:
    app: timetable-db
  ports:
    - port: 5432
