// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: proto/timetable.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TimetableService_ListTimetable_FullMethodName            = "/timetable.TimetableService/ListTimetable"
	TimetableService_GetTimetable_FullMethodName             = "/timetable.TimetableService/GetTimetable"
	TimetableService_CreateAbstractLesson_FullMethodName     = "/timetable.TimetableService/CreateAbstractLesson"
	TimetableService_DeleteAbstractLesson_FullMethodName     = "/timetable.TimetableService/DeleteAbstractLesson"
	TimetableService_GetAbstractLesson_FullMethodName        = "/timetable.TimetableService/GetAbstractLesson"
	TimetableService_PatchAbstractLesson_FullMethodName      = "/timetable.TimetableService/PatchAbstractLesson"
	TimetableService_ListAbstractLessons_FullMethodName      = "/timetable.TimetableService/ListAbstractLessons"
	TimetableService_CreateConcreteLesson_FullMethodName     = "/timetable.TimetableService/CreateConcreteLesson"
	TimetableService_DeleteConcreteLesson_FullMethodName     = "/timetable.TimetableService/DeleteConcreteLesson"
	TimetableService_PatchConcreteLesson_FullMethodName      = "/timetable.TimetableService/PatchConcreteLesson"
	TimetableService_GetConcreteLesson_FullMethodName        = "/timetable.TimetableService/GetConcreteLesson"
	TimetableService_GetPeriods_FullMethodName               = "/timetable.TimetableService/GetPeriods"
	TimetableService_PatchPeriods_FullMethodName             = "/timetable.TimetableService/PatchPeriods"
	TimetableService_HomeworkBodyPUTUrl_FullMethodName       = "/timetable.TimetableService/HomeworkBodyPUTUrl"
	TimetableService_HomeworkBodyGETUrl_FullMethodName       = "/timetable.TimetableService/HomeworkBodyGETUrl"
	TimetableService_HomeworkAttachmentPUTUrl_FullMethodName = "/timetable.TimetableService/HomeworkAttachmentPUTUrl"
	TimetableService_HomeworkAttachmentGETUrl_FullMethodName = "/timetable.TimetableService/HomeworkAttachmentGETUrl"
)

// TimetableServiceClient is the client API for TimetableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimetableServiceClient interface {
	ListTimetable(ctx context.Context, in *ListTimetablesRequest, opts ...grpc.CallOption) (*ListTimetableResponse, error)
	GetTimetable(ctx context.Context, in *GetTimetableRequest, opts ...grpc.CallOption) (*GetTimetableResponse, error)
	CreateAbstractLesson(ctx context.Context, in *CreateAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteAbstractLesson(ctx context.Context, in *DeleteAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAbstractLesson(ctx context.Context, in *GetAbstractLessonRequest, opts ...grpc.CallOption) (*GetAbstractLessonResponse, error)
	PatchAbstractLesson(ctx context.Context, in *PatchAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListAbstractLessons(ctx context.Context, in *ListAbstractLessonsRequest, opts ...grpc.CallOption) (*ListAbstractLessonsResponse, error)
	CreateConcreteLesson(ctx context.Context, in *CreateConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteConcreteLesson(ctx context.Context, in *DeleteConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PatchConcreteLesson(ctx context.Context, in *PatchConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetConcreteLesson(ctx context.Context, in *GetConcreteLessonRequest, opts ...grpc.CallOption) (*GetConcreteLessonResponse, error)
	GetPeriods(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodsResponse, error)
	PatchPeriods(ctx context.Context, in *PatchPeriodsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HomeworkBodyPUTUrl(ctx context.Context, in *HomeworkBodyPUTUrlRequest, opts ...grpc.CallOption) (*HomeworkBodyPUTUrlResponse, error)
	HomeworkBodyGETUrl(ctx context.Context, in *HomeworkBodyGETUrlRequest, opts ...grpc.CallOption) (*HomeworkBodyGETUrlResponse, error)
	HomeworkAttachmentPUTUrl(ctx context.Context, in *HomeworkAttachmentPUTUrlRequest, opts ...grpc.CallOption) (*HomeworkAttachmentPUTUrlResponse, error)
	HomeworkAttachmentGETUrl(ctx context.Context, in *HomeworkAttachmentGETUrlsRequest, opts ...grpc.CallOption) (*HomeworkAttachmentGETUrlsResponse, error)
}

type timetableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTimetableServiceClient(cc grpc.ClientConnInterface) TimetableServiceClient {
	return &timetableServiceClient{cc}
}

func (c *timetableServiceClient) ListTimetable(ctx context.Context, in *ListTimetablesRequest, opts ...grpc.CallOption) (*ListTimetableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTimetableResponse)
	err := c.cc.Invoke(ctx, TimetableService_ListTimetable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) GetTimetable(ctx context.Context, in *GetTimetableRequest, opts ...grpc.CallOption) (*GetTimetableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimetableResponse)
	err := c.cc.Invoke(ctx, TimetableService_GetTimetable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) CreateAbstractLesson(ctx context.Context, in *CreateAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_CreateAbstractLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) DeleteAbstractLesson(ctx context.Context, in *DeleteAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_DeleteAbstractLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) GetAbstractLesson(ctx context.Context, in *GetAbstractLessonRequest, opts ...grpc.CallOption) (*GetAbstractLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAbstractLessonResponse)
	err := c.cc.Invoke(ctx, TimetableService_GetAbstractLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) PatchAbstractLesson(ctx context.Context, in *PatchAbstractLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_PatchAbstractLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) ListAbstractLessons(ctx context.Context, in *ListAbstractLessonsRequest, opts ...grpc.CallOption) (*ListAbstractLessonsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAbstractLessonsResponse)
	err := c.cc.Invoke(ctx, TimetableService_ListAbstractLessons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) CreateConcreteLesson(ctx context.Context, in *CreateConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_CreateConcreteLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) DeleteConcreteLesson(ctx context.Context, in *DeleteConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_DeleteConcreteLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) PatchConcreteLesson(ctx context.Context, in *PatchConcreteLessonRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_PatchConcreteLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) GetConcreteLesson(ctx context.Context, in *GetConcreteLessonRequest, opts ...grpc.CallOption) (*GetConcreteLessonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConcreteLessonResponse)
	err := c.cc.Invoke(ctx, TimetableService_GetConcreteLesson_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) GetPeriods(ctx context.Context, in *GetPeriodRequest, opts ...grpc.CallOption) (*GetPeriodsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPeriodsResponse)
	err := c.cc.Invoke(ctx, TimetableService_GetPeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) PatchPeriods(ctx context.Context, in *PatchPeriodsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TimetableService_PatchPeriods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) HomeworkBodyPUTUrl(ctx context.Context, in *HomeworkBodyPUTUrlRequest, opts ...grpc.CallOption) (*HomeworkBodyPUTUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkBodyPUTUrlResponse)
	err := c.cc.Invoke(ctx, TimetableService_HomeworkBodyPUTUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) HomeworkBodyGETUrl(ctx context.Context, in *HomeworkBodyGETUrlRequest, opts ...grpc.CallOption) (*HomeworkBodyGETUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkBodyGETUrlResponse)
	err := c.cc.Invoke(ctx, TimetableService_HomeworkBodyGETUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) HomeworkAttachmentPUTUrl(ctx context.Context, in *HomeworkAttachmentPUTUrlRequest, opts ...grpc.CallOption) (*HomeworkAttachmentPUTUrlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkAttachmentPUTUrlResponse)
	err := c.cc.Invoke(ctx, TimetableService_HomeworkAttachmentPUTUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *timetableServiceClient) HomeworkAttachmentGETUrl(ctx context.Context, in *HomeworkAttachmentGETUrlsRequest, opts ...grpc.CallOption) (*HomeworkAttachmentGETUrlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HomeworkAttachmentGETUrlsResponse)
	err := c.cc.Invoke(ctx, TimetableService_HomeworkAttachmentGETUrl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TimetableServiceServer is the server API for TimetableService service.
// All implementations must embed UnimplementedTimetableServiceServer
// for forward compatibility.
type TimetableServiceServer interface {
	ListTimetable(context.Context, *ListTimetablesRequest) (*ListTimetableResponse, error)
	GetTimetable(context.Context, *GetTimetableRequest) (*GetTimetableResponse, error)
	CreateAbstractLesson(context.Context, *CreateAbstractLessonRequest) (*emptypb.Empty, error)
	DeleteAbstractLesson(context.Context, *DeleteAbstractLessonRequest) (*emptypb.Empty, error)
	GetAbstractLesson(context.Context, *GetAbstractLessonRequest) (*GetAbstractLessonResponse, error)
	PatchAbstractLesson(context.Context, *PatchAbstractLessonRequest) (*emptypb.Empty, error)
	ListAbstractLessons(context.Context, *ListAbstractLessonsRequest) (*ListAbstractLessonsResponse, error)
	CreateConcreteLesson(context.Context, *CreateConcreteLessonRequest) (*emptypb.Empty, error)
	DeleteConcreteLesson(context.Context, *DeleteConcreteLessonRequest) (*emptypb.Empty, error)
	PatchConcreteLesson(context.Context, *PatchConcreteLessonRequest) (*emptypb.Empty, error)
	GetConcreteLesson(context.Context, *GetConcreteLessonRequest) (*GetConcreteLessonResponse, error)
	GetPeriods(context.Context, *GetPeriodRequest) (*GetPeriodsResponse, error)
	PatchPeriods(context.Context, *PatchPeriodsRequest) (*emptypb.Empty, error)
	HomeworkBodyPUTUrl(context.Context, *HomeworkBodyPUTUrlRequest) (*HomeworkBodyPUTUrlResponse, error)
	HomeworkBodyGETUrl(context.Context, *HomeworkBodyGETUrlRequest) (*HomeworkBodyGETUrlResponse, error)
	HomeworkAttachmentPUTUrl(context.Context, *HomeworkAttachmentPUTUrlRequest) (*HomeworkAttachmentPUTUrlResponse, error)
	HomeworkAttachmentGETUrl(context.Context, *HomeworkAttachmentGETUrlsRequest) (*HomeworkAttachmentGETUrlsResponse, error)
	mustEmbedUnimplementedTimetableServiceServer()
}

// UnimplementedTimetableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTimetableServiceServer struct{}

func (UnimplementedTimetableServiceServer) ListTimetable(context.Context, *ListTimetablesRequest) (*ListTimetableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTimetable not implemented")
}
func (UnimplementedTimetableServiceServer) GetTimetable(context.Context, *GetTimetableRequest) (*GetTimetableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimetable not implemented")
}
func (UnimplementedTimetableServiceServer) CreateAbstractLesson(context.Context, *CreateAbstractLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAbstractLesson not implemented")
}
func (UnimplementedTimetableServiceServer) DeleteAbstractLesson(context.Context, *DeleteAbstractLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAbstractLesson not implemented")
}
func (UnimplementedTimetableServiceServer) GetAbstractLesson(context.Context, *GetAbstractLessonRequest) (*GetAbstractLessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAbstractLesson not implemented")
}
func (UnimplementedTimetableServiceServer) PatchAbstractLesson(context.Context, *PatchAbstractLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchAbstractLesson not implemented")
}
func (UnimplementedTimetableServiceServer) ListAbstractLessons(context.Context, *ListAbstractLessonsRequest) (*ListAbstractLessonsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAbstractLessons not implemented")
}
func (UnimplementedTimetableServiceServer) CreateConcreteLesson(context.Context, *CreateConcreteLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateConcreteLesson not implemented")
}
func (UnimplementedTimetableServiceServer) DeleteConcreteLesson(context.Context, *DeleteConcreteLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConcreteLesson not implemented")
}
func (UnimplementedTimetableServiceServer) PatchConcreteLesson(context.Context, *PatchConcreteLessonRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchConcreteLesson not implemented")
}
func (UnimplementedTimetableServiceServer) GetConcreteLesson(context.Context, *GetConcreteLessonRequest) (*GetConcreteLessonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConcreteLesson not implemented")
}
func (UnimplementedTimetableServiceServer) GetPeriods(context.Context, *GetPeriodRequest) (*GetPeriodsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPeriods not implemented")
}
func (UnimplementedTimetableServiceServer) PatchPeriods(context.Context, *PatchPeriodsRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PatchPeriods not implemented")
}
func (UnimplementedTimetableServiceServer) HomeworkBodyPUTUrl(context.Context, *HomeworkBodyPUTUrlRequest) (*HomeworkBodyPUTUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeworkBodyPUTUrl not implemented")
}
func (UnimplementedTimetableServiceServer) HomeworkBodyGETUrl(context.Context, *HomeworkBodyGETUrlRequest) (*HomeworkBodyGETUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeworkBodyGETUrl not implemented")
}
func (UnimplementedTimetableServiceServer) HomeworkAttachmentPUTUrl(context.Context, *HomeworkAttachmentPUTUrlRequest) (*HomeworkAttachmentPUTUrlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeworkAttachmentPUTUrl not implemented")
}
func (UnimplementedTimetableServiceServer) HomeworkAttachmentGETUrl(context.Context, *HomeworkAttachmentGETUrlsRequest) (*HomeworkAttachmentGETUrlsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HomeworkAttachmentGETUrl not implemented")
}
func (UnimplementedTimetableServiceServer) mustEmbedUnimplementedTimetableServiceServer() {}
func (UnimplementedTimetableServiceServer) testEmbeddedByValue()                          {}

// UnsafeTimetableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TimetableServiceServer will
// result in compilation errors.
type UnsafeTimetableServiceServer interface {
	mustEmbedUnimplementedTimetableServiceServer()
}

func RegisterTimetableServiceServer(s grpc.ServiceRegistrar, srv TimetableServiceServer) {
	// If the following call panics, it indicates UnimplementedTimetableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TimetableService_ServiceDesc, srv)
}

func _TimetableService_ListTimetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTimetablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).ListTimetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_ListTimetable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).ListTimetable(ctx, req.(*ListTimetablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_GetTimetable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimetableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).GetTimetable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_GetTimetable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).GetTimetable(ctx, req.(*GetTimetableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_CreateAbstractLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAbstractLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).CreateAbstractLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_CreateAbstractLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).CreateAbstractLesson(ctx, req.(*CreateAbstractLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_DeleteAbstractLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAbstractLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).DeleteAbstractLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_DeleteAbstractLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).DeleteAbstractLesson(ctx, req.(*DeleteAbstractLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_GetAbstractLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbstractLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).GetAbstractLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_GetAbstractLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).GetAbstractLesson(ctx, req.(*GetAbstractLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_PatchAbstractLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchAbstractLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).PatchAbstractLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_PatchAbstractLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).PatchAbstractLesson(ctx, req.(*PatchAbstractLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_ListAbstractLessons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAbstractLessonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).ListAbstractLessons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_ListAbstractLessons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).ListAbstractLessons(ctx, req.(*ListAbstractLessonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_CreateConcreteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConcreteLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).CreateConcreteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_CreateConcreteLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).CreateConcreteLesson(ctx, req.(*CreateConcreteLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_DeleteConcreteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConcreteLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).DeleteConcreteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_DeleteConcreteLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).DeleteConcreteLesson(ctx, req.(*DeleteConcreteLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_PatchConcreteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchConcreteLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).PatchConcreteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_PatchConcreteLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).PatchConcreteLesson(ctx, req.(*PatchConcreteLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_GetConcreteLesson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConcreteLessonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).GetConcreteLesson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_GetConcreteLesson_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).GetConcreteLesson(ctx, req.(*GetConcreteLessonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_GetPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeriodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).GetPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_GetPeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).GetPeriods(ctx, req.(*GetPeriodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_PatchPeriods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchPeriodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).PatchPeriods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_PatchPeriods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).PatchPeriods(ctx, req.(*PatchPeriodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_HomeworkBodyPUTUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeworkBodyPUTUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).HomeworkBodyPUTUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_HomeworkBodyPUTUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).HomeworkBodyPUTUrl(ctx, req.(*HomeworkBodyPUTUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_HomeworkBodyGETUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeworkBodyGETUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).HomeworkBodyGETUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_HomeworkBodyGETUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).HomeworkBodyGETUrl(ctx, req.(*HomeworkBodyGETUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_HomeworkAttachmentPUTUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeworkAttachmentPUTUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).HomeworkAttachmentPUTUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_HomeworkAttachmentPUTUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).HomeworkAttachmentPUTUrl(ctx, req.(*HomeworkAttachmentPUTUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TimetableService_HomeworkAttachmentGETUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeworkAttachmentGETUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimetableServiceServer).HomeworkAttachmentGETUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TimetableService_HomeworkAttachmentGETUrl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimetableServiceServer).HomeworkAttachmentGETUrl(ctx, req.(*HomeworkAttachmentGETUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TimetableService_ServiceDesc is the grpc.ServiceDesc for TimetableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimetableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "timetable.TimetableService",
	HandlerType: (*TimetableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTimetable",
			Handler:    _TimetableService_ListTimetable_Handler,
		},
		{
			MethodName: "GetTimetable",
			Handler:    _TimetableService_GetTimetable_Handler,
		},
		{
			MethodName: "CreateAbstractLesson",
			Handler:    _TimetableService_CreateAbstractLesson_Handler,
		},
		{
			MethodName: "DeleteAbstractLesson",
			Handler:    _TimetableService_DeleteAbstractLesson_Handler,
		},
		{
			MethodName: "GetAbstractLesson",
			Handler:    _TimetableService_GetAbstractLesson_Handler,
		},
		{
			MethodName: "PatchAbstractLesson",
			Handler:    _TimetableService_PatchAbstractLesson_Handler,
		},
		{
			MethodName: "ListAbstractLessons",
			Handler:    _TimetableService_ListAbstractLessons_Handler,
		},
		{
			MethodName: "CreateConcreteLesson",
			Handler:    _TimetableService_CreateConcreteLesson_Handler,
		},
		{
			MethodName: "DeleteConcreteLesson",
			Handler:    _TimetableService_DeleteConcreteLesson_Handler,
		},
		{
			MethodName: "PatchConcreteLesson",
			Handler:    _TimetableService_PatchConcreteLesson_Handler,
		},
		{
			MethodName: "GetConcreteLesson",
			Handler:    _TimetableService_GetConcreteLesson_Handler,
		},
		{
			MethodName: "GetPeriods",
			Handler:    _TimetableService_GetPeriods_Handler,
		},
		{
			MethodName: "PatchPeriods",
			Handler:    _TimetableService_PatchPeriods_Handler,
		},
		{
			MethodName: "HomeworkBodyPUTUrl",
			Handler:    _TimetableService_HomeworkBodyPUTUrl_Handler,
		},
		{
			MethodName: "HomeworkBodyGETUrl",
			Handler:    _TimetableService_HomeworkBodyGETUrl_Handler,
		},
		{
			MethodName: "HomeworkAttachmentPUTUrl",
			Handler:    _TimetableService_HomeworkAttachmentPUTUrl_Handler,
		},
		{
			MethodName: "HomeworkAttachmentGETUrl",
			Handler:    _TimetableService_HomeworkAttachmentGETUrl_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/timetable.proto",
}
