// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/timetable.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Day int32

const (
	Day_UNSPECIFIED Day = 0
	Day_MONDAY      Day = 1
	Day_TUESDAY     Day = 2
	Day_WEDNESDAY   Day = 3
	Day_THURSDAY    Day = 4
	Day_FRIDAY      Day = 5
	Day_SATURDAY    Day = 6
	Day_SUNDAY      Day = 7
)

// Enum value maps for Day.
var (
	Day_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
	}
	Day_value = map[string]int32{
		"UNSPECIFIED": 0,
		"MONDAY":      1,
		"TUESDAY":     2,
		"WEDNESDAY":   3,
		"THURSDAY":    4,
		"FRIDAY":      5,
		"SATURDAY":    6,
		"SUNDAY":      7,
	}
)

func (x Day) Enum() *Day {
	p := new(Day)
	*p = x
	return p
}

func (x Day) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Day) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_timetable_proto_enumTypes[0].Descriptor()
}

func (Day) Type() protoreflect.EnumType {
	return &file_proto_timetable_proto_enumTypes[0]
}

func (x Day) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Day.Descriptor instead.
func (Day) EnumDescriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{0}
}

type ListTimetablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimetablesRequest) Reset() {
	*x = ListTimetablesRequest{}
	mi := &file_proto_timetable_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimetablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimetablesRequest) ProtoMessage() {}

func (x *ListTimetablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimetablesRequest.ProtoReflect.Descriptor instead.
func (*ListTimetablesRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{0}
}

func (x *ListTimetablesRequest) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *ListTimetablesRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type GetTimetableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Day           Day                    `protobuf:"varint,3,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimetableRequest) Reset() {
	*x = GetTimetableRequest{}
	mi := &file_proto_timetable_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimetableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableRequest) ProtoMessage() {}

func (x *GetTimetableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableRequest.ProtoReflect.Descriptor instead.
func (*GetTimetableRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{1}
}

func (x *GetTimetableRequest) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *GetTimetableRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *GetTimetableRequest) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

type GetTimetableResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Timetable     *ConcreteLessonShortEntry `protobuf:"bytes,1,opt,name=Timetable,proto3" json:"Timetable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimetableResponse) Reset() {
	*x = GetTimetableResponse{}
	mi := &file_proto_timetable_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimetableResponse) ProtoMessage() {}

func (x *GetTimetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimetableResponse.ProtoReflect.Descriptor instead.
func (*GetTimetableResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimetableResponse) GetTimetable() *ConcreteLessonShortEntry {
	if x != nil {
		return x.Timetable
	}
	return nil
}

type AbstractLesson struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbstractLesson) Reset() {
	*x = AbstractLesson{}
	mi := &file_proto_timetable_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbstractLesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbstractLesson) ProtoMessage() {}

func (x *AbstractLesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbstractLesson.ProtoReflect.Descriptor instead.
func (*AbstractLesson) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{3}
}

func (x *AbstractLesson) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *AbstractLesson) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ConcreteLesson struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber                 uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	Year                       uint32                 `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	LessonInfo                 *AbstractLesson        `protobuf:"bytes,3,opt,name=lesson_info,json=lessonInfo,proto3" json:"lesson_info,omitempty"`
	TeacherUuid                string                 `protobuf:"bytes,4,opt,name=teacher_uuid,json=teacherUuid,proto3" json:"teacher_uuid,omitempty"`
	HomeworkTextGetUrl         *string                `protobuf:"bytes,5,opt,name=homework_text_get_url,json=homeworkTextGetUrl,proto3,oneof" json:"homework_text_get_url,omitempty"`
	HomeworkAttachmentsGetUrls []string               `protobuf:"bytes,6,rep,name=homework_attachments_get_urls,json=homeworkAttachmentsGetUrls,proto3" json:"homework_attachments_get_urls,omitempty"`
	LessonUuid                 string                 `protobuf:"bytes,7,opt,name=lesson_uuid,json=lessonUuid,proto3" json:"lesson_uuid,omitempty"`
	Marks                      []string               `protobuf:"bytes,8,rep,name=marks,proto3" json:"marks,omitempty"` //5- итд
	Period                     uint32                 `protobuf:"varint,9,opt,name=period,proto3" json:"period,omitempty"`
	Day                        Day                    `protobuf:"varint,10,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	Building                   *string                `protobuf:"bytes,11,opt,name=building,proto3,oneof" json:"building,omitempty"`
	Auditorium                 *string                `protobuf:"bytes,12,opt,name=auditorium,proto3,oneof" json:"auditorium,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ConcreteLesson) Reset() {
	*x = ConcreteLesson{}
	mi := &file_proto_timetable_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcreteLesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcreteLesson) ProtoMessage() {}

func (x *ConcreteLesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcreteLesson.ProtoReflect.Descriptor instead.
func (*ConcreteLesson) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{4}
}

func (x *ConcreteLesson) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *ConcreteLesson) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ConcreteLesson) GetLessonInfo() *AbstractLesson {
	if x != nil {
		return x.LessonInfo
	}
	return nil
}

func (x *ConcreteLesson) GetTeacherUuid() string {
	if x != nil {
		return x.TeacherUuid
	}
	return ""
}

func (x *ConcreteLesson) GetHomeworkTextGetUrl() string {
	if x != nil && x.HomeworkTextGetUrl != nil {
		return *x.HomeworkTextGetUrl
	}
	return ""
}

func (x *ConcreteLesson) GetHomeworkAttachmentsGetUrls() []string {
	if x != nil {
		return x.HomeworkAttachmentsGetUrls
	}
	return nil
}

func (x *ConcreteLesson) GetLessonUuid() string {
	if x != nil {
		return x.LessonUuid
	}
	return ""
}

func (x *ConcreteLesson) GetMarks() []string {
	if x != nil {
		return x.Marks
	}
	return nil
}

func (x *ConcreteLesson) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *ConcreteLesson) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

func (x *ConcreteLesson) GetBuilding() string {
	if x != nil && x.Building != nil {
		return *x.Building
	}
	return ""
}

func (x *ConcreteLesson) GetAuditorium() string {
	if x != nil && x.Auditorium != nil {
		return *x.Auditorium
	}
	return ""
}

type ShortConcreteLesson struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber     uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	Year           uint32                 `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Period         uint32                 `protobuf:"varint,3,opt,name=period,proto3" json:"period,omitempty"`
	AbstractLesson *AbstractLesson        `protobuf:"bytes,4,opt,name=abstract_lesson,json=abstractLesson,proto3" json:"abstract_lesson,omitempty"`
	IsHomeworkDue  bool                   `protobuf:"varint,5,opt,name=is_homework_due,json=isHomeworkDue,proto3" json:"is_homework_due,omitempty"`
	Day            Day                    `protobuf:"varint,6,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	Building       *string                `protobuf:"bytes,7,opt,name=building,proto3,oneof" json:"building,omitempty"`
	Auditorium     *string                `protobuf:"bytes,8,opt,name=auditorium,proto3,oneof" json:"auditorium,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShortConcreteLesson) Reset() {
	*x = ShortConcreteLesson{}
	mi := &file_proto_timetable_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortConcreteLesson) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortConcreteLesson) ProtoMessage() {}

func (x *ShortConcreteLesson) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortConcreteLesson.ProtoReflect.Descriptor instead.
func (*ShortConcreteLesson) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{5}
}

func (x *ShortConcreteLesson) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *ShortConcreteLesson) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *ShortConcreteLesson) GetPeriod() uint32 {
	if x != nil {
		return x.Period
	}
	return 0
}

func (x *ShortConcreteLesson) GetAbstractLesson() *AbstractLesson {
	if x != nil {
		return x.AbstractLesson
	}
	return nil
}

func (x *ShortConcreteLesson) GetIsHomeworkDue() bool {
	if x != nil {
		return x.IsHomeworkDue
	}
	return false
}

func (x *ShortConcreteLesson) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

func (x *ShortConcreteLesson) GetBuilding() string {
	if x != nil && x.Building != nil {
		return *x.Building
	}
	return ""
}

func (x *ShortConcreteLesson) GetAuditorium() string {
	if x != nil && x.Auditorium != nil {
		return *x.Auditorium
	}
	return ""
}

type ConcreteLessonShortEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           Day                    `protobuf:"varint,1,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	Lessons       []*ShortConcreteLesson `protobuf:"bytes,2,rep,name=lessons,proto3" json:"lessons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcreteLessonShortEntry) Reset() {
	*x = ConcreteLessonShortEntry{}
	mi := &file_proto_timetable_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcreteLessonShortEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcreteLessonShortEntry) ProtoMessage() {}

func (x *ConcreteLessonShortEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcreteLessonShortEntry.ProtoReflect.Descriptor instead.
func (*ConcreteLessonShortEntry) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{6}
}

func (x *ConcreteLessonShortEntry) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

func (x *ConcreteLessonShortEntry) GetLessons() []*ShortConcreteLesson {
	if x != nil {
		return x.Lessons
	}
	return nil
}

type ListTimetableResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Timetable     []*ConcreteLessonShortEntry `protobuf:"bytes,1,rep,name=Timetable,proto3" json:"Timetable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTimetableResponse) Reset() {
	*x = ListTimetableResponse{}
	mi := &file_proto_timetable_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTimetableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimetableResponse) ProtoMessage() {}

func (x *ListTimetableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimetableResponse.ProtoReflect.Descriptor instead.
func (*ListTimetableResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{7}
}

func (x *ListTimetableResponse) GetTimetable() []*ConcreteLessonShortEntry {
	if x != nil {
		return x.Timetable
	}
	return nil
}

type CreateAbstractLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAbstractLessonRequest) Reset() {
	*x = CreateAbstractLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAbstractLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAbstractLessonRequest) ProtoMessage() {}

func (x *CreateAbstractLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAbstractLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateAbstractLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAbstractLessonRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Period struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	Day           Day                    `protobuf:"varint,4,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	Year          uint32                 `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	WeekNumber    uint32                 `protobuf:"varint,6,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	PeriodUuid    string                 `protobuf:"bytes,7,opt,name=period_uuid,json=periodUuid,proto3" json:"period_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Period) Reset() {
	*x = Period{}
	mi := &file_proto_timetable_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Period) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Period) ProtoMessage() {}

func (x *Period) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Period.ProtoReflect.Descriptor instead.
func (*Period) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{9}
}

func (x *Period) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Period) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Period) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *Period) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

func (x *Period) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Period) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *Period) GetPeriodUuid() string {
	if x != nil {
		return x.PeriodUuid
	}
	return ""
}

type GetPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeekNumber    uint32                 `protobuf:"varint,1,opt,name=week_number,json=weekNumber,proto3" json:"week_number,omitempty"`
	Day           Day                    `protobuf:"varint,2,opt,name=day,proto3,enum=timetable.Day" json:"day,omitempty"`
	Year          uint32                 `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodRequest) Reset() {
	*x = GetPeriodRequest{}
	mi := &file_proto_timetable_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodRequest) ProtoMessage() {}

func (x *GetPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodRequest.ProtoReflect.Descriptor instead.
func (*GetPeriodRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{10}
}

func (x *GetPeriodRequest) GetWeekNumber() uint32 {
	if x != nil {
		return x.WeekNumber
	}
	return 0
}

func (x *GetPeriodRequest) GetDay() Day {
	if x != nil {
		return x.Day
	}
	return Day_UNSPECIFIED
}

func (x *GetPeriodRequest) GetYear() uint32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type GetPeriodsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []*Period              `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeriodsResponse) Reset() {
	*x = GetPeriodsResponse{}
	mi := &file_proto_timetable_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeriodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeriodsResponse) ProtoMessage() {}

func (x *GetPeriodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeriodsResponse.ProtoReflect.Descriptor instead.
func (*GetPeriodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{11}
}

func (x *GetPeriodsResponse) GetPeriods() []*Period {
	if x != nil {
		return x.Periods
	}
	return nil
}

type PatchPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PeriodUuid    string                 `protobuf:"bytes,7,opt,name=period_uuid,json=periodUuid,proto3" json:"period_uuid,omitempty"`
	Number        *uint32                `protobuf:"varint,1,opt,name=number,proto3,oneof" json:"number,omitempty"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start,proto3,oneof" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end,proto3,oneof" json:"end,omitempty"`
	Day           *Day                   `protobuf:"varint,4,opt,name=day,proto3,enum=timetable.Day,oneof" json:"day,omitempty"`
	Year          *uint32                `protobuf:"varint,5,opt,name=year,proto3,oneof" json:"year,omitempty"`
	WeekNumber    *uint32                `protobuf:"varint,6,opt,name=week_number,json=weekNumber,proto3,oneof" json:"week_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchPeriodRequest) Reset() {
	*x = PatchPeriodRequest{}
	mi := &file_proto_timetable_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPeriodRequest) ProtoMessage() {}

func (x *PatchPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPeriodRequest.ProtoReflect.Descriptor instead.
func (*PatchPeriodRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{12}
}

func (x *PatchPeriodRequest) GetPeriodUuid() string {
	if x != nil {
		return x.PeriodUuid
	}
	return ""
}

func (x *PatchPeriodRequest) GetNumber() uint32 {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return 0
}

func (x *PatchPeriodRequest) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *PatchPeriodRequest) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *PatchPeriodRequest) GetDay() Day {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return Day_UNSPECIFIED
}

func (x *PatchPeriodRequest) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *PatchPeriodRequest) GetWeekNumber() uint32 {
	if x != nil && x.WeekNumber != nil {
		return *x.WeekNumber
	}
	return 0
}

type DeleteAbstractLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonUuid    string                 `protobuf:"bytes,1,opt,name=lesson_uuid,json=lessonUuid,proto3" json:"lesson_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAbstractLessonRequest) Reset() {
	*x = DeleteAbstractLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAbstractLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAbstractLessonRequest) ProtoMessage() {}

func (x *DeleteAbstractLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAbstractLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteAbstractLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteAbstractLessonRequest) GetLessonUuid() string {
	if x != nil {
		return x.LessonUuid
	}
	return ""
}

type GetAbstractLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonUuid    string                 `protobuf:"bytes,1,opt,name=lesson_uuid,json=lessonUuid,proto3" json:"lesson_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbstractLessonRequest) Reset() {
	*x = GetAbstractLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbstractLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbstractLessonRequest) ProtoMessage() {}

func (x *GetAbstractLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbstractLessonRequest.ProtoReflect.Descriptor instead.
func (*GetAbstractLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{14}
}

func (x *GetAbstractLessonRequest) GetLessonUuid() string {
	if x != nil {
		return x.LessonUuid
	}
	return ""
}

type GetAbstractLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *AbstractLesson        `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbstractLessonResponse) Reset() {
	*x = GetAbstractLessonResponse{}
	mi := &file_proto_timetable_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbstractLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbstractLessonResponse) ProtoMessage() {}

func (x *GetAbstractLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbstractLessonResponse.ProtoReflect.Descriptor instead.
func (*GetAbstractLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{15}
}

func (x *GetAbstractLessonResponse) GetLesson() *AbstractLesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type PatchAbstractLessonRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LessonUuid    string                 `protobuf:"bytes,1,opt,name=lesson_uuid,json=lessonUuid,proto3" json:"lesson_uuid,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"` //и такое бывает
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchAbstractLessonRequest) Reset() {
	*x = PatchAbstractLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchAbstractLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchAbstractLessonRequest) ProtoMessage() {}

func (x *PatchAbstractLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchAbstractLessonRequest.ProtoReflect.Descriptor instead.
func (*PatchAbstractLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{16}
}

func (x *PatchAbstractLessonRequest) GetLessonUuid() string {
	if x != nil {
		return x.LessonUuid
	}
	return ""
}

func (x *PatchAbstractLessonRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type ListAbstractLessonsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Page          uint64                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAbstractLessonsRequest) Reset() {
	*x = ListAbstractLessonsRequest{}
	mi := &file_proto_timetable_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbstractLessonsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbstractLessonsRequest) ProtoMessage() {}

func (x *ListAbstractLessonsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbstractLessonsRequest.ProtoReflect.Descriptor instead.
func (*ListAbstractLessonsRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{17}
}

func (x *ListAbstractLessonsRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListAbstractLessonsRequest) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListAbstractLessonsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Size            uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Page            uint64                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Total           uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	AbstractLessons []*AbstractLesson      `protobuf:"bytes,4,rep,name=abstract_lessons,json=abstractLessons,proto3" json:"abstract_lessons,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAbstractLessonsResponse) Reset() {
	*x = ListAbstractLessonsResponse{}
	mi := &file_proto_timetable_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbstractLessonsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbstractLessonsResponse) ProtoMessage() {}

func (x *ListAbstractLessonsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbstractLessonsResponse.ProtoReflect.Descriptor instead.
func (*ListAbstractLessonsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{18}
}

func (x *ListAbstractLessonsResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListAbstractLessonsResponse) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAbstractLessonsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAbstractLessonsResponse) GetAbstractLessons() []*AbstractLesson {
	if x != nil {
		return x.AbstractLessons
	}
	return nil
}

type CreateConcreteLessonRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AbstractLessonUuid string                 `protobuf:"bytes,1,opt,name=abstract_lesson_uuid,json=abstractLessonUuid,proto3" json:"abstract_lesson_uuid,omitempty"`
	TeacherUuid        string                 `protobuf:"bytes,2,opt,name=teacher_uuid,json=teacherUuid,proto3" json:"teacher_uuid,omitempty"`
	GroupUuid          string                 `protobuf:"bytes,5,opt,name=group_uuid,json=groupUuid,proto3" json:"group_uuid,omitempty"`
	PeriodUuid         string                 `protobuf:"bytes,6,opt,name=period_uuid,json=periodUuid,proto3" json:"period_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateConcreteLessonRequest) Reset() {
	*x = CreateConcreteLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateConcreteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateConcreteLessonRequest) ProtoMessage() {}

func (x *CreateConcreteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateConcreteLessonRequest.ProtoReflect.Descriptor instead.
func (*CreateConcreteLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{19}
}

func (x *CreateConcreteLessonRequest) GetAbstractLessonUuid() string {
	if x != nil {
		return x.AbstractLessonUuid
	}
	return ""
}

func (x *CreateConcreteLessonRequest) GetTeacherUuid() string {
	if x != nil {
		return x.TeacherUuid
	}
	return ""
}

func (x *CreateConcreteLessonRequest) GetGroupUuid() string {
	if x != nil {
		return x.GroupUuid
	}
	return ""
}

func (x *CreateConcreteLessonRequest) GetPeriodUuid() string {
	if x != nil {
		return x.PeriodUuid
	}
	return ""
}

type DeleteConcreteLessonRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DeleteConcreteLessonRequest) Reset() {
	*x = DeleteConcreteLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConcreteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConcreteLessonRequest) ProtoMessage() {}

func (x *DeleteConcreteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConcreteLessonRequest.ProtoReflect.Descriptor instead.
func (*DeleteConcreteLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteConcreteLessonRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

type PatchConcreteLessonRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PeriodUuid         *string                `protobuf:"bytes,1,opt,name=period_uuid,json=periodUuid,proto3,oneof" json:"period_uuid,omitempty"`
	AbstractLessonUuid *string                `protobuf:"bytes,3,opt,name=abstract_lesson_uuid,json=abstractLessonUuid,proto3,oneof" json:"abstract_lesson_uuid,omitempty"`
	TeacherUuid        *string                `protobuf:"bytes,4,opt,name=teacher_uuid,json=teacherUuid,proto3,oneof" json:"teacher_uuid,omitempty"`
	ConcreteLessonUuid string                 `protobuf:"bytes,5,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	GroupUuid          *string                `protobuf:"bytes,6,opt,name=group_uuid,json=groupUuid,proto3,oneof" json:"group_uuid,omitempty"`
	Building           *string                `protobuf:"bytes,7,opt,name=building,proto3,oneof" json:"building,omitempty"`
	Auditorium         *string                `protobuf:"bytes,8,opt,name=auditorium,proto3,oneof" json:"auditorium,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PatchConcreteLessonRequest) Reset() {
	*x = PatchConcreteLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchConcreteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchConcreteLessonRequest) ProtoMessage() {}

func (x *PatchConcreteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchConcreteLessonRequest.ProtoReflect.Descriptor instead.
func (*PatchConcreteLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{21}
}

func (x *PatchConcreteLessonRequest) GetPeriodUuid() string {
	if x != nil && x.PeriodUuid != nil {
		return *x.PeriodUuid
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetAbstractLessonUuid() string {
	if x != nil && x.AbstractLessonUuid != nil {
		return *x.AbstractLessonUuid
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetTeacherUuid() string {
	if x != nil && x.TeacherUuid != nil {
		return *x.TeacherUuid
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetGroupUuid() string {
	if x != nil && x.GroupUuid != nil {
		return *x.GroupUuid
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetBuilding() string {
	if x != nil && x.Building != nil {
		return *x.Building
	}
	return ""
}

func (x *PatchConcreteLessonRequest) GetAuditorium() string {
	if x != nil && x.Auditorium != nil {
		return *x.Auditorium
	}
	return ""
}

type GetConcreteLessonRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetConcreteLessonRequest) Reset() {
	*x = GetConcreteLessonRequest{}
	mi := &file_proto_timetable_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcreteLessonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcreteLessonRequest) ProtoMessage() {}

func (x *GetConcreteLessonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcreteLessonRequest.ProtoReflect.Descriptor instead.
func (*GetConcreteLessonRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{22}
}

func (x *GetConcreteLessonRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

type GetConcreteLessonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lesson        *ConcreteLesson        `protobuf:"bytes,1,opt,name=lesson,proto3" json:"lesson,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConcreteLessonResponse) Reset() {
	*x = GetConcreteLessonResponse{}
	mi := &file_proto_timetable_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConcreteLessonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConcreteLessonResponse) ProtoMessage() {}

func (x *GetConcreteLessonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConcreteLessonResponse.ProtoReflect.Descriptor instead.
func (*GetConcreteLessonResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{23}
}

func (x *GetConcreteLessonResponse) GetLesson() *ConcreteLesson {
	if x != nil {
		return x.Lesson
	}
	return nil
}

type HomeworkBodyPUTUrlRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HomeworkBodyPUTUrlRequest) Reset() {
	*x = HomeworkBodyPUTUrlRequest{}
	mi := &file_proto_timetable_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkBodyPUTUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkBodyPUTUrlRequest) ProtoMessage() {}

func (x *HomeworkBodyPUTUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkBodyPUTUrlRequest.ProtoReflect.Descriptor instead.
func (*HomeworkBodyPUTUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{24}
}

func (x *HomeworkBodyPUTUrlRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

type HomeworkBodyPUTUrlResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HomeworkBodyUrl string                 `protobuf:"bytes,1,opt,name=homework_body_url,json=homeworkBodyUrl,proto3" json:"homework_body_url,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HomeworkBodyPUTUrlResponse) Reset() {
	*x = HomeworkBodyPUTUrlResponse{}
	mi := &file_proto_timetable_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkBodyPUTUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkBodyPUTUrlResponse) ProtoMessage() {}

func (x *HomeworkBodyPUTUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkBodyPUTUrlResponse.ProtoReflect.Descriptor instead.
func (*HomeworkBodyPUTUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{25}
}

func (x *HomeworkBodyPUTUrlResponse) GetHomeworkBodyUrl() string {
	if x != nil {
		return x.HomeworkBodyUrl
	}
	return ""
}

type HomeworkAttachmentPUTUrlRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	Mime               string                 `protobuf:"bytes,2,opt,name=mime,proto3" json:"mime,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HomeworkAttachmentPUTUrlRequest) Reset() {
	*x = HomeworkAttachmentPUTUrlRequest{}
	mi := &file_proto_timetable_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkAttachmentPUTUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkAttachmentPUTUrlRequest) ProtoMessage() {}

func (x *HomeworkAttachmentPUTUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkAttachmentPUTUrlRequest.ProtoReflect.Descriptor instead.
func (*HomeworkAttachmentPUTUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{26}
}

func (x *HomeworkAttachmentPUTUrlRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

func (x *HomeworkAttachmentPUTUrlRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *HomeworkAttachmentPUTUrlRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HomeworkAttachmentPUTUrlResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	HomeworkAttachmentUrl string                 `protobuf:"bytes,1,opt,name=homework_attachment_url,json=homeworkAttachmentUrl,proto3" json:"homework_attachment_url,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HomeworkAttachmentPUTUrlResponse) Reset() {
	*x = HomeworkAttachmentPUTUrlResponse{}
	mi := &file_proto_timetable_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkAttachmentPUTUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkAttachmentPUTUrlResponse) ProtoMessage() {}

func (x *HomeworkAttachmentPUTUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkAttachmentPUTUrlResponse.ProtoReflect.Descriptor instead.
func (*HomeworkAttachmentPUTUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{27}
}

func (x *HomeworkAttachmentPUTUrlResponse) GetHomeworkAttachmentUrl() string {
	if x != nil {
		return x.HomeworkAttachmentUrl
	}
	return ""
}

type HomeworkAttachmentGETUrlsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HomeworkAttachmentGETUrlsRequest) Reset() {
	*x = HomeworkAttachmentGETUrlsRequest{}
	mi := &file_proto_timetable_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkAttachmentGETUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkAttachmentGETUrlsRequest) ProtoMessage() {}

func (x *HomeworkAttachmentGETUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkAttachmentGETUrlsRequest.ProtoReflect.Descriptor instead.
func (*HomeworkAttachmentGETUrlsRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{28}
}

func (x *HomeworkAttachmentGETUrlsRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

type HomeworkAttachmentGETUrlsResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	HomeworkAttachmentUrls []string               `protobuf:"bytes,1,rep,name=homework_attachment_urls,json=homeworkAttachmentUrls,proto3" json:"homework_attachment_urls,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HomeworkAttachmentGETUrlsResponse) Reset() {
	*x = HomeworkAttachmentGETUrlsResponse{}
	mi := &file_proto_timetable_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkAttachmentGETUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkAttachmentGETUrlsResponse) ProtoMessage() {}

func (x *HomeworkAttachmentGETUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkAttachmentGETUrlsResponse.ProtoReflect.Descriptor instead.
func (*HomeworkAttachmentGETUrlsResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{29}
}

func (x *HomeworkAttachmentGETUrlsResponse) GetHomeworkAttachmentUrls() []string {
	if x != nil {
		return x.HomeworkAttachmentUrls
	}
	return nil
}

type HomeworkBodyGETUrlRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ConcreteLessonUuid string                 `protobuf:"bytes,1,opt,name=concrete_lesson_uuid,json=concreteLessonUuid,proto3" json:"concrete_lesson_uuid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HomeworkBodyGETUrlRequest) Reset() {
	*x = HomeworkBodyGETUrlRequest{}
	mi := &file_proto_timetable_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkBodyGETUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkBodyGETUrlRequest) ProtoMessage() {}

func (x *HomeworkBodyGETUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkBodyGETUrlRequest.ProtoReflect.Descriptor instead.
func (*HomeworkBodyGETUrlRequest) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{30}
}

func (x *HomeworkBodyGETUrlRequest) GetConcreteLessonUuid() string {
	if x != nil {
		return x.ConcreteLessonUuid
	}
	return ""
}

type HomeworkBodyGETUrlResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	HomeworkBodyUuid string                 `protobuf:"bytes,1,opt,name=homework_body_uuid,json=homeworkBodyUuid,proto3" json:"homework_body_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HomeworkBodyGETUrlResponse) Reset() {
	*x = HomeworkBodyGETUrlResponse{}
	mi := &file_proto_timetable_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HomeworkBodyGETUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HomeworkBodyGETUrlResponse) ProtoMessage() {}

func (x *HomeworkBodyGETUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_timetable_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HomeworkBodyGETUrlResponse.ProtoReflect.Descriptor instead.
func (*HomeworkBodyGETUrlResponse) Descriptor() ([]byte, []int) {
	return file_proto_timetable_proto_rawDescGZIP(), []int{31}
}

func (x *HomeworkBodyGETUrlResponse) GetHomeworkBodyUuid() string {
	if x != nil {
		return x.HomeworkBodyUuid
	}
	return ""
}

var File_proto_timetable_proto protoreflect.FileDescriptor

const file_proto_timetable_proto_rawDesc = "" +
	"\n" +
	"\x15proto/timetable.proto\x12\ttimetable\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x15ListTimetablesRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"u\n" +
	"\x13GetTimetableRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12 \n" +
	"\x03day\x18\x03 \x01(\x0e2\x0e.timetable.DayR\x03day\"Y\n" +
	"\x14GetTimetableResponse\x12A\n" +
	"\tTimetable\x18\x01 \x01(\v2#.timetable.ConcreteLessonShortEntryR\tTimetable\"8\n" +
	"\x0eAbstractLesson\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8c\x04\n" +
	"\x0eConcreteLesson\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\rR\x04year\x12:\n" +
	"\vlesson_info\x18\x03 \x01(\v2\x19.timetable.AbstractLessonR\n" +
	"lessonInfo\x12!\n" +
	"\fteacher_uuid\x18\x04 \x01(\tR\vteacherUuid\x126\n" +
	"\x15homework_text_get_url\x18\x05 \x01(\tH\x00R\x12homeworkTextGetUrl\x88\x01\x01\x12A\n" +
	"\x1dhomework_attachments_get_urls\x18\x06 \x03(\tR\x1ahomeworkAttachmentsGetUrls\x12\x1f\n" +
	"\vlesson_uuid\x18\a \x01(\tR\n" +
	"lessonUuid\x12\x14\n" +
	"\x05marks\x18\b \x03(\tR\x05marks\x12\x16\n" +
	"\x06period\x18\t \x01(\rR\x06period\x12 \n" +
	"\x03day\x18\n" +
	" \x01(\x0e2\x0e.timetable.DayR\x03day\x12\x1f\n" +
	"\bbuilding\x18\v \x01(\tH\x01R\bbuilding\x88\x01\x01\x12#\n" +
	"\n" +
	"auditorium\x18\f \x01(\tH\x02R\n" +
	"auditorium\x88\x01\x01B\x18\n" +
	"\x16_homework_text_get_urlB\v\n" +
	"\t_buildingB\r\n" +
	"\v_auditorium\"\xd2\x02\n" +
	"\x13ShortConcreteLesson\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\rR\x04year\x12\x16\n" +
	"\x06period\x18\x03 \x01(\rR\x06period\x12B\n" +
	"\x0fabstract_lesson\x18\x04 \x01(\v2\x19.timetable.AbstractLessonR\x0eabstractLesson\x12&\n" +
	"\x0fis_homework_due\x18\x05 \x01(\bR\risHomeworkDue\x12 \n" +
	"\x03day\x18\x06 \x01(\x0e2\x0e.timetable.DayR\x03day\x12\x1f\n" +
	"\bbuilding\x18\a \x01(\tH\x00R\bbuilding\x88\x01\x01\x12#\n" +
	"\n" +
	"auditorium\x18\b \x01(\tH\x01R\n" +
	"auditorium\x88\x01\x01B\v\n" +
	"\t_buildingB\r\n" +
	"\v_auditorium\"v\n" +
	"\x18ConcreteLessonShortEntry\x12 \n" +
	"\x03day\x18\x01 \x01(\x0e2\x0e.timetable.DayR\x03day\x128\n" +
	"\alessons\x18\x02 \x03(\v2\x1e.timetable.ShortConcreteLessonR\alessons\"Z\n" +
	"\x15ListTimetableResponse\x12A\n" +
	"\tTimetable\x18\x01 \x03(\v2#.timetable.ConcreteLessonShortEntryR\tTimetable\"1\n" +
	"\x1bCreateAbstractLessonRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf8\x01\n" +
	"\x06Period\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\x120\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\x12 \n" +
	"\x03day\x18\x04 \x01(\x0e2\x0e.timetable.DayR\x03day\x12\x12\n" +
	"\x04year\x18\x05 \x01(\rR\x04year\x12\x1f\n" +
	"\vweek_number\x18\x06 \x01(\rR\n" +
	"weekNumber\x12\x1f\n" +
	"\vperiod_uuid\x18\a \x01(\tR\n" +
	"periodUuid\"i\n" +
	"\x10GetPeriodRequest\x12\x1f\n" +
	"\vweek_number\x18\x01 \x01(\rR\n" +
	"weekNumber\x12 \n" +
	"\x03day\x18\x02 \x01(\x0e2\x0e.timetable.DayR\x03day\x12\x12\n" +
	"\x04year\x18\x03 \x01(\rR\x04year\"A\n" +
	"\x12GetPeriodsResponse\x12+\n" +
	"\aperiods\x18\x01 \x03(\v2\x11.timetable.PeriodR\aperiods\"\xe0\x02\n" +
	"\x12PatchPeriodRequest\x12\x1f\n" +
	"\vperiod_uuid\x18\a \x01(\tR\n" +
	"periodUuid\x12\x1b\n" +
	"\x06number\x18\x01 \x01(\rH\x00R\x06number\x88\x01\x01\x125\n" +
	"\x05start\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x05start\x88\x01\x01\x121\n" +
	"\x03end\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x03end\x88\x01\x01\x12%\n" +
	"\x03day\x18\x04 \x01(\x0e2\x0e.timetable.DayH\x03R\x03day\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\x05 \x01(\rH\x04R\x04year\x88\x01\x01\x12$\n" +
	"\vweek_number\x18\x06 \x01(\rH\x05R\n" +
	"weekNumber\x88\x01\x01B\t\n" +
	"\a_numberB\b\n" +
	"\x06_startB\x06\n" +
	"\x04_endB\x06\n" +
	"\x04_dayB\a\n" +
	"\x05_yearB\x0e\n" +
	"\f_week_number\">\n" +
	"\x1bDeleteAbstractLessonRequest\x12\x1f\n" +
	"\vlesson_uuid\x18\x01 \x01(\tR\n" +
	"lessonUuid\";\n" +
	"\x18GetAbstractLessonRequest\x12\x1f\n" +
	"\vlesson_uuid\x18\x01 \x01(\tR\n" +
	"lessonUuid\"N\n" +
	"\x19GetAbstractLessonResponse\x121\n" +
	"\x06lesson\x18\x01 \x01(\v2\x19.timetable.AbstractLessonR\x06lesson\"_\n" +
	"\x1aPatchAbstractLessonRequest\x12\x1f\n" +
	"\vlesson_uuid\x18\x01 \x01(\tR\n" +
	"lessonUuid\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"D\n" +
	"\x1aListAbstractLessonsRequest\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x04R\x04page\"\xa1\x01\n" +
	"\x1bListAbstractLessonsResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x04R\x04page\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12D\n" +
	"\x10abstract_lessons\x18\x04 \x03(\v2\x19.timetable.AbstractLessonR\x0fabstractLessons\"\xb2\x01\n" +
	"\x1bCreateConcreteLessonRequest\x120\n" +
	"\x14abstract_lesson_uuid\x18\x01 \x01(\tR\x12abstractLessonUuid\x12!\n" +
	"\fteacher_uuid\x18\x02 \x01(\tR\vteacherUuid\x12\x1d\n" +
	"\n" +
	"group_uuid\x18\x05 \x01(\tR\tgroupUuid\x12\x1f\n" +
	"\vperiod_uuid\x18\x06 \x01(\tR\n" +
	"periodUuid\"O\n" +
	"\x1bDeleteConcreteLessonRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\"\xa2\x03\n" +
	"\x1aPatchConcreteLessonRequest\x12$\n" +
	"\vperiod_uuid\x18\x01 \x01(\tH\x00R\n" +
	"periodUuid\x88\x01\x01\x125\n" +
	"\x14abstract_lesson_uuid\x18\x03 \x01(\tH\x01R\x12abstractLessonUuid\x88\x01\x01\x12&\n" +
	"\fteacher_uuid\x18\x04 \x01(\tH\x02R\vteacherUuid\x88\x01\x01\x120\n" +
	"\x14concrete_lesson_uuid\x18\x05 \x01(\tR\x12concreteLessonUuid\x12\"\n" +
	"\n" +
	"group_uuid\x18\x06 \x01(\tH\x03R\tgroupUuid\x88\x01\x01\x12\x1f\n" +
	"\bbuilding\x18\a \x01(\tH\x04R\bbuilding\x88\x01\x01\x12#\n" +
	"\n" +
	"auditorium\x18\b \x01(\tH\x05R\n" +
	"auditorium\x88\x01\x01B\x0e\n" +
	"\f_period_uuidB\x17\n" +
	"\x15_abstract_lesson_uuidB\x0f\n" +
	"\r_teacher_uuidB\r\n" +
	"\v_group_uuidB\v\n" +
	"\t_buildingB\r\n" +
	"\v_auditorium\"L\n" +
	"\x18GetConcreteLessonRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\"N\n" +
	"\x19GetConcreteLessonResponse\x121\n" +
	"\x06lesson\x18\x01 \x01(\v2\x19.timetable.ConcreteLessonR\x06lesson\"M\n" +
	"\x19HomeworkBodyPUTUrlRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\"H\n" +
	"\x1aHomeworkBodyPUTUrlResponse\x12*\n" +
	"\x11homework_body_url\x18\x01 \x01(\tR\x0fhomeworkBodyUrl\"{\n" +
	"\x1fHomeworkAttachmentPUTUrlRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\x12\x12\n" +
	"\x04mime\x18\x02 \x01(\tR\x04mime\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"Z\n" +
	" HomeworkAttachmentPUTUrlResponse\x126\n" +
	"\x17homework_attachment_url\x18\x01 \x01(\tR\x15homeworkAttachmentUrl\"T\n" +
	" HomeworkAttachmentGETUrlsRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\"]\n" +
	"!HomeworkAttachmentGETUrlsResponse\x128\n" +
	"\x18homework_attachment_urls\x18\x01 \x03(\tR\x16homeworkAttachmentUrls\"M\n" +
	"\x19HomeworkBodyGETUrlRequest\x120\n" +
	"\x14concrete_lesson_uuid\x18\x01 \x01(\tR\x12concreteLessonUuid\"J\n" +
	"\x1aHomeworkBodyGETUrlResponse\x12,\n" +
	"\x12homework_body_uuid\x18\x01 \x01(\tR\x10homeworkBodyUuid*r\n" +
	"\x03Day\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06MONDAY\x10\x01\x12\v\n" +
	"\aTUESDAY\x10\x02\x12\r\n" +
	"\tWEDNESDAY\x10\x03\x12\f\n" +
	"\bTHURSDAY\x10\x04\x12\n" +
	"\n" +
	"\x06FRIDAY\x10\x05\x12\f\n" +
	"\bSATURDAY\x10\x06\x12\n" +
	"\n" +
	"\x06SUNDAY\x10\a2\x95\x14\n" +
	"\x10TimetableService\x12\x84\x01\n" +
	"\rListTimetable\x12 .timetable.ListTimetablesRequest\x1a .timetable.ListTimetableResponse\"/\x82\xd3\xe4\x93\x02)\x12'/v1/timetable/{user_uuid}/{week_number}\x12\x86\x01\n" +
	"\fGetTimetable\x12\x1e.timetable.GetTimetableRequest\x1a\x1f.timetable.GetTimetableResponse\"5\x82\xd3\xe4\x93\x02/\x12-/v1/timetable/{user_uuid}/{week_number}/{day}\x12\x80\x01\n" +
	"\x14CreateAbstractLesson\x12&.timetable.CreateAbstractLessonRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/timetable/lesson/abstract\x12\x8b\x01\n" +
	"\x14DeleteAbstractLesson\x12&.timetable.DeleteAbstractLessonRequest\x1a\x16.google.protobuf.Empty\"3\x82\xd3\xe4\x93\x02-*+/v1/timetable/lesson/abstract/{lesson_uuid}\x12\x93\x01\n" +
	"\x11GetAbstractLesson\x12#.timetable.GetAbstractLessonRequest\x1a$.timetable.GetAbstractLessonResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/timetable/lesson/abstract/{lesson_uuid}\x12\x8c\x01\n" +
	"\x13PatchAbstractLesson\x12%.timetable.PatchAbstractLessonRequest\x1a\x16.google.protobuf.Empty\"6\x82\xd3\xe4\x93\x020:\x01*2+/v1/timetable/lesson/abstract/{lesson_uuid}\x12\x8b\x01\n" +
	"\x13ListAbstractLessons\x12%.timetable.ListAbstractLessonsRequest\x1a&.timetable.ListAbstractLessonsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/timetable/lesson/abstract\x12\x80\x01\n" +
	"\x14CreateConcreteLesson\x12&.timetable.CreateConcreteLessonRequest\x1a\x16.google.protobuf.Empty\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/timetable/lesson/concrete\x12\x94\x01\n" +
	"\x14DeleteConcreteLesson\x12&.timetable.DeleteConcreteLessonRequest\x1a\x16.google.protobuf.Empty\"<\x82\xd3\xe4\x93\x026*4/v1/timetable/lesson/concrete/{concrete_lesson_uuid}\x12\x92\x01\n" +
	"\x13PatchConcreteLesson\x12%.timetable.PatchConcreteLessonRequest\x1a\x16.google.protobuf.Empty\"<\x82\xd3\xe4\x93\x02624/v1/timetable/lesson/concrete/{concrete_lesson_uuid}\x12\x9c\x01\n" +
	"\x11GetConcreteLesson\x12#.timetable.GetConcreteLessonRequest\x1a$.timetable.GetConcreteLessonResponse\"<\x82\xd3\xe4\x93\x026\x124/v1/timetable/lesson/concrete/{concrete_lesson_uuid}\x12\x82\x01\n" +
	"\n" +
	"GetPeriods\x12\x1b.timetable.GetPeriodRequest\x1a\x1d.timetable.GetPeriodsResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/timetable/periods/{year}/{week_number}/{day}\x12t\n" +
	"\vPatchPeriod\x12\x1d.timetable.PatchPeriodRequest\x1a\x16.google.protobuf.Empty\".\x82\xd3\xe4\x93\x02(:\x01*2#/v1/timetable/periods/{period_uuid}\x12\xaf\x01\n" +
	"\x12HomeworkBodyPUTUrl\x12$.timetable.HomeworkBodyPUTUrlRequest\x1a%.timetable.HomeworkBodyPUTUrlResponse\"L\x82\xd3\xe4\x93\x02F\x12D/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/homework/upload\x12\xa8\x01\n" +
	"\x12HomeworkBodyGETUrl\x12$.timetable.HomeworkBodyGETUrlRequest\x1a%.timetable.HomeworkBodyGETUrlResponse\"E\x82\xd3\xe4\x93\x02?\x12=/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/homework\x12\xc4\x01\n" +
	"\x18HomeworkAttachmentPUTUrl\x12*.timetable.HomeworkAttachmentPUTUrlRequest\x1a+.timetable.HomeworkAttachmentPUTUrlResponse\"O\x82\xd3\xe4\x93\x02I\x12G/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/attachments/upload\x12\xbf\x01\n" +
	"\x18HomeworkAttachmentGETUrl\x12+.timetable.HomeworkAttachmentGETUrlsRequest\x1a,.timetable.HomeworkAttachmentGETUrlsResponse\"H\x82\xd3\xe4\x93\x02B\x12@/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/attachmentsB\x04Z\x02./b\x06proto3"

var (
	file_proto_timetable_proto_rawDescOnce sync.Once
	file_proto_timetable_proto_rawDescData []byte
)

func file_proto_timetable_proto_rawDescGZIP() []byte {
	file_proto_timetable_proto_rawDescOnce.Do(func() {
		file_proto_timetable_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_timetable_proto_rawDesc), len(file_proto_timetable_proto_rawDesc)))
	})
	return file_proto_timetable_proto_rawDescData
}

var file_proto_timetable_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_timetable_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_timetable_proto_goTypes = []any{
	(Day)(0),                                  // 0: timetable.Day
	(*ListTimetablesRequest)(nil),             // 1: timetable.ListTimetablesRequest
	(*GetTimetableRequest)(nil),               // 2: timetable.GetTimetableRequest
	(*GetTimetableResponse)(nil),              // 3: timetable.GetTimetableResponse
	(*AbstractLesson)(nil),                    // 4: timetable.AbstractLesson
	(*ConcreteLesson)(nil),                    // 5: timetable.ConcreteLesson
	(*ShortConcreteLesson)(nil),               // 6: timetable.ShortConcreteLesson
	(*ConcreteLessonShortEntry)(nil),          // 7: timetable.ConcreteLessonShortEntry
	(*ListTimetableResponse)(nil),             // 8: timetable.ListTimetableResponse
	(*CreateAbstractLessonRequest)(nil),       // 9: timetable.CreateAbstractLessonRequest
	(*Period)(nil),                            // 10: timetable.Period
	(*GetPeriodRequest)(nil),                  // 11: timetable.GetPeriodRequest
	(*GetPeriodsResponse)(nil),                // 12: timetable.GetPeriodsResponse
	(*PatchPeriodRequest)(nil),                // 13: timetable.PatchPeriodRequest
	(*DeleteAbstractLessonRequest)(nil),       // 14: timetable.DeleteAbstractLessonRequest
	(*GetAbstractLessonRequest)(nil),          // 15: timetable.GetAbstractLessonRequest
	(*GetAbstractLessonResponse)(nil),         // 16: timetable.GetAbstractLessonResponse
	(*PatchAbstractLessonRequest)(nil),        // 17: timetable.PatchAbstractLessonRequest
	(*ListAbstractLessonsRequest)(nil),        // 18: timetable.ListAbstractLessonsRequest
	(*ListAbstractLessonsResponse)(nil),       // 19: timetable.ListAbstractLessonsResponse
	(*CreateConcreteLessonRequest)(nil),       // 20: timetable.CreateConcreteLessonRequest
	(*DeleteConcreteLessonRequest)(nil),       // 21: timetable.DeleteConcreteLessonRequest
	(*PatchConcreteLessonRequest)(nil),        // 22: timetable.PatchConcreteLessonRequest
	(*GetConcreteLessonRequest)(nil),          // 23: timetable.GetConcreteLessonRequest
	(*GetConcreteLessonResponse)(nil),         // 24: timetable.GetConcreteLessonResponse
	(*HomeworkBodyPUTUrlRequest)(nil),         // 25: timetable.HomeworkBodyPUTUrlRequest
	(*HomeworkBodyPUTUrlResponse)(nil),        // 26: timetable.HomeworkBodyPUTUrlResponse
	(*HomeworkAttachmentPUTUrlRequest)(nil),   // 27: timetable.HomeworkAttachmentPUTUrlRequest
	(*HomeworkAttachmentPUTUrlResponse)(nil),  // 28: timetable.HomeworkAttachmentPUTUrlResponse
	(*HomeworkAttachmentGETUrlsRequest)(nil),  // 29: timetable.HomeworkAttachmentGETUrlsRequest
	(*HomeworkAttachmentGETUrlsResponse)(nil), // 30: timetable.HomeworkAttachmentGETUrlsResponse
	(*HomeworkBodyGETUrlRequest)(nil),         // 31: timetable.HomeworkBodyGETUrlRequest
	(*HomeworkBodyGETUrlResponse)(nil),        // 32: timetable.HomeworkBodyGETUrlResponse
	(*timestamppb.Timestamp)(nil),             // 33: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 34: google.protobuf.Empty
}
var file_proto_timetable_proto_depIdxs = []int32{
	0,  // 0: timetable.GetTimetableRequest.day:type_name -> timetable.Day
	7,  // 1: timetable.GetTimetableResponse.Timetable:type_name -> timetable.ConcreteLessonShortEntry
	4,  // 2: timetable.ConcreteLesson.lesson_info:type_name -> timetable.AbstractLesson
	0,  // 3: timetable.ConcreteLesson.day:type_name -> timetable.Day
	4,  // 4: timetable.ShortConcreteLesson.abstract_lesson:type_name -> timetable.AbstractLesson
	0,  // 5: timetable.ShortConcreteLesson.day:type_name -> timetable.Day
	0,  // 6: timetable.ConcreteLessonShortEntry.day:type_name -> timetable.Day
	6,  // 7: timetable.ConcreteLessonShortEntry.lessons:type_name -> timetable.ShortConcreteLesson
	7,  // 8: timetable.ListTimetableResponse.Timetable:type_name -> timetable.ConcreteLessonShortEntry
	33, // 9: timetable.Period.start:type_name -> google.protobuf.Timestamp
	33, // 10: timetable.Period.end:type_name -> google.protobuf.Timestamp
	0,  // 11: timetable.Period.day:type_name -> timetable.Day
	0,  // 12: timetable.GetPeriodRequest.day:type_name -> timetable.Day
	10, // 13: timetable.GetPeriodsResponse.periods:type_name -> timetable.Period
	33, // 14: timetable.PatchPeriodRequest.start:type_name -> google.protobuf.Timestamp
	33, // 15: timetable.PatchPeriodRequest.end:type_name -> google.protobuf.Timestamp
	0,  // 16: timetable.PatchPeriodRequest.day:type_name -> timetable.Day
	4,  // 17: timetable.GetAbstractLessonResponse.lesson:type_name -> timetable.AbstractLesson
	4,  // 18: timetable.ListAbstractLessonsResponse.abstract_lessons:type_name -> timetable.AbstractLesson
	5,  // 19: timetable.GetConcreteLessonResponse.lesson:type_name -> timetable.ConcreteLesson
	1,  // 20: timetable.TimetableService.ListTimetable:input_type -> timetable.ListTimetablesRequest
	2,  // 21: timetable.TimetableService.GetTimetable:input_type -> timetable.GetTimetableRequest
	9,  // 22: timetable.TimetableService.CreateAbstractLesson:input_type -> timetable.CreateAbstractLessonRequest
	14, // 23: timetable.TimetableService.DeleteAbstractLesson:input_type -> timetable.DeleteAbstractLessonRequest
	15, // 24: timetable.TimetableService.GetAbstractLesson:input_type -> timetable.GetAbstractLessonRequest
	17, // 25: timetable.TimetableService.PatchAbstractLesson:input_type -> timetable.PatchAbstractLessonRequest
	18, // 26: timetable.TimetableService.ListAbstractLessons:input_type -> timetable.ListAbstractLessonsRequest
	20, // 27: timetable.TimetableService.CreateConcreteLesson:input_type -> timetable.CreateConcreteLessonRequest
	21, // 28: timetable.TimetableService.DeleteConcreteLesson:input_type -> timetable.DeleteConcreteLessonRequest
	22, // 29: timetable.TimetableService.PatchConcreteLesson:input_type -> timetable.PatchConcreteLessonRequest
	23, // 30: timetable.TimetableService.GetConcreteLesson:input_type -> timetable.GetConcreteLessonRequest
	11, // 31: timetable.TimetableService.GetPeriods:input_type -> timetable.GetPeriodRequest
	13, // 32: timetable.TimetableService.PatchPeriod:input_type -> timetable.PatchPeriodRequest
	25, // 33: timetable.TimetableService.HomeworkBodyPUTUrl:input_type -> timetable.HomeworkBodyPUTUrlRequest
	31, // 34: timetable.TimetableService.HomeworkBodyGETUrl:input_type -> timetable.HomeworkBodyGETUrlRequest
	27, // 35: timetable.TimetableService.HomeworkAttachmentPUTUrl:input_type -> timetable.HomeworkAttachmentPUTUrlRequest
	29, // 36: timetable.TimetableService.HomeworkAttachmentGETUrl:input_type -> timetable.HomeworkAttachmentGETUrlsRequest
	8,  // 37: timetable.TimetableService.ListTimetable:output_type -> timetable.ListTimetableResponse
	3,  // 38: timetable.TimetableService.GetTimetable:output_type -> timetable.GetTimetableResponse
	34, // 39: timetable.TimetableService.CreateAbstractLesson:output_type -> google.protobuf.Empty
	34, // 40: timetable.TimetableService.DeleteAbstractLesson:output_type -> google.protobuf.Empty
	16, // 41: timetable.TimetableService.GetAbstractLesson:output_type -> timetable.GetAbstractLessonResponse
	34, // 42: timetable.TimetableService.PatchAbstractLesson:output_type -> google.protobuf.Empty
	19, // 43: timetable.TimetableService.ListAbstractLessons:output_type -> timetable.ListAbstractLessonsResponse
	34, // 44: timetable.TimetableService.CreateConcreteLesson:output_type -> google.protobuf.Empty
	34, // 45: timetable.TimetableService.DeleteConcreteLesson:output_type -> google.protobuf.Empty
	34, // 46: timetable.TimetableService.PatchConcreteLesson:output_type -> google.protobuf.Empty
	24, // 47: timetable.TimetableService.GetConcreteLesson:output_type -> timetable.GetConcreteLessonResponse
	12, // 48: timetable.TimetableService.GetPeriods:output_type -> timetable.GetPeriodsResponse
	34, // 49: timetable.TimetableService.PatchPeriod:output_type -> google.protobuf.Empty
	26, // 50: timetable.TimetableService.HomeworkBodyPUTUrl:output_type -> timetable.HomeworkBodyPUTUrlResponse
	32, // 51: timetable.TimetableService.HomeworkBodyGETUrl:output_type -> timetable.HomeworkBodyGETUrlResponse
	28, // 52: timetable.TimetableService.HomeworkAttachmentPUTUrl:output_type -> timetable.HomeworkAttachmentPUTUrlResponse
	30, // 53: timetable.TimetableService.HomeworkAttachmentGETUrl:output_type -> timetable.HomeworkAttachmentGETUrlsResponse
	37, // [37:54] is the sub-list for method output_type
	20, // [20:37] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_timetable_proto_init() }
func file_proto_timetable_proto_init() {
	if File_proto_timetable_proto != nil {
		return
	}
	file_proto_timetable_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_timetable_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_timetable_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_timetable_proto_msgTypes[16].OneofWrappers = []any{}
	file_proto_timetable_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_timetable_proto_rawDesc), len(file_proto_timetable_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_timetable_proto_goTypes,
		DependencyIndexes: file_proto_timetable_proto_depIdxs,
		EnumInfos:         file_proto_timetable_proto_enumTypes,
		MessageInfos:      file_proto_timetable_proto_msgTypes,
	}.Build()
	File_proto_timetable_proto = out.File
	file_proto_timetable_proto_goTypes = nil
	file_proto_timetable_proto_depIdxs = nil
}
