// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/puddle.proto

package __

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PuddleType int32

const (
	PuddleType_UNSPECIFIED PuddleType = 0
	PuddleType_GROUP       PuddleType = 1
	PuddleType_ONEONONE    PuddleType = 2
	PuddleType_CHANNEL     PuddleType = 3
)

// Enum value maps for PuddleType.
var (
	PuddleType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GROUP",
		2: "ONEONONE",
		3: "CHANNEL",
	}
	PuddleType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GROUP":       1,
		"ONEONONE":    2,
		"CHANNEL":     3,
	}
)

func (x PuddleType) Enum() *PuddleType {
	p := new(PuddleType)
	*p = x
	return p
}

func (x PuddleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PuddleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_puddle_proto_enumTypes[0].Descriptor()
}

func (PuddleType) Type() protoreflect.EnumType {
	return &file_proto_puddle_proto_enumTypes[0]
}

func (x PuddleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PuddleType.Descriptor instead.
func (PuddleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{0}
}

type Puddle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UUID          string                 `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PuddleType    PuddleType             `protobuf:"varint,4,opt,name=puddle_type,json=puddleType,proto3,enum=puddle.PuddleType" json:"puddle_type,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	MemberCount   uint64                 `protobuf:"varint,8,opt,name=memberCount,proto3" json:"memberCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Puddle) Reset() {
	*x = Puddle{}
	mi := &file_proto_puddle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Puddle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puddle) ProtoMessage() {}

func (x *Puddle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puddle.ProtoReflect.Descriptor instead.
func (*Puddle) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{0}
}

func (x *Puddle) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *Puddle) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Puddle) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Puddle) GetPuddleType() PuddleType {
	if x != nil {
		return x.PuddleType
	}
	return PuddleType_UNSPECIFIED
}

func (x *Puddle) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Puddle) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Puddle) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Puddle) GetMemberCount() uint64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsModerator   bool                   `protobuf:"varint,4,opt,name=isModerator,proto3" json:"isModerator,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_puddle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetIsModerator() bool {
	if x != nil {
		return x.IsModerator
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PuddleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuddleRequest) Reset() {
	*x = PuddleRequest{}
	mi := &file_proto_puddle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuddleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuddleRequest) ProtoMessage() {}

func (x *PuddleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuddleRequest.ProtoReflect.Descriptor instead.
func (*PuddleRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{2}
}

func (x *PuddleRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type PuddleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puddle        *Puddle                `protobuf:"bytes,1,opt,name=puddle,proto3" json:"puddle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuddleResponse) Reset() {
	*x = PuddleResponse{}
	mi := &file_proto_puddle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuddleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuddleResponse) ProtoMessage() {}

func (x *PuddleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuddleResponse.ProtoReflect.Descriptor instead.
func (*PuddleResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{3}
}

func (x *PuddleResponse) GetPuddle() *Puddle {
	if x != nil {
		return x.Puddle
	}
	return nil
}

type CreatePuddleRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description       *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	PuddleType        PuddleType             `protobuf:"varint,3,opt,name=puddle_type,json=puddleType,proto3,enum=puddle.PuddleType" json:"puddle_type,omitempty"`
	InvitedUsersUUIDs []string               `protobuf:"bytes,4,rep,name=invitedUsersUUIDs,proto3" json:"invitedUsersUUIDs,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreatePuddleRequest) Reset() {
	*x = CreatePuddleRequest{}
	mi := &file_proto_puddle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePuddleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePuddleRequest) ProtoMessage() {}

func (x *CreatePuddleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePuddleRequest.ProtoReflect.Descriptor instead.
func (*CreatePuddleRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePuddleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePuddleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreatePuddleRequest) GetPuddleType() PuddleType {
	if x != nil {
		return x.PuddleType
	}
	return PuddleType_UNSPECIFIED
}

func (x *CreatePuddleRequest) GetInvitedUsersUUIDs() []string {
	if x != nil {
		return x.InvitedUsersUUIDs
	}
	return nil
}

type PatchPuddleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchPuddleRequest) Reset() {
	*x = PatchPuddleRequest{}
	mi := &file_proto_puddle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchPuddleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchPuddleRequest) ProtoMessage() {}

func (x *PatchPuddleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchPuddleRequest.ProtoReflect.Descriptor instead.
func (*PatchPuddleRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{5}
}

func (x *PatchPuddleRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *PatchPuddleRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *PatchPuddleRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type DeletePuddleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePuddleRequest) Reset() {
	*x = DeletePuddleRequest{}
	mi := &file_proto_puddle_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePuddleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePuddleRequest) ProtoMessage() {}

func (x *DeletePuddleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePuddleRequest.ProtoReflect.Descriptor instead.
func (*DeletePuddleRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{6}
}

func (x *DeletePuddleRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type ListPuddleMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPuddleMembersRequest) Reset() {
	*x = ListPuddleMembersRequest{}
	mi := &file_proto_puddle_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPuddleMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuddleMembersRequest) ProtoMessage() {}

func (x *ListPuddleMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuddleMembersRequest.ProtoReflect.Descriptor instead.
func (*ListPuddleMembersRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{7}
}

func (x *ListPuddleMembersRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *ListPuddleMembersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPuddleMembersRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListPuddleMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPuddleMembersResponse) Reset() {
	*x = ListPuddleMembersResponse{}
	mi := &file_proto_puddle_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPuddleMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPuddleMembersResponse) ProtoMessage() {}

func (x *ListPuddleMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPuddleMembersResponse.ProtoReflect.Descriptor instead.
func (*ListPuddleMembersResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{8}
}

func (x *ListPuddleMembersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListPuddleMembersResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListPuddleMembersResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPuddleMembersResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_puddle_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{9}
}

func (x *AddMemberRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *AddMemberRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type ListMembersPuddlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberUUID    string                 `protobuf:"bytes,1,opt,name=memberUUID,proto3" json:"memberUUID,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersPuddlesRequest) Reset() {
	*x = ListMembersPuddlesRequest{}
	mi := &file_proto_puddle_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersPuddlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersPuddlesRequest) ProtoMessage() {}

func (x *ListMembersPuddlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersPuddlesRequest.ProtoReflect.Descriptor instead.
func (*ListMembersPuddlesRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{10}
}

func (x *ListMembersPuddlesRequest) GetMemberUUID() string {
	if x != nil {
		return x.MemberUUID
	}
	return ""
}

func (x *ListMembersPuddlesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersPuddlesRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMembersPuddlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puddles       []*Puddle              `protobuf:"bytes,1,rep,name=puddles,proto3" json:"puddles,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersPuddlesResponse) Reset() {
	*x = ListMembersPuddlesResponse{}
	mi := &file_proto_puddle_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersPuddlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersPuddlesResponse) ProtoMessage() {}

func (x *ListMembersPuddlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersPuddlesResponse.ProtoReflect.Descriptor instead.
func (*ListMembersPuddlesResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{11}
}

func (x *ListMembersPuddlesResponse) GetPuddles() []*Puddle {
	if x != nil {
		return x.Puddles
	}
	return nil
}

func (x *ListMembersPuddlesResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMembersPuddlesResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersPuddlesResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMembersPuddlesIntersectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAUUID     string                 `protobuf:"bytes,1,opt,name=userAUUID,proto3" json:"userAUUID,omitempty"`
	UserBUUID     string                 `protobuf:"bytes,2,opt,name=userBUUID,proto3" json:"userBUUID,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersPuddlesIntersectionsRequest) Reset() {
	*x = ListMembersPuddlesIntersectionsRequest{}
	mi := &file_proto_puddle_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersPuddlesIntersectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersPuddlesIntersectionsRequest) ProtoMessage() {}

func (x *ListMembersPuddlesIntersectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersPuddlesIntersectionsRequest.ProtoReflect.Descriptor instead.
func (*ListMembersPuddlesIntersectionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{12}
}

func (x *ListMembersPuddlesIntersectionsRequest) GetUserAUUID() string {
	if x != nil {
		return x.UserAUUID
	}
	return ""
}

func (x *ListMembersPuddlesIntersectionsRequest) GetUserBUUID() string {
	if x != nil {
		return x.UserBUUID
	}
	return ""
}

func (x *ListMembersPuddlesIntersectionsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersPuddlesIntersectionsRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListMembersPuddlesIntersectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puddles       []*Puddle              `protobuf:"bytes,1,rep,name=puddles,proto3" json:"puddles,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersPuddlesIntersectionsResponse) Reset() {
	*x = ListMembersPuddlesIntersectionsResponse{}
	mi := &file_proto_puddle_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersPuddlesIntersectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersPuddlesIntersectionsResponse) ProtoMessage() {}

func (x *ListMembersPuddlesIntersectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersPuddlesIntersectionsResponse.ProtoReflect.Descriptor instead.
func (*ListMembersPuddlesIntersectionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{13}
}

func (x *ListMembersPuddlesIntersectionsResponse) GetPuddles() []*Puddle {
	if x != nil {
		return x.Puddles
	}
	return nil
}

func (x *ListMembersPuddlesIntersectionsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMembersPuddlesIntersectionsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMembersPuddlesIntersectionsResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListAddersAddorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdderUUID     string                 `protobuf:"bytes,1,opt,name=adderUUID,proto3" json:"adderUUID,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,4,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddersAddorsRequest) Reset() {
	*x = ListAddersAddorsRequest{}
	mi := &file_proto_puddle_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddersAddorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddersAddorsRequest) ProtoMessage() {}

func (x *ListAddersAddorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddersAddorsRequest.ProtoReflect.Descriptor instead.
func (*ListAddersAddorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{14}
}

func (x *ListAddersAddorsRequest) GetAdderUUID() string {
	if x != nil {
		return x.AdderUUID
	}
	return ""
}

func (x *ListAddersAddorsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAddersAddorsRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListAddersAddorsRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type ListAddersAddorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddersAddorsResponse) Reset() {
	*x = ListAddersAddorsResponse{}
	mi := &file_proto_puddle_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddersAddorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddersAddorsResponse) ProtoMessage() {}

func (x *ListAddersAddorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddersAddorsResponse.ProtoReflect.Descriptor instead.
func (*ListAddersAddorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{15}
}

func (x *ListAddersAddorsResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListAddersAddorsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAddersAddorsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAddersAddorsResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PuddleMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	MemberUUID    string                 `protobuf:"bytes,2,opt,name=memberUUID,proto3" json:"memberUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuddleMemberRequest) Reset() {
	*x = PuddleMemberRequest{}
	mi := &file_proto_puddle_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuddleMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuddleMemberRequest) ProtoMessage() {}

func (x *PuddleMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuddleMemberRequest.ProtoReflect.Descriptor instead.
func (*PuddleMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{16}
}

func (x *PuddleMemberRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *PuddleMemberRequest) GetMemberUUID() string {
	if x != nil {
		return x.MemberUUID
	}
	return ""
}

type PuddleMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *User                  `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	Adder         *User                  `protobuf:"bytes,2,opt,name=adder,proto3" json:"adder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuddleMemberResponse) Reset() {
	*x = PuddleMemberResponse{}
	mi := &file_proto_puddle_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuddleMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuddleMemberResponse) ProtoMessage() {}

func (x *PuddleMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuddleMemberResponse.ProtoReflect.Descriptor instead.
func (*PuddleMemberResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{17}
}

func (x *PuddleMemberResponse) GetMember() *User {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *PuddleMemberResponse) GetAdder() *User {
	if x != nil {
		return x.Adder
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	MemberUUID    string                 `protobuf:"bytes,2,opt,name=memberUUID,proto3" json:"memberUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_puddle_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveMemberRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *RemoveMemberRequest) GetMemberUUID() string {
	if x != nil {
		return x.MemberUUID
	}
	return ""
}

type AssignModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignModeratorRequest) Reset() {
	*x = AssignModeratorRequest{}
	mi := &file_proto_puddle_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignModeratorRequest) ProtoMessage() {}

func (x *AssignModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignModeratorRequest.ProtoReflect.Descriptor instead.
func (*AssignModeratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{19}
}

func (x *AssignModeratorRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *AssignModeratorRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type IsModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUUID      string                 `protobuf:"bytes,1,opt,name=userUUID,proto3" json:"userUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModeratorRequest) Reset() {
	*x = IsModeratorRequest{}
	mi := &file_proto_puddle_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModeratorRequest) ProtoMessage() {}

func (x *IsModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModeratorRequest.ProtoReflect.Descriptor instead.
func (*IsModeratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{20}
}

func (x *IsModeratorRequest) GetUserUUID() string {
	if x != nil {
		return x.UserUUID
	}
	return ""
}

func (x *IsModeratorRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type IsModeratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Is            bool                   `protobuf:"varint,1,opt,name=is,proto3" json:"is,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsModeratorResponse) Reset() {
	*x = IsModeratorResponse{}
	mi := &file_proto_puddle_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsModeratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsModeratorResponse) ProtoMessage() {}

func (x *IsModeratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsModeratorResponse.ProtoReflect.Descriptor instead.
func (*IsModeratorResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{21}
}

func (x *IsModeratorResponse) GetIs() bool {
	if x != nil {
		return x.Is
	}
	return false
}

type RevokeModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorUUID string                 `protobuf:"bytes,1,opt,name=moderatorUUID,proto3" json:"moderatorUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeModeratorRequest) Reset() {
	*x = RevokeModeratorRequest{}
	mi := &file_proto_puddle_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeModeratorRequest) ProtoMessage() {}

func (x *RevokeModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeModeratorRequest.ProtoReflect.Descriptor instead.
func (*RevokeModeratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{22}
}

func (x *RevokeModeratorRequest) GetModeratorUUID() string {
	if x != nil {
		return x.ModeratorUUID
	}
	return ""
}

func (x *RevokeModeratorRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type AssignorModeratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssignorUUID  string                 `protobuf:"bytes,1,opt,name=assignorUUID,proto3" json:"assignorUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignorModeratorsRequest) Reset() {
	*x = AssignorModeratorsRequest{}
	mi := &file_proto_puddle_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignorModeratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignorModeratorsRequest) ProtoMessage() {}

func (x *AssignorModeratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignorModeratorsRequest.ProtoReflect.Descriptor instead.
func (*AssignorModeratorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{23}
}

func (x *AssignorModeratorsRequest) GetAssignorUUID() string {
	if x != nil {
		return x.AssignorUUID
	}
	return ""
}

func (x *AssignorModeratorsRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *AssignorModeratorsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AssignorModeratorsRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type AssignorModeratorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderators    []*User                `protobuf:"bytes,1,rep,name=moderators,proto3" json:"moderators,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignorModeratorsResponse) Reset() {
	*x = AssignorModeratorsResponse{}
	mi := &file_proto_puddle_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignorModeratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignorModeratorsResponse) ProtoMessage() {}

func (x *AssignorModeratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignorModeratorsResponse.ProtoReflect.Descriptor instead.
func (*AssignorModeratorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{24}
}

func (x *AssignorModeratorsResponse) GetModerators() []*User {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *AssignorModeratorsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AssignorModeratorsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AssignorModeratorsResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Moderator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorUUID string                 `protobuf:"bytes,1,opt,name=moderatorUUID,proto3" json:"moderatorUUID,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	IsModerator   bool                   `protobuf:"varint,4,opt,name=isModerator,proto3" json:"isModerator,omitempty"`
	AssignorUUID  string                 `protobuf:"bytes,5,opt,name=assignorUUID,proto3" json:"assignorUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,8,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	AssignedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=assigned_at,json=assignedAt,proto3" json:"assigned_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Moderator) Reset() {
	*x = Moderator{}
	mi := &file_proto_puddle_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Moderator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Moderator) ProtoMessage() {}

func (x *Moderator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Moderator.ProtoReflect.Descriptor instead.
func (*Moderator) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{25}
}

func (x *Moderator) GetModeratorUUID() string {
	if x != nil {
		return x.ModeratorUUID
	}
	return ""
}

func (x *Moderator) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Moderator) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Moderator) GetIsModerator() bool {
	if x != nil {
		return x.IsModerator
	}
	return false
}

func (x *Moderator) GetAssignorUUID() string {
	if x != nil {
		return x.AssignorUUID
	}
	return ""
}

func (x *Moderator) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

func (x *Moderator) GetAssignedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AssignedAt
	}
	return nil
}

func (x *Moderator) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ModeratorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorUUID string                 `protobuf:"bytes,1,opt,name=moderatorUUID,proto3" json:"moderatorUUID,omitempty"`
	PuddleUUID    string                 `protobuf:"bytes,2,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratorRequest) Reset() {
	*x = ModeratorRequest{}
	mi := &file_proto_puddle_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratorRequest) ProtoMessage() {}

func (x *ModeratorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratorRequest.ProtoReflect.Descriptor instead.
func (*ModeratorRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{26}
}

func (x *ModeratorRequest) GetModeratorUUID() string {
	if x != nil {
		return x.ModeratorUUID
	}
	return ""
}

func (x *ModeratorRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type ModeratorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderator     *Moderator             `protobuf:"bytes,1,opt,name=moderator,proto3" json:"moderator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModeratorResponse) Reset() {
	*x = ModeratorResponse{}
	mi := &file_proto_puddle_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModeratorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModeratorResponse) ProtoMessage() {}

func (x *ModeratorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModeratorResponse.ProtoReflect.Descriptor instead.
func (*ModeratorResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{27}
}

func (x *ModeratorResponse) GetModerator() *Moderator {
	if x != nil {
		return x.Moderator
	}
	return nil
}

type ListAssignorModeratorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuddleUUID    string                 `protobuf:"bytes,1,opt,name=puddleUUID,proto3" json:"puddleUUID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignorModeratorsRequest) Reset() {
	*x = ListAssignorModeratorsRequest{}
	mi := &file_proto_puddle_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignorModeratorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignorModeratorsRequest) ProtoMessage() {}

func (x *ListAssignorModeratorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignorModeratorsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignorModeratorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{28}
}

func (x *ListAssignorModeratorsRequest) GetPuddleUUID() string {
	if x != nil {
		return x.PuddleUUID
	}
	return ""
}

type ListAssignorModeratorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moderators    []*Moderator           `protobuf:"bytes,1,rep,name=moderators,proto3" json:"moderators,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          uint32                 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssignorModeratorsResponse) Reset() {
	*x = ListAssignorModeratorsResponse{}
	mi := &file_proto_puddle_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssignorModeratorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignorModeratorsResponse) ProtoMessage() {}

func (x *ListAssignorModeratorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_puddle_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignorModeratorsResponse.ProtoReflect.Descriptor instead.
func (*ListAssignorModeratorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_puddle_proto_rawDescGZIP(), []int{29}
}

func (x *ListAssignorModeratorsResponse) GetModerators() []*Moderator {
	if x != nil {
		return x.Moderators
	}
	return nil
}

func (x *ListAssignorModeratorsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssignorModeratorsResponse) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssignorModeratorsResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_puddle_proto protoreflect.FileDescriptor

const file_proto_puddle_proto_rawDesc = "" +
	"\n" +
	"\x12proto/puddle.proto\x12\x06puddle\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xec\x02\n" +
	"\x06Puddle\x12\x12\n" +
	"\x04UUID\x18\x01 \x01(\tR\x04UUID\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x123\n" +
	"\vpuddle_type\x18\x04 \x01(\x0e2\x12.puddle.PuddleTypeR\n" +
	"puddleType\x128\n" +
	"\tUpdatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x128\n" +
	"\tCreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x128\n" +
	"\tDeletedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12 \n" +
	"\vmemberCount\x18\b \x01(\x04R\vmemberCountB\x0e\n" +
	"\f_description\"\xb2\x01\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12 \n" +
	"\visModerator\x18\x04 \x01(\bR\visModerator\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"/\n" +
	"\rPuddleRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\"8\n" +
	"\x0ePuddleResponse\x12&\n" +
	"\x06puddle\x18\x01 \x01(\v2\x0e.puddle.PuddleR\x06puddle\"\xc3\x01\n" +
	"\x13CreatePuddleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x123\n" +
	"\vpuddle_type\x18\x03 \x01(\x0e2\x12.puddle.PuddleTypeR\n" +
	"puddleType\x12,\n" +
	"\x11invitedUsersUUIDs\x18\x04 \x03(\tR\x11invitedUsersUUIDsB\x0e\n" +
	"\f_description\"\x8d\x01\n" +
	"\x12PatchPuddleRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_description\"5\n" +
	"\x13DeletePuddleRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\"b\n" +
	"\x18ListPuddleMembersRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"}\n" +
	"\x19ListPuddleMembersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.puddle.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"N\n" +
	"\x10AddMemberRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\"c\n" +
	"\x19ListMembersPuddlesRequest\x12\x1e\n" +
	"\n" +
	"memberUUID\x18\x01 \x01(\tR\n" +
	"memberUUID\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"\x84\x01\n" +
	"\x1aListMembersPuddlesResponse\x12(\n" +
	"\apuddles\x18\x01 \x03(\v2\x0e.puddle.PuddleR\apuddles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\x8c\x01\n" +
	"&ListMembersPuddlesIntersectionsRequest\x12\x1c\n" +
	"\tuserAUUID\x18\x01 \x01(\tR\tuserAUUID\x12\x1c\n" +
	"\tuserBUUID\x18\x02 \x01(\tR\tuserBUUID\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\x91\x01\n" +
	"'ListMembersPuddlesIntersectionsResponse\x12(\n" +
	"\apuddles\x18\x01 \x03(\v2\x0e.puddle.PuddleR\apuddles\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\x7f\n" +
	"\x17ListAddersAddorsRequest\x12\x1c\n" +
	"\tadderUUID\x18\x01 \x01(\tR\tadderUUID\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x04 \x01(\tR\n" +
	"puddleUUID\"|\n" +
	"\x18ListAddersAddorsResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.puddle.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"U\n" +
	"\x13PuddleMemberRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\x12\x1e\n" +
	"\n" +
	"memberUUID\x18\x02 \x01(\tR\n" +
	"memberUUID\"`\n" +
	"\x14PuddleMemberResponse\x12$\n" +
	"\x06member\x18\x01 \x01(\v2\f.puddle.UserR\x06member\x12\"\n" +
	"\x05adder\x18\x02 \x01(\v2\f.puddle.UserR\x05adder\"U\n" +
	"\x13RemoveMemberRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\x12\x1e\n" +
	"\n" +
	"memberUUID\x18\x02 \x01(\tR\n" +
	"memberUUID\"T\n" +
	"\x16AssignModeratorRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\"P\n" +
	"\x12IsModeratorRequest\x12\x1a\n" +
	"\buserUUID\x18\x01 \x01(\tR\buserUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\"%\n" +
	"\x13IsModeratorResponse\x12\x0e\n" +
	"\x02is\x18\x01 \x01(\bR\x02is\"^\n" +
	"\x16RevokeModeratorRequest\x12$\n" +
	"\rmoderatorUUID\x18\x01 \x01(\tR\rmoderatorUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\"\x87\x01\n" +
	"\x19AssignorModeratorsRequest\x12\"\n" +
	"\fassignorUUID\x18\x01 \x01(\tR\fassignorUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\x88\x01\n" +
	"\x1aAssignorModeratorsResponse\x12,\n" +
	"\n" +
	"moderators\x18\x01 \x03(\v2\f.puddle.UserR\n" +
	"moderators\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"\xca\x02\n" +
	"\tModerator\x12$\n" +
	"\rmoderatorUUID\x18\x01 \x01(\tR\rmoderatorUUID\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12 \n" +
	"\visModerator\x18\x04 \x01(\bR\visModerator\x12\"\n" +
	"\fassignorUUID\x18\x05 \x01(\tR\fassignorUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\b \x01(\tR\n" +
	"puddleUUID\x12;\n" +
	"\vassigned_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"assignedAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"X\n" +
	"\x10ModeratorRequest\x12$\n" +
	"\rmoderatorUUID\x18\x01 \x01(\tR\rmoderatorUUID\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x02 \x01(\tR\n" +
	"puddleUUID\"D\n" +
	"\x11ModeratorResponse\x12/\n" +
	"\tmoderator\x18\x01 \x01(\v2\x11.puddle.ModeratorR\tmoderator\"?\n" +
	"\x1dListAssignorModeratorsRequest\x12\x1e\n" +
	"\n" +
	"puddleUUID\x18\x01 \x01(\tR\n" +
	"puddleUUID\"\x91\x01\n" +
	"\x1eListAssignorModeratorsResponse\x121\n" +
	"\n" +
	"moderators\x18\x01 \x03(\v2\x11.puddle.ModeratorR\n" +
	"moderators\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size*C\n" +
	"\n" +
	"PuddleType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GROUP\x10\x01\x12\f\n" +
	"\bONEONONE\x10\x02\x12\v\n" +
	"\aCHANNEL\x10\x032\xf3\x0f\n" +
	"\rPuddleService\x12x\n" +
	"\x0fAssignModerator\x12\x1e.puddle.AssignModeratorRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/v1/puddle/{puddleUUID}/moderators\x12\x80\x01\n" +
	"\vIsModerator\x12\x1a.puddle.IsModeratorRequest\x1a\x1b.puddle.IsModeratorResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/puddle/{puddleUUID}/moderators/{userUUID}/is\x12\x88\x01\n" +
	"\x0fRevokeModerator\x12\x1e.puddle.RevokeModeratorRequest\x1a\x16.google.protobuf.Empty\"=\x82\xd3\xe4\x93\x027:\x01*\"2/v1/puddle/{puddleUUID}/moderators/{moderatorUUID}\x12\x93\x01\n" +
	"\x16ListAssignorModerators\x12%.puddle.ListAssignorModeratorsRequest\x1a&.puddle.ListAssignorModeratorsResponse\"*\x82\xd3\xe4\x93\x02$\x12\"/v1/puddle/{puddleUUID}/moderators\x12|\n" +
	"\tModerator\x12\x18.puddle.ModeratorRequest\x1a\x19.puddle.ModeratorResponse\":\x82\xd3\xe4\x93\x024\x122/v1/puddle/{puddleUUID}/moderators/{moderatorUUID}\x12i\n" +
	"\tAddMember\x12\x18.puddle.AddMemberRequest\x1a\x16.google.protobuf.Empty\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/puddle/{puddleUUID}/members\x12\x84\x01\n" +
	"\x12ListMembersPuddles\x12!.puddle.ListMembersPuddlesRequest\x1a\".puddle.ListMembersPuddlesResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/puddle/{memberUUID}/puddles\x12\xbc\x01\n" +
	"\x1fListMembersPuddlesIntersections\x12..puddle.ListMembersPuddlesIntersectionsRequest\x1a/.puddle.ListMembersPuddlesIntersectionsResponse\"8\x82\xd3\xe4\x93\x022\x120/v1/puddle/intersections/{userAUUID}/{userBUUID}\x12\x91\x01\n" +
	"\x10ListAddersAddors\x12\x1f.puddle.ListAddersAddorsRequest\x1a .puddle.ListAddersAddorsResponse\":\x82\xd3\xe4\x93\x024\x122/v1/puddle/{puddleUUID}/members/{adderUUID}/addors\x12\x7f\n" +
	"\fPuddleMember\x12\x1b.puddle.PuddleMemberRequest\x1a\x1c.puddle.PuddleMemberResponse\"4\x82\xd3\xe4\x93\x02.\x12,/v1/puddle/{puddleUUID}/members/{memberUUID}\x12y\n" +
	"\fRemoveMember\x12\x1b.puddle.RemoveMemberRequest\x1a\x16.google.protobuf.Empty\"4\x82\xd3\xe4\x93\x02.*,/v1/puddle/{puddleUUID}/members/{memberUUID}\x12X\n" +
	"\x06Puddle\x12\x15.puddle.PuddleRequest\x1a\x16.puddle.PuddleResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/puddle/{puddleUUID}\x12Z\n" +
	"\fCreatePuddle\x12\x1b.puddle.CreatePuddleRequest\x1a\x16.google.protobuf.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/puddle\x12e\n" +
	"\vPatchPuddle\x12\x1a.puddle.PatchPuddleRequest\x1a\x16.google.protobuf.Empty\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*2\x17/v1/puddle/{puddleUUID}\x12d\n" +
	"\fDeletePuddle\x12\x1b.puddle.DeletePuddleRequest\x1a\x16.google.protobuf.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19*\x17/v1/puddle/{puddleUUID}\x12\x81\x01\n" +
	"\x11ListPuddleMembers\x12 .puddle.ListPuddleMembersRequest\x1a!.puddle.ListPuddleMembersResponse\"'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/puddle/{puddleUUID}/membersB\x04Z\x02./b\x06proto3"

var (
	file_proto_puddle_proto_rawDescOnce sync.Once
	file_proto_puddle_proto_rawDescData []byte
)

func file_proto_puddle_proto_rawDescGZIP() []byte {
	file_proto_puddle_proto_rawDescOnce.Do(func() {
		file_proto_puddle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_puddle_proto_rawDesc), len(file_proto_puddle_proto_rawDesc)))
	})
	return file_proto_puddle_proto_rawDescData
}

var file_proto_puddle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_puddle_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_puddle_proto_goTypes = []any{
	(PuddleType)(0),                                 // 0: puddle.PuddleType
	(*Puddle)(nil),                                  // 1: puddle.Puddle
	(*User)(nil),                                    // 2: puddle.User
	(*PuddleRequest)(nil),                           // 3: puddle.PuddleRequest
	(*PuddleResponse)(nil),                          // 4: puddle.PuddleResponse
	(*CreatePuddleRequest)(nil),                     // 5: puddle.CreatePuddleRequest
	(*PatchPuddleRequest)(nil),                      // 6: puddle.PatchPuddleRequest
	(*DeletePuddleRequest)(nil),                     // 7: puddle.DeletePuddleRequest
	(*ListPuddleMembersRequest)(nil),                // 8: puddle.ListPuddleMembersRequest
	(*ListPuddleMembersResponse)(nil),               // 9: puddle.ListPuddleMembersResponse
	(*AddMemberRequest)(nil),                        // 10: puddle.AddMemberRequest
	(*ListMembersPuddlesRequest)(nil),               // 11: puddle.ListMembersPuddlesRequest
	(*ListMembersPuddlesResponse)(nil),              // 12: puddle.ListMembersPuddlesResponse
	(*ListMembersPuddlesIntersectionsRequest)(nil),  // 13: puddle.ListMembersPuddlesIntersectionsRequest
	(*ListMembersPuddlesIntersectionsResponse)(nil), // 14: puddle.ListMembersPuddlesIntersectionsResponse
	(*ListAddersAddorsRequest)(nil),                 // 15: puddle.ListAddersAddorsRequest
	(*ListAddersAddorsResponse)(nil),                // 16: puddle.ListAddersAddorsResponse
	(*PuddleMemberRequest)(nil),                     // 17: puddle.PuddleMemberRequest
	(*PuddleMemberResponse)(nil),                    // 18: puddle.PuddleMemberResponse
	(*RemoveMemberRequest)(nil),                     // 19: puddle.RemoveMemberRequest
	(*AssignModeratorRequest)(nil),                  // 20: puddle.AssignModeratorRequest
	(*IsModeratorRequest)(nil),                      // 21: puddle.IsModeratorRequest
	(*IsModeratorResponse)(nil),                     // 22: puddle.IsModeratorResponse
	(*RevokeModeratorRequest)(nil),                  // 23: puddle.RevokeModeratorRequest
	(*AssignorModeratorsRequest)(nil),               // 24: puddle.AssignorModeratorsRequest
	(*AssignorModeratorsResponse)(nil),              // 25: puddle.AssignorModeratorsResponse
	(*Moderator)(nil),                               // 26: puddle.Moderator
	(*ModeratorRequest)(nil),                        // 27: puddle.ModeratorRequest
	(*ModeratorResponse)(nil),                       // 28: puddle.ModeratorResponse
	(*ListAssignorModeratorsRequest)(nil),           // 29: puddle.ListAssignorModeratorsRequest
	(*ListAssignorModeratorsResponse)(nil),          // 30: puddle.ListAssignorModeratorsResponse
	(*timestamppb.Timestamp)(nil),                   // 31: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                           // 32: google.protobuf.Empty
}
var file_proto_puddle_proto_depIdxs = []int32{
	0,  // 0: puddle.Puddle.puddle_type:type_name -> puddle.PuddleType
	31, // 1: puddle.Puddle.UpdatedAt:type_name -> google.protobuf.Timestamp
	31, // 2: puddle.Puddle.CreatedAt:type_name -> google.protobuf.Timestamp
	31, // 3: puddle.Puddle.DeletedAt:type_name -> google.protobuf.Timestamp
	31, // 4: puddle.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 5: puddle.PuddleResponse.puddle:type_name -> puddle.Puddle
	0,  // 6: puddle.CreatePuddleRequest.puddle_type:type_name -> puddle.PuddleType
	2,  // 7: puddle.ListPuddleMembersResponse.users:type_name -> puddle.User
	1,  // 8: puddle.ListMembersPuddlesResponse.puddles:type_name -> puddle.Puddle
	1,  // 9: puddle.ListMembersPuddlesIntersectionsResponse.puddles:type_name -> puddle.Puddle
	2,  // 10: puddle.ListAddersAddorsResponse.users:type_name -> puddle.User
	2,  // 11: puddle.PuddleMemberResponse.member:type_name -> puddle.User
	2,  // 12: puddle.PuddleMemberResponse.adder:type_name -> puddle.User
	2,  // 13: puddle.AssignorModeratorsResponse.moderators:type_name -> puddle.User
	31, // 14: puddle.Moderator.assigned_at:type_name -> google.protobuf.Timestamp
	31, // 15: puddle.Moderator.created_at:type_name -> google.protobuf.Timestamp
	26, // 16: puddle.ModeratorResponse.moderator:type_name -> puddle.Moderator
	26, // 17: puddle.ListAssignorModeratorsResponse.moderators:type_name -> puddle.Moderator
	20, // 18: puddle.PuddleService.AssignModerator:input_type -> puddle.AssignModeratorRequest
	21, // 19: puddle.PuddleService.IsModerator:input_type -> puddle.IsModeratorRequest
	23, // 20: puddle.PuddleService.RevokeModerator:input_type -> puddle.RevokeModeratorRequest
	29, // 21: puddle.PuddleService.ListAssignorModerators:input_type -> puddle.ListAssignorModeratorsRequest
	27, // 22: puddle.PuddleService.Moderator:input_type -> puddle.ModeratorRequest
	10, // 23: puddle.PuddleService.AddMember:input_type -> puddle.AddMemberRequest
	11, // 24: puddle.PuddleService.ListMembersPuddles:input_type -> puddle.ListMembersPuddlesRequest
	13, // 25: puddle.PuddleService.ListMembersPuddlesIntersections:input_type -> puddle.ListMembersPuddlesIntersectionsRequest
	15, // 26: puddle.PuddleService.ListAddersAddors:input_type -> puddle.ListAddersAddorsRequest
	17, // 27: puddle.PuddleService.PuddleMember:input_type -> puddle.PuddleMemberRequest
	19, // 28: puddle.PuddleService.RemoveMember:input_type -> puddle.RemoveMemberRequest
	3,  // 29: puddle.PuddleService.Puddle:input_type -> puddle.PuddleRequest
	5,  // 30: puddle.PuddleService.CreatePuddle:input_type -> puddle.CreatePuddleRequest
	6,  // 31: puddle.PuddleService.PatchPuddle:input_type -> puddle.PatchPuddleRequest
	7,  // 32: puddle.PuddleService.DeletePuddle:input_type -> puddle.DeletePuddleRequest
	8,  // 33: puddle.PuddleService.ListPuddleMembers:input_type -> puddle.ListPuddleMembersRequest
	32, // 34: puddle.PuddleService.AssignModerator:output_type -> google.protobuf.Empty
	22, // 35: puddle.PuddleService.IsModerator:output_type -> puddle.IsModeratorResponse
	32, // 36: puddle.PuddleService.RevokeModerator:output_type -> google.protobuf.Empty
	30, // 37: puddle.PuddleService.ListAssignorModerators:output_type -> puddle.ListAssignorModeratorsResponse
	28, // 38: puddle.PuddleService.Moderator:output_type -> puddle.ModeratorResponse
	32, // 39: puddle.PuddleService.AddMember:output_type -> google.protobuf.Empty
	12, // 40: puddle.PuddleService.ListMembersPuddles:output_type -> puddle.ListMembersPuddlesResponse
	14, // 41: puddle.PuddleService.ListMembersPuddlesIntersections:output_type -> puddle.ListMembersPuddlesIntersectionsResponse
	16, // 42: puddle.PuddleService.ListAddersAddors:output_type -> puddle.ListAddersAddorsResponse
	18, // 43: puddle.PuddleService.PuddleMember:output_type -> puddle.PuddleMemberResponse
	32, // 44: puddle.PuddleService.RemoveMember:output_type -> google.protobuf.Empty
	4,  // 45: puddle.PuddleService.Puddle:output_type -> puddle.PuddleResponse
	32, // 46: puddle.PuddleService.CreatePuddle:output_type -> google.protobuf.Empty
	32, // 47: puddle.PuddleService.PatchPuddle:output_type -> google.protobuf.Empty
	32, // 48: puddle.PuddleService.DeletePuddle:output_type -> google.protobuf.Empty
	9,  // 49: puddle.PuddleService.ListPuddleMembers:output_type -> puddle.ListPuddleMembersResponse
	34, // [34:50] is the sub-list for method output_type
	18, // [18:34] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_puddle_proto_init() }
func file_proto_puddle_proto_init() {
	if File_proto_puddle_proto != nil {
		return
	}
	file_proto_puddle_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_puddle_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_puddle_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_puddle_proto_rawDesc), len(file_proto_puddle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_puddle_proto_goTypes,
		DependencyIndexes: file_proto_puddle_proto_depIdxs,
		EnumInfos:         file_proto_puddle_proto_enumTypes,
		MessageInfos:      file_proto_puddle_proto_msgTypes,
	}.Build()
	File_proto_puddle_proto = out.File
	file_proto_puddle_proto_goTypes = nil
	file_proto_puddle_proto_depIdxs = nil
}
