syntax = "proto3";

package identity;

import "google/api/annotations.proto";

option go_package = "./";

enum Role {
    USER = 0;
    ADMIN = 1;
}

message TokenRequest {
    string uuid = 1;
}

message Token {
    string token = 1;
}

message TokenPayload {
    string uuid = 1;
    string role = 2;
}

service IdentityService {
    rpc RemintToken(Token) returns (Token);
    rpc ValidateToken(Token) returns (TokenPayload);
    rpc Login(LoginRequest) returns (Token){
        option (google.api.http) = {
            post: "/v1/identity/login"
        };
    };
    rpc Register(RegisterRequest) returns (Token){
        option (google.api.http) = {
            post: "/v1/identity/register"
        };
    };
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message RegisterRequest {
    string email = 1;
    string password = 2;
    string nickname = 3;
}