syntax = "proto3";

package identity;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

option go_package = "./";

enum Role {
    USER = 0;
    ADMIN = 1;
}

message TokenRequest {
    string uuid = 1;
}

message Token {
    string token = 1;
}

message TokenPayload {
    string uuid = 1;
    string role = 2;
}

service IdentityService {
    rpc RemintToken(Token) returns (Token);
    rpc ValidateToken(Token) returns (TokenPayload){
        option (google.api.http) = {
            get: "/v1/public/validate/{token}"
        };
    };
    rpc Login(LoginRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/public/login"
            body: "*"
        };
    };
    rpc Register(RegisterRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/public/register"
            body: "*"
        };
    };
}

message LoginRequest {
    string email = 1;
    string password = 2;
}

message RegisterRequest {
    string email = 1;
    string password = 2;
    string nickname = 3;
}