syntax = "proto3";

package news;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";

option go_package = "./";

message GenerateUploadURLSsRequest {
    reserved 1;
    repeated ImageMeta images = 2;
}

message ImageMeta {
    string file_name = 1;
    string mime = 2;
}
message UploadTarget {
    string upload_url = 1;
    string file_key = 2;
}

message GenerateNewUploadURLsResponse {
    repeated UploadTarget targets = 1;
}

message CreateNewRequest {
    reserved 1;
    string caption = 2;
    optional string body_key = 3;
    repeated string image_keys = 4;
}

message New {
    string new_id = 1;
    string user_id = 2;
    string caption = 3;
    optional string body_url = 4;
    repeated string image_urls = 5;
    google.protobuf.Timestamp created_at = 6;
}

message CreateNewResponse {
    New new = 1;
}

message GetNewRequest {
    string new_id = 1;
}

message GetNewResponse {
    New new = 1;
}

message ListNewsRequest {
    uint32 page = 1;
    uint32 size = 2;
}

message ListNewsResponse {
    repeated New news = 1;
    uint32 page = 2;
    uint32 size = 3;
    uint64 total = 4;
}

message GenerateBodyUploadURLRequest {
    string body_name = 1; //first 16 chars
}

message GenerateBodyUploadURLResponse {
    UploadTarget target = 1;
}

service NewsService {
    rpc GenerateBodyUploadURL(GenerateBodyUploadURLRequest) returns (GenerateBodyUploadURLResponse){
        option (google.api.http) = {
            post: "/v1/news/body"
            body: "*"
        };
    };
    rpc GenerateNewUploadURLs(GenerateUploadURLSsRequest) returns (GenerateNewUploadURLsResponse){
        option (google.api.http) = {
            post: "/v1/news/images"
            body: "*"
        };
    };
    rpc CreateNew(CreateNewRequest) returns (CreateNewResponse){
        option (google.api.http) = {
            post: "/v1/news"
            body: "*"
        };
    };
    rpc GetNew(GetNewRequest) returns (GetNewResponse){
        option (google.api.http) = {
            get: "/v1/news/{new_id}"
        };
    };
    rpc ListNews(ListNewsRequest) returns (ListNewsResponse){
        option (google.api.http) = {
            get: "/v1/news"
        };
    };
}