syntax = "proto3";

package RBAC;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

option go_package = "./";

enum Verb {
    UNDEFINED = 0;
    GET       = 1;
	POST      = 2;
	PUT       = 3;
    PATCH     = 4;
	DELETE    = 5;
}

message HasPermissionQuestion {
    string user_UUID = 1;
    string scope = 2;
    optional string subScope = 3;
    Verb verb = 4;
}

message HasPermissionAnswer {
    bool has = 1;
}


message DeleteRoleRequest {
    string role_UUID = 1;
}


message Action {
    string scope = 1;
    optional string sub_scope = 2;
    Verb verb = 3;
}


message CreateRoleRequest {
    string name = 1;
    optional string description = 2;
    optional string extended_UUID = 3;
    int32 priority = 4;

    repeated Action actions = 5;
} 


message AssignorsAssigneesRequest {
    string assignor_UUID = 1;
}

message AssignorsAssigneesResponse {
    repeated string assignee_UUIDs = 1;
}


message RoleAssignorRequest {
    string assignee_UUID = 1;
    string role_UUID = 2;
}

message RoleAssignorResponse {
    string assignor_UUID = 1;
}


message RoleAssigneesRequest {
    string role_UUID = 1;
}

message RoleAssigneesResponse {
    repeated string user_UUIDs = 1;
}


message AssignRoleRequest {
    string assignee_UUID = 1;
    string role_UUID = 2;
    optional google.protobuf.Timestamp expires_at = 3;
}

message PatchRoleRequest {
    string role_UUID = 1;
    optional string name = 2;
    optional string description = 3;
    optional string extended_UUID = 4;
    optional int32  priority = 5;
}


message RoleRequest {
    string role_UUID = 1;
}

message RoleResponse {
    string role_UUID = 1;
    string name = 2;
    optional string description = 3;
    optional string extended_UUID = 4;

    int32  priority = 5;

    google.protobuf.Timestamp created_at = 6;
    optional google.protobuf.Timestamp deleted_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}

message ListRolesRequest {
    int32 page = 1;
    int32 size = 2;
}

message ListRolesResponse {
    message Role {
        string role_UUID = 1;
        string name = 2;
        optional string description = 3;
        optional string extended_UUID = 4;

        int32  priority = 5;

        google.protobuf.Timestamp created_at = 6;
        optional google.protobuf.Timestamp deleted_at = 7;
        google.protobuf.Timestamp updated_at = 8;
    }

    repeated Role roles = 1;
    int32 page = 2;
    int32 size = 3;
    int64 total = 4;
}

service RBACService {
    rpc HasPermission(HasPermissionQuestion) returns (HasPermissionAnswer);
    
    rpc DeleteRole(DeleteRoleRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/RBAC/roles/{role_UUID}"
        };
    }; 
    rpc Role(RoleRequest) returns (RoleResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/roles/{role_UUID}"
        };
    };
    rpc PatchRole(PatchRoleRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/RBAC/roles/{role_UUID}"
            body: "*"
        };
    };
    rpc CreateRole(CreateRoleRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/RBAC/roles"
            body: "*"
        };
    };
    rpc ListRoles(ListRolesRequest) returns (ListRolesResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/roles"
        };
    };

    rpc AssignorsAssignees(AssignorsAssigneesRequest) returns (AssignorsAssigneesResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/assignors/{assignor_UUID}"
        };
    };
    rpc RoleAssignor(RoleAssignorRequest) returns (RoleAssignorResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/assignees/{assignee_UUID}/{role_UUID}"
        };
    };
    rpc RoleAssignees(RoleAssigneesRequest) returns (RoleAssigneesResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/roles/{role_UUID}/assignees"
        };
    };
    rpc AssignRole(AssignRoleRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/RBAC/roles/{role_UUID}/assignees/{assignee_UUID}"
        };
    };


    rpc AddActions(AddActionsRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/RBAC/roles/{role_UUID}/actions"
            body: "*"
        };
    };
    rpc RevokeActions(RevokeActionsRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/RBAC/roles/{role_UUID}/actions"
        };
    };
    rpc ListActions(ListActionsRequest) returns (ListActionsResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/actions"
        };
    };
    rpc ActionsByRole(ActionsByRoleRequest) returns (ActionsByRoleResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/roles/{role_UUID}/actions"
        };
    };
    rpc Action(ActionRequest) returns (ActionResponse){
        option (google.api.http) = {
            get: "/v1/RBAC/actions/{action_UUID}"
        };
    };
}

message AddActionsRequest {
    repeated string action_UUIDs = 1;
    string role_UUID = 2;
}

message RevokeActionsRequest {
    repeated string action_UUIDs = 1;
    string role_UUID = 2;
}

message ListActionsRequest {
    int32 page = 1;
    int32 size = 2;
}

message ListActionsResponse {
    repeated Action action = 1;
    int32 page = 2;
    int32 size = 3;
    int64 total = 4;
}

message ActionsByRoleRequest {
    string role_UUID = 1;
}

message ActionsByRoleResponse {
    repeated Action actions = 1;
}

message ActionRequest {
    string action_UUID = 1;
}

message ActionResponse {
    Action action = 1;
}