syntax = "proto3";

package timetable;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

option go_package = "./";

enum Day {
    UNSPECIFIED = 0;
    MONDAY = 1;
    TUESDAY = 2;
    WEDNESDAY = 3;
    THURSDAY = 4;
    FRIDAY = 5;
    SATURDAY = 6;
    SUNDAY = 7;
}

message ListTimetablesRequest {
    uint32 week_number = 1;
    string group_uuid = 2;
}

message GetTimetableRequest {
    uint32 week_number = 1;
    string group_uuid = 2;
    Day day = 3;
}

message GetTimetableResponse {
    ConcreteLessonShortEntry Timetable = 1;
}

message AbstractLesson {
    string uuid = 1;
    string name = 2;
}

message ConcreteLesson {
    google.protobuf.Timestamp start = 1;
    google.protobuf.Timestamp end = 2;
    AbstractLesson lesson_info = 3;
    string teacher_uuid = 4;
    optional string homework_text_get_url= 5;
    repeated string homework_attachments_get_urls = 6;
    string lesson_uuid = 7;
    repeated string marks = 8; //5- итд
    uint32 period = 9;
}

message ShortConcreteLesson {
    optional google.protobuf.Timestamp start = 1;
    optional google.protobuf.Timestamp end = 2;
    optional uint32 period = 3;
    AbstractLesson abstract_lesson = 4;
    bool is_homework_due = 5;
}

message ConcreteLessonShortEntry {
    Day day = 1;
    repeated ShortConcreteLesson lessons = 2;
}


message ListTimetableResponse {
    repeated ConcreteLessonShortEntry Timetable = 1;
}

message CreateAbstractLessonRequest {
    string name = 1;
}

message Period {
    uint32 number = 1;
    google.protobuf.Timestamp start = 2;
    google.protobuf.Timestamp end = 3;
}

message GetPeriodRequest {
    uint32 week_number = 1;
}

message GetPeriodsResponse {
    repeated Period periods = 1;
}

message PatchPeriodsRequest {
    repeated Period periods = 1;
}

message DeleteAbstractLessonRequest {
    string lesson_uuid = 1;
}

message GetAbstractLessonRequest {
    string lesson_uuid = 1;
}

message GetAbstractLessonResponse {
    AbstractLesson lesson = 1;
}

message PatchAbstractLessonRequest {
    string lesson_uuid = 1;
    optional string name = 2; //и такое бывает
}

message ListAbstractLessonsRequest {
    uint64 size = 1;
    uint64 page = 2;
}

message ListAbstractLessonsResponse {
    uint64 size = 1;
    uint64 page = 2;
    uint64 total = 3;
    repeated AbstractLesson abstract_lessons = 4;
}

message CreateConcreteLessonRequest {
    string abstract_lesson_uuid = 1;
    string teacher_uuid = 2;
    google.protobuf.Timestamp start = 3;
    google.protobuf.Timestamp end = 4;
    string group_uuid = 5;
    uint32 period = 6;
}

message DeleteConcreteLessonRequest {
    string concrete_lesson_uuid = 1;
}

message PatchConcreteLessonRequest {
    optional google.protobuf.Timestamp start = 1;
    optional google.protobuf.Timestamp end = 2;
    optional string abstract_lesson_uuid = 3;
    optional string teacher_uuid = 4;
    string concrete_lesson_uuid = 5;
    string group_uuid = 6;
}

message GetConcreteLessonRequest {
    string concrete_lesson_uuid = 1;
}

message GetConcreteLessonResponse {
    ConcreteLesson lesson = 1;
}

message HomeworkBodyPUTUrlRequest {
    string concrete_lesson_uuid = 1;
}

message HomeworkBodyPUTUrlResponse {
    string homework_body_url = 1;
}

message HomeworkAttachmentPUTUrlRequest {
    string concrete_lesson_uuid = 1;
}

message HomeworkAttachmentPUTUrlResponse {
    repeated string homework_attachment_urls = 1;
}

message HomeworkAttachmentGETUrlRequest {
    string concrete_lesson_uuid = 1;
}

message HomeworkAttachmentGETUrlResponse {
    repeated string homework_attachment_urls = 1;
}

message HomeworkBodyGETUrlRequest {
    string concrete_lesson_uuid = 1;
}

message HomeworkBodyGETUrlResponse {
    string homework_body_uuid = 1;
}

service TimetableService {
    rpc ListTimetable(ListTimetablesRequest) returns (ListTimetableResponse){
        option (google.api.http) = {
            get: "/v1/timetable/{group_uuid}/{week_number}"
        };
    };
    rpc GetTimetable(GetTimetableRequest) returns (GetTimetableResponse){
        option (google.api.http) = {
            get: "/v1/timetable/{group_uuid}/{week_number}/{day}"
        };
    };


    rpc CreateAbstractLesson(CreateAbstractLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/lesson/abstract"
            body: "*"
        };
    };
    rpc DeleteAbstractLesson(DeleteAbstractLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/lesson/abstract/{lesson_uuid}"
        };
    };
    rpc GetAbstractLesson(GetAbstractLessonRequest) returns (GetAbstractLessonResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/abstract/{lesson_uuid}"
        };
    };
    rpc PatchAbstractLesson(PatchAbstractLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/lesson/abstract/{lesson_uuid}"
            body: "*"
        };
    };
    rpc ListAbstractLessons(ListAbstractLessonsRequest) returns (ListAbstractLessonsResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/abstract"
        };
    };


    rpc CreateConcreteLesson(CreateConcreteLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/lesson/concrete"
            body: "*"
        };
    };
    rpc DeleteConcreteLesson(DeleteConcreteLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}"
        };
    };
    rpc PatchConcreteLesson(PatchConcreteLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}"
        };
    };
    rpc GetConcreteLesson(GetConcreteLessonRequest) returns (GetConcreteLessonResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}"
        };
    };


    rpc GetPeriods(GetPeriodRequest) returns (GetPeriodsResponse) {
        option (google.api.http) = {
            get: "/v1/timetable/periods"
        };
    };
    rpc PatchPeriods(PatchPeriodsRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/periods"
            body: "*"
        };
    };


    rpc HomeworkBodyPUTUrl(HomeworkBodyPUTUrlRequest) returns (HomeworkBodyPUTUrlResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/homework/upload"
        };
    };
    rpc HomeworkBodyGETUrl(HomeworkBodyGETUrlRequest) returns (HomeworkBodyGETUrlResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/homework"
        };
    };


    rpc HomeworkAttachmentPUTUrl(HomeworkAttachmentPUTUrlRequest) returns (HomeworkAttachmentPUTUrlResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/attachments/upload"
        };
    };
    rpc HomeworkAttachmentGETUrl(HomeworkAttachmentGETUrlRequest) returns (HomeworkAttachmentGETUrlResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/concrete/{concrete_lesson_uuid}/attachments"
        };
    };
}