syntax = "proto3";

package timetable;

import "google/protobuf/timestamp.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";

option go_package = "./";

message PeriodRequest {
    string periodUUID = 1;
}

message Period {
    string UUID = 1;
    string name = 2;
    int32 position = 3;
    google.protobuf.Timestamp start_time = 4;
    google.protobuf.Timestamp end_time = 5;

    google.protobuf.Timestamp updated_at = 6;
    optional google.protobuf.Timestamp deleted_at = 7;
    google.protobuf.Timestamp created_at = 8;
}

message PeriodResponse {
    Period period = 1;
}

message CreatePeriodRequest {
    string name = 2;
    int32 position = 3;
    google.protobuf.Timestamp start_time = 4;
    google.protobuf.Timestamp end_time = 5;
}

message PatchPeriodRequest {
    string periodUUID = 1;
    optional string name = 2;
    optional int32 position = 3;
    optional google.protobuf.Timestamp start_time = 4;
    optional google.protobuf.Timestamp end_time = 5;
}

message DeletePeriodRequest {
    string periodUUID = 1;
}

message ListPeriodsRequest {
    uint32 page = 1;
    uint32 size = 2;
}

message ListPeriodsResponse {
    uint32 page = 1;
    uint32 size = 2;
    uint64 total = 3;
    repeated Period periods = 4;
}

message Subject {
    string UUID = 1;
    optional string name = 2;
    optional int32 position = 3;

    google.protobuf.Timestamp updated_at = 4;
    optional google.protobuf.Timestamp deleted_at = 5;
    google.protobuf.Timestamp created_at = 6;
}

message SubjectRequest {
    string subjectUUID = 1;
}

message SubjectResponse {
    Subject subject = 1;
}

message CreateSubjectRequest {
    string name = 1;
}

message PatchSubjectRequest {
    string subjectUUID = 1;
    optional string name = 2;
}

message DeleteSubjectRequest {
    string subjectUUID = 1;
}

message ListSubjectsRequest {
    uint32 page = 1;
    uint32 size = 2;
}

message ListSubjectsResponse {
    uint32 page = 1;
    uint32 size = 2;
    uint64 total = 3;
    repeated Subject subjects = 4;
}

message Timetable {
    string UUID = 1;
    string groupUUID = 2;
    string name = 3;
    google.protobuf.Timestamp assign_at = 4;
    google.protobuf.Timestamp revoke_at = 5; 
}

message TimetableByDateRequest {
    string date = 1;
}

message TimetableByDateResponse {
    Timetable timetable = 1;
}

message TimetableRequest {
    string timetableUUID = 1;
}

message TimetableResponse {
    Timetable timetable = 1;
}

message CreateTimetableRequest {
    string groupUUID = 2;
    string name = 3;
    google.protobuf.Timestamp assign_at = 4;
    google.protobuf.Timestamp revoke_at = 5;
}

message PatchTimetableRequest {
    string timetableUUID = 1;
    optional string GroupUUID = 2;
    optional string Name = 3;
    optional google.protobuf.Timestamp assign_at = 4;
    optional google.protobuf.Timestamp revoke_at = 5; 
}

message DeleteTimetableRequest {
    string timetableUUID = 1;
}

message ListTimetablesRequest {
    uint32 page = 1;
    uint32 size = 2;
}

message ListTimetablesResponse {
    uint32 page = 1;
    uint32 size = 2;
    uint64 total = 3;
    repeated Timetable timetables = 4;
}

message CurrentTimetableRequest {}

message CurrentTimetableResponse {
    Timetable timetable = 1;
}

message Lesson {
    string UUID = 1;
    string timetable_entryUUID = 2;
    google.protobuf.Timestamp date = 3;
    bool cancelled = 4;

    google.protobuf.Timestamp created_at = 5;
}

message LessonRequest {
    string lessonUUID = 1;
}

message LessonResponse {
    Lesson lesson = 1;
}

message CreateLessonRequest {
    string timetable_entryUUID = 2;
    google.protobuf.Timestamp date = 3;
}

message PatchLessonRequest {
    string lessonUUID = 1;
    optional string timetable_entryUUID = 2;
    optional google.protobuf.Timestamp date = 3;
    optional bool cancelled = 4;
}

message DeleteLessonRequest {
    string lessonUUID = 1;
}

message ListLessonsRequest {
    string timetableUUID = 1;
}

message ListLessonsResponse {
    repeated Lesson lessons = 1;
}

enum DayOfWeek {
  DAY_OF_WEEK_UNSPECIFIED = 0;
  MONDAY = 1;
  TUESDAY = 2;
  WEDNESDAY = 3;
  THURSDAY = 4;
  FRIDAY = 5;
  SATURDAY = 6;
  SUNDAY = 7;
}


message TimetableEntry {
    string UUID = 1;
    string timetableUUID = 2;
    string periodUUID = 3;
    string subjectUUID = 4;
    optional string teacherUUID = 5;
    
    string place = 6;
    DayOfWeek day_of_week = 7;
    
    google.protobuf.Timestamp updated_at = 8;
    optional google.protobuf.Timestamp deleted_at = 9;
    google.protobuf.Timestamp created_at = 10;
}

message TimetableEntryRequest {
    string timetable_entryUUID = 1;
}

message TimetableEntryResponse {
    TimetableEntry timetable_entry = 1;
}

message TimetableEntriesByTimetableRequest {
    string timetableUUID = 1;
}

message TimetableEntriesByTimetableResponse {
    repeated TimetableEntry timetable_entries = 1;
}

message CreateTimetableEntryRequest {
    string timetableUUID = 2;
    string periodUUID = 3;
    string subjectUUID = 4;
    optional string teacherUUID = 5;
    
    string place = 6;
    DayOfWeek day_of_week = 7;
}

message PatchTimetableEntryRequest {
    string timetable_entryUUID = 1;
    optional string timetableUUID = 2;
    optional string periodUUID = 3;
    optional string subjectUUID = 4;
    optional string teacherUUID = 5;
    
    optional string place = 6;
    DayOfWeek day_of_week = 7;
}

message DeleteTimetableEntryRequest {
    string timetable_entryUUID = 1;
}

message HomeworkAttachment {
    string UUID = 1;
    string lessonUUID = 2;
    string storage_key = 3;

    google.protobuf.Timestamp created_at = 4;
}

message HomeworkAttachmentRequest {
    string homework_attachmentUUID = 1;
}

message HomeworkAttachmentResponse {
    HomeworkAttachment homeworkAttachment = 1;
}

message HomeworkAttachmentByLessonRequest {
    string lessonUUID = 1;
}

message HomeworkAttachmentByLessonResponse {
    repeated HomeworkAttachment homeworkAttachments = 1;
}

message AttachHomeworkRequest {
    string name = 1;
    string mime = 2;
    string lessonUUID = 3;
}

message AttachHomeworkResponse {
    string upload_url = 1;
    string file_key = 2;
}

message DetachHomeworkRequest {
    string homework_attachmentUUID = 1;
}

service TimetableService {

    rpc HomeworkAttachment(HomeworkAttachmentRequest) returns (HomeworkAttachmentResponse){
        option (google.api.http) = {
            get: "/v1/timetable/homework/{homework_attachmentUUID}"
        };
    };
    rpc HomeworkAttachmentByLesson(HomeworkAttachmentByLessonRequest) returns (HomeworkAttachmentByLessonResponse){
        option (google.api.http) = {
            get: "/v1/timetable/homework/lesson/{lessonUUID}"
        };
    };
    rpc AttachHomework(AttachHomeworkRequest) returns (AttachHomeworkResponse){
        option (google.api.http) = {
            post: "/v1/timetable/homework"
            body: "*"
        };
    };
    rpc DetachHomework(DetachHomeworkRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/homework/{homework_attachmentUUID}"
        };
    };

    rpc TimetableEntry(TimetableEntryRequest) returns (TimetableEntryResponse){
        option (google.api.http) = {
            get: "/v1/timetable/entry/{timetable_entryUUID}"
        };
    };
    rpc CreateTimetableEntry(CreateTimetableEntryRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/entry"
            body: "*"
        };
    };
    rpc PatchTimetableEntry(PatchTimetableEntryRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/entry/{timetable_entryUUID}"
            body: "*"
        };
    };
    rpc DeleteTimetableEntry(DeleteTimetableEntryRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/entry/{timetable_entryUUID}"
        };
    };
    rpc TimetableEntriesByTimetable(TimetableEntriesByTimetableRequest) returns (TimetableEntriesByTimetableResponse){
        option (google.api.http) = {
            get: "/v1/timetable/entry/timetable/{timetableUUID}"
        };
    };

    rpc Lesson(LessonRequest) returns (LessonResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/{lessonUUID}"
        };
    };
    rpc CreateLesson(CreateLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/lesson"
            body: "*"
        };
    };
    rpc PatchLesson(PatchLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/lesson/{lessonUUID}"
            body: "*"
        };
    };
    rpc DeleteLesson(DeleteLessonRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/lesson/{lessonUUID}"
        };
    };
    rpc ListLessons(ListLessonsRequest) returns (ListLessonsResponse){
        option (google.api.http) = {
            get: "/v1/timetable/lesson/timetable/{timetableUUID}"
        };
    };

    rpc Timetable(TimetableRequest) returns (TimetableResponse){
        option (google.api.http) = {
            get: "/v1/timetable/{timetableUUID}"
        };
    };
    rpc CreateTimetable(CreateTimetableRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable"
            body: "*"
        };
    };
    rpc PatchTimetable(PatchTimetableRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/{timetableUUID}"
            body: "*"
        };
    };
    rpc DeleteTimetable(DeleteTimetableRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/{timetableUUID}"
        };
    };
    rpc ListTimetables(ListTimetablesRequest) returns (ListTimetablesResponse){
        option (google.api.http) = {
            get: "/v1/timetable"
        };
    };
    rpc TimetableByDate(TimetableByDateRequest) returns (TimetableByDateResponse){
        option (google.api.http) = {
            get: "/v1/timetable/at/{date}"
        };
    };
    rpc CurrentTimetable(CurrentTimetableRequest) returns (CurrentTimetableResponse){
        option (google.api.http) = {
            get: "/v1/timetable/current"
        };
    };

    rpc Subject(SubjectRequest) returns (SubjectResponse){
        option (google.api.http) = {
            get: "/v1/timetable/subject/{subjectUUID}"
        };
    };
    rpc CreateSubject(CreateSubjectRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/subject"
            body: "*"
        };
    };
    rpc PatchSubject(PatchSubjectRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/subject/{subjectUUID}"
            body: "*"
        };
    };
    rpc DeleteSubject(DeleteSubjectRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            delete: "/v1/timetable/subject/{subjectUUID}"
        };
    };
    rpc ListSubjects(ListSubjectsRequest) returns (ListSubjectsResponse){
        option (google.api.http) = {
            get: "/v1/timetable/subject"
        };
    };

    rpc Period(PeriodRequest) returns (PeriodResponse){
        option (google.api.http) = {
            get: "/v1/timetable/period/{periodUUID}"
        };
    };
    rpc CreatePeriod(CreatePeriodRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            post: "/v1/timetable/period"
            body: "*"
        };
    };
    rpc PatchPeriod(PatchPeriodRequest) returns (google.protobuf.Empty){
        option (google.api.http) = {
            patch: "/v1/timetable/period/{periodUUID}"
            body: "*"
        };
    };
    rpc DeletePeriod(DeletePeriodRequest) returns (google.protobuf.Empty){
         option (google.api.http) = {
            delete: "/v1/timetable/period/{periodUUID}"
        };
    };
    rpc ListPeriods(ListPeriodsRequest) returns(ListPeriodsResponse){
         option (google.api.http) = {
            get: "/v1/timetable/period"
        };
    };
}