apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./0-namespace.yaml
  - ./acorn-namespace.yaml
  - ./agate-namespace.yaml
  - ./alpha-namespace.yaml
  - ./angel-namespace.yaml
  - ./apocalypse-namespace.yaml
  - ./apple-namespace.yaml
  - ./monitoring-namespace.yaml
  - ./group-namespace.yaml
  - ./rbac-namespace.yaml
